### ISSUE TITLE
Landing Autopilot state machine transition bugs on suborbital hops (Falcon 9-style vehicle)

### ISSUE THREAD

**Issue by dlrk2** [MuMech/MechJeb2#1004]
The bug only occurs with Land at Target. Land Somewhere works perfectly.

Example video: https://streamable.com/wky7f

**Comment by lamont-granquist** [comment]
I've also seen this on suborbital minmus science-grinding hops I think.  The workaround I've used is to never engage the landing autopilot until I've fallen through my apoapsis and I'm on my way down (which isn't what people want to do here).

For some reason the autopilot is getting stuck in the CourseCorrection stage and it just outputs “performing a course correction of about XXX m/s” where XXX just keeps climbing indefinitely -- then when the rocket falls below 500m it switches to FinalDescent, fires the engines, and it is way too late and it all ends badly.

**Comment by lamont-granquist** [comment]
closing this for #1052 and #115
