### ISSUE TITLE
Windows Defender thinks MechJeb2.dll is a Trojan

### ISSUE THREAD

**Issue by futuramaking** [MuMech/MechJeb2#1005]
Hey all,
I'm using version 2.7.0.0-79:
https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/lastSuccessfulBuild/artifact/MechJeb2-2.7.0.0-791.zip

And started getting this:
![image](https://user-images.githubusercontent.com/4301804/37558377-6e9e1496-29d0-11e8-9699-0e69eb54ca64.png)

**Comment by lamont-granquist** [comment]
False Positive:

https://forum.kerbalspaceprogram.com/index.php?/topic/154834-131-anatid-robotics-mumech-mechjeb-autopilot-270-08-january-2018/&page=59&tab=comments#comment-3322945

This is a bug against Windows Defender, there's no issue in MechJeb.

**Comment by lamont-granquist** [comment]
Alternative recommendations to Windows Defender:

https://lifehacker.com/5865356/the-best-antivirus-app-for-windows

**Comment by futuramaking** [comment]
Sounds good, I've manually exclude it from Windows Defender scans.
