### ISSUE TITLE
"autostage" option does not track amongst different MJ windows.

### ISSUE THREAD

**Issue by christhephish** [MuMech/MechJeb2#1006]
Example. 

open maneuver planner & Rendezvouz Autopilot, Utilities, and Asc. Guidance.  Enable Auto-Warp in M.P. window, setting will carry over to R.A. window & Utils.  

Now, click on Autostage in Asc. Guidance - Utils does reflect status change.    All other shared items in this window pair translate back & forth, autostage does not.

**Comment by sarbian** [comment]
This is on purpose. Some player disliked the autostage after the ascent (it can be dangerous with station for example) and were forgetting to turn it off.
