### ISSUE TITLE
Script for surface smart ass ignores values

### ISSUE THREAD

**Issue by Darinth** [MuMech/MechJeb2#1007]
Utilizing build 791, the scripting module seems to ignore the values put in for scripting the surface smart a.s.s. 
![image](https://user-images.githubusercontent.com/4502486/37674075-58d2821c-2c48-11e8-832d-9684df46b61f.png)

If I run that script, surface mode gets turned on but the values are ignored and it just continues to go straight up. It'll actually overwrite values that I might've put in there myself and revert the rocket to heading/pitch 90 and roll 0 no matter what values are specified.

**Comment by sarbian** [comment]
Funny that no one noticed before :)

**Comment by Darinth** [comment]
Gonna guess that there's just not much interest in automating ascent prior to having ascent guidance, which was what I was trying to do here. Thank you for the fix good sir! :)
