### ISSUE TITLE
DLC thrust plate does not autostage.

### ISSUE THREAD

**Issue by AlonzoTG** [MuMech/MechJeb2#1008]
Normal launch with an upper stage engine configuration based on the DLC thrust plate fails to stage. the plate includes mounting nodes, a shroud, and a decoupler, and does not require any additional decoupler parts. 

This craft is utterly conventional except it takes advantage of the variable length of the plate part and the concavity of the SAS wheel to shorten the length of the rocket, because of this it uses separation motors to help ensure a reliable launch.... Basically, this is a 5 minute build. I launched it from Woomerang, the new launch site to 333km orbit...) I did have to manually stage it. The log file around that time is extremely boring, many thousands of "remaining in ascent" messages and then the craft reconfiguration messages when I staged... 

[Thrust plate example craft_.craft.zip](https://github.com/MuMech/MechJeb2/files/1831993/Thrust.plate.example.craft_.craft.zip)

**Comment by sarbian** [comment]
Newest dev has the fix.
Your "stock" craft had Novapunch parts.
