### ISSUE TITLE
Aborting Landing within Scripting Module

### ISSUE THREAD

**Issue by merket** [MuMech/MechJeb2#1009]
Hello,
I'm trying to configure a two staging landing.. Using different stages for different altitudes.
But once I give an autoland command and it triggers, even from "ELSE" state, I can not stop it.
I guess the script can not interrupt and doesn't count the command "Done" it unless the vessel lands.

I would like to be able to cancel the landing command move on to next step, or execute the IF part, when the conditions are met.

I'm not sure If I could explain myself clearly but in short I would like to learn how to abort autolanding within the scripting module.

Also where are the global scripts saved in harddrive, I'd like to copy paste my code to show what I'm trying to do.

Thanks everybody in advance.

**Comment by lamont-granquist** [comment]
Inserting code into the middle of the Landing Autopilot via the scripting interface is not supportable.  Fixing the Landing Autopilot to handle multiple stage burns is very hard, but part of #1052
