### ISSUE TITLE
Antennas don't work anymore

### ISSUE THREAD

**Issue by ChuckWheat** [MuMech/MechJeb2#1010]
since the recent update. Building something with MechJeb will prevent the antennas from working. I put MechJeb on a fuel tank with batteries and every kind of antenna and the Engineer's Report still says I don't have an antenna... :(

Removing MechJeb solves this issue. Clean install and fresh game and fresh mechjeb install without any other mods didn't fix the issue. It seems to be exclusively an issue with MechJeb.

or am i missing something?

**Comment by lamont-granquist** [comment]
can't imagine what would cause that and nobody else is reporting it.
