### ISSUE TITLE
DeltaV calculations in editor incorrect

### ISSUE THREAD

**Issue by Darinth** [MuMech/MechJeb2#1012]
Running into issues with the DeltaV calculations in-editor with the most recent 1.4 builds

![image](https://user-images.githubusercontent.com/4502486/38165920-a466beec-34e9-11e8-91b6-d0443027174a.png)
![image](https://user-images.githubusercontent.com/4502486/38165930-ce80be44-34e9-11e8-899a-168aedb76dce.png)

Those are both the same ship in the editor and on the pad. The numbers on the pad appear to be correct, the numbers in the editor are definately not. While I have a number of mods installed, the ship itself is completely stock I think. It's basically a terrier powered probe carrying a sentinel to go out to solar orbit. A skipper powered center stage with a pair of mainsail outer stages. Both mainsails and skipper fire at the same time, mainsails are decoupled when they run out of fuel. Skipper is decoupled just prior to circularization. Running into issues with all of my ships that fire two sets of engines at the same time and have one set get decoupled when it runs out before the other set.

Full List of Mods: [x] Science!, AT_Utils, USITools, CCK, CRP, ConfigurableContainers, EasyVesselSwitch, Firespitter, GroundConstruction, Hangar. KAS, KIS, Infernal Robotics, MechJeb2, ModularFuelTanks, SCANSat, ShipManifest, StageRecovery, TriggerTech, Most of USI, Waypoint Manager, OSE Workshop.

Craft file to this ship: [IR Probe.zip](https://github.com/MuMech/MechJeb2/files/1865761/IR.Probe.zip)

**Comment by sarbian** [comment]
Thanks. It turns out an optimization i made did not work well in the editor...
