### ISSUE TITLE
Landing Guidance System barely working

### ISSUE THREAD

**Issue by Ssssusrgf** [MuMech/MechJeb2#1013]
Hi, 
i reinstalled Mechjeb a few days ago, because i remembered it from a year ago, when i used it to create Planetary Bases, as i was barely able to land where i wanted, before i discovered Mechjeb's guidance system.
I progressed far enough again to be able to start building a base on Mun, but i ran into serious problems with Mechjeb.

1. with any autopilot:
When the autopilot wants to auto-warp somewhere for coasting, etc., the time warp multiplicator climbs up to x10 and immediately drops down to x1 again, therefore only stuttering forward.
2. with "Land on target" autopilot:
Autopilot only works below a certain height. When i try to activate it high above Mun, the autopilot status is visible for the time of the link and then disappears again. It seems that the autopilot is aborting immediately after i try to start it. When i got below a certain height, it starts normally (does a course correction and then brakes), the problem is, this happens way too late, in a height where it should brake already, resulting in a crash because it cannot stop the vessel in time. Also, because the course correction happens so late, it burns a lot more fuel.

Are you familiar with this problem, have i done something wrong?

I'm using KSP 1.4.1 and Mechjeb 2.7.3 and used CKAN to install the mod.

I will attach a video recording of the problem in the next few hours.

**Comment by Ssssusrgf** [comment]
Well, i can't upload the video, because github doesn't like the format and it's too large as well.

I instead uploaded it to MEGA: https://mega.nz/#!twJSxSaQ!MizyPjIuqFg7DZ9j-SK_RbZY0M4JPEd7LtSYrJX8dcY

The video shows, how the "Land at target" autopilot doesnt work. I then Warp to a lower point and brake a bit with Stage 2, to avoid a crash. You can then see, that the "Land at target" autopilot suddenly works (before i acitvate the next stage) and then does a course correction. Afterwards, it coasts towards the braking point, but slops down the warping speed to x1 3 times (mostly, it does more of these "hops", but it was only a short distance). Then the autopilot proceeds to brake normally and lands perfectly.

**Comment by doubt72** [comment]
That video: hmm, I can see why Github doesn't like that video. Can't read it, wouldn't willingly install Adobe software to read it.

That said, what are the thrust-to-weight ratios of the landing stages?  This is something I've run into a lot for difficult landings (Tylo, bases, etc.): anything with a TWR too close to 1 (or God forbid, less than 1) isn't going to work very well if it works at all.  The solutions break down and it will abort.  You generally want at least 2 (4 or above is better if possible for efficiency reasons and what I always aim for, though not absolutely necessary).

**Comment by Ssssusrgf** [comment]
I'll look into it as soon as I can, but I can assure, that there is more than enough thrust, to make the landing with ease (in the video, i was able to land, even though the autopilot working that late)

**Comment by joelmeaders** [comment]
I noticed the latest version of MJ does indeed have some pretty big landing issues with Land At Target. It doesn't work on any of my old ships that it used to work on either. Phase change works, initial target burn works and then it goes haywire - stuttering the engines like crazy, over and undershooting by 100's of km with no atmosphere (and with) from various heights. TWR's tested range from 1.18-16

Unfortunately I installed other mods recently so I can't rule those out - they were all parts packs except for BetterBurn Time.

**Comment by joelmeaders** [comment]
Here are a ton of screenshots with debug log up and other information, I hope it helps. Plane Change was perfect, afterwards it stuttered the engines easily 500x before doing a flip and crashing at around 30ms. This is a far better guided landing than other recent experiences.

(Side note: Upon leaving I thought I would try ascent guidance to 12k and it put me at 12k on a suborbital crash course and did not circularize even though "skip particularization" was not checked. It didn't warp or create the node either.)

![screenshot0](https://user-images.githubusercontent.com/26804420/38530307-0faf86cc-3c27-11e8-938b-81afe497f1b0.png)
![screenshot1](https://user-images.githubusercontent.com/26804420/38530308-0fc395b8-3c27-11e8-8dbf-4ad6745e51d2.png)
![screenshot2](https://user-images.githubusercontent.com/26804420/38530309-0fd7c7d6-3c27-11e8-8d93-a018935ff647.png)
![screenshot3](https://user-images.githubusercontent.com/26804420/38530310-0fef028e-3c27-11e8-8fae-bb1c2afd7870.png)
![screenshot4](https://user-images.githubusercontent.com/26804420/38530311-10065d8a-3c27-11e8-96af-1e2e4376a508.png)
![screenshot5](https://user-images.githubusercontent.com/26804420/38530312-101bbcf2-3c27-11e8-852f-1f27ac201084.png)
![screenshot6](https://user-images.githubusercontent.com/26804420/38530313-102fbd7e-3c27-11e8-813f-3f5aae8b215f.png)
![screenshot7](https://user-images.githubusercontent.com/26804420/38530314-1043760c-3c27-11e8-9beb-86f7e43e720d.png)
![screenshot8](https://user-images.githubusercontent.com/26804420/38530315-1056fd62-3c27-11e8-8e9a-668d4cc5b5a7.png)
![screenshot9](https://user-images.githubusercontent.com/26804420/38530316-106bd2a0-3c27-11e8-92ed-489e812eacae.png)
![screenshot10](https://user-images.githubusercontent.com/26804420/38530317-1082cd0c-3c27-11e8-9804-28e1326e0398.png)
![screenshot11](https://user-images.githubusercontent.com/26804420/38530318-109aae40-3c27-11e8-82af-61c135809699.png)
![screenshot12](https://user-images.githubusercontent.com/26804420/38530319-10aef8d2-3c27-11e8-8f2d-5160992ca0d8.png)
![screenshot13](https://user-images.githubusercontent.com/26804420/38530320-10c4cd7e-3c27-11e8-8c38-2ed1db1317c5.png)
![screenshot14](https://user-images.githubusercontent.com/26804420/38530321-10dbc4de-3c27-11e8-98f4-03e3f3496d8c.png)
![screenshot15](https://user-images.githubusercontent.com/26804420/38530322-10edc350-3c27-11e8-917c-347a7277bbdc.png)
![screenshot16](https://user-images.githubusercontent.com/26804420/38530323-1103a9f4-3c27-11e8-918b-57f1d13b9196.png)

**Comment by DanTheColoradan** [comment]
Same issue, but I haven't tried to fix it so it could be bad design. Sometimes my Kerbs build my ships wrong ;-)

**Comment by DanTheColoradan** [comment]
It would seem mine was bad design. Sorry for the false alarm!

**Comment by lamont-granquist** [comment]
closing in favor of #1052
