### ISSUE TITLE
Auto-landing should aim for a flat spot

### ISSUE THREAD

**Issue by tilo** [MuMech/MechJeb2#1022]
it would be awesome if MechJeb could laterally translate to a flat spot shortly before touchdown

**Comment by Zengas** [comment]
I second that. Alot of times that I've fliped my ship after Mechjeb landed it in a slope.
The lander module could do a scan of the terrain in a radius of the target (that we could change that radius) and chose the target with least inclination to land, prefereably 0º.

**Comment by lamont-granquist** [comment]
oft requested, tracking in #1052, closing as dup
