### ISSUE TITLE
Problem with debugging

### ISSUE THREAD

**Issue by denix56** [MuMech/MechJeb2#1023]
Hi everyone.

 I would like to make some contributions to MechJeb, but I can`t debug it. When I connect Visual Studio unity debugger to the ksp debug exe, the plugin debug is not working. I have built plugin with debug flag, placed mdb near dll in but it does not work.

When I tried monodevelop, tht comes with Unity, it does not show my ksp in the list to debug.

P.S. I followed instructions mentioned on ksp forum t debug plugin.

Could anybody help me with it?

**Comment by sarbian** [comment]
Did you launch KSP in dev mode with the modified exe ? You should have a "development" text in the lower right (?) corner.
KSP shows up in "Attach Unity Debugger" list in VS ?
If you attached properly what did you try to do ? Breakpoints ?

With the current MJ project it should build the mdb and copy everything needed as long as you have a PDB2MDB env variable that contains the full path to pdb2mdb.exe (for me C:\Games\Tools\pdb2mdb\pdb2mdb.exe) and KSPDIR that contains the path to KS install (for me C:\Games\ksp-win_dev)




And here is a link to the pdb2mdb.exe I use
https://www.dropbox.com/s/51zvg82nqqv3vbr/pdb2mdb.exe?dl=0

**Comment by denix56** [comment]
After some manipulations with visual studio (added missing references and setup correct post-build event) now it builds with msvc and debugs correctly, don`t know, what exactly helped)
