### ISSUE TITLE
Wrong SLT in VAB / SPH

### ISSUE THREAD

**Issue by DasSkelett** [MuMech/MechJeb2#1024]
Hello there,
please forgive me if I've missed an already existing issue for this bug, I found none on my quick search.

## Versions + Installed Mods + LOG
KSP version: **1.4.3 (already existed on 1.4.2)**
MechJeb version: **2.7.3.0**
List of mods:
![installedmods](https://user-images.githubusercontent.com/28812678/39668297-24797f92-50ca-11e8-87e2-530056f5d009.JPG)
LOG: 
https://www.file-upload.net/download-13115468/output_log.txt.html

## Problem:
In the VAB (and SPH), MechJeb displays the wrong SLT. Instead of real SLT, it displays the space TWR:
![mechjeb1](https://user-images.githubusercontent.com/28812678/39668273-836f1ea4-50c9-11e8-8289-2cb531ca916a.png)

But on Launchpad / Runway all values are fine again:
![mechjeb2](https://user-images.githubusercontent.com/28812678/39668274-867467ee-50c9-11e8-8cbb-d5e24d656ac5.png)

Found an exception in the log, don't know if it has sth to do with this:
```
[MechJeb2] Exception in MechJebModuleStageStats.StartSimulation(): System.NullReferenceException: Object reference not set to an instance of an object
  at MuMech.MechJebModuleStageStats.StartSimulation () [0x00000] in <filename unknown>:0 
  at MuMech.MechJebModuleStageStats.StartSimulation () [0x00000] in <filename unknown>:0
```

Thanks for your efforts!

**Comment by sarbian** [comment]
Do you see the slider that is set to 70km? Move it back to 0 😁

**Comment by DasSkelett** [comment]
Ah sh't 😄  🤦‍♂️ 
Thanks!
