### ISSUE TITLE
Staging issue - engines

### ISSUE THREAD

**Issue by Gilph** [MuMech/MechJeb2#1028]
In V1.4.3 and dev v800:

If the Default Throttle in Prelaunch setting is set to 0, the engines on the second and later stages will activate, but the throttle will be set to zero. You have to hit the z key in order for the thrust to turn on.

Steps:

1. create a simple two stage rocket and make sure staging is correct. Have a MJ pod on upper stage
2. launch rocket. Note that throttle is 0
3. under utilities, turn on autostage
4. press spacebar to launch
5. when first stage completes, autostage will activate decoupler and activate engine, but throttle is set to 0. the Z key must be pressed to set to 100%.

It seems that the prelaunch throttle setting is affecting the throttles of engines post launch.

Please let me know if you need anything further. Thanks

**Comment by lamont-granquist** [comment]
pretty certain this one got fixed
