### ISSUE TITLE
"fine tune closest approach to target" has been more accurate before

### ISSUE THREAD

**Issue by Gordon-Dry** [MuMech/MechJeb2#1031]
Actually using dev #801 I see that I can't fine tune anymore as intended, I have to enter different values and by try and error coming near the desired result.

See:
1. I enter 200 km periapsis
https://i.imgur.com/8b81xQ1.png

2. I get this (117.988 km periapsis)
https://i.imgur.com/gzBDOvQ.png

I have to repeat this about a dozen times or more to find a value to enter that makes the periapsis as I want it to be.

**Comment by lamont-granquist** [comment]
Maybe #1055

**Comment by lamont-granquist** [comment]
bug won't get fixed, it needs to be tossed and rewritten
