### ISSUE TITLE
Landing Predictions Broken In 1.4.4

### ISSUE THREAD

**Issue by at5148** [MuMech/MechJeb2#1037]
I have mechjeb v 2.7.3, worked great in 1.4.2, and all other versions.  But, I just upgraded to 1.4.4 and landing predictions are now broken.  It used to be pretty consistent, with small variations I think from recalculating the path and estimating, but now they're all over the place.  I loaded the same save game 4 times in a row and got 4 different predictions, all about 20 or 10 km apart, almost exactly.  I also noticed that rotating your ship will change the prediction by up to 20 ish km.  Towards normal, purple triangles makes it lower, usually by about 20 km, starting just past 45 degrees, the times that I noticed this. 
 Rotating it other directions can also change it in what seems like random ways, but that doesn't mean it's necessarily random.  Other times rotating will have no effect or a small effect.  I also deleted a maneuver node, and instead of going back to the original prediction, it was off from the original by I don't remember, either 20 or 40 km.  Don't know if it's related or not but it also seems much faster.  A far out orbit I had used to take 20-30 seconds to calculate (from way out there), now it takes 5-10 at most.  
I landed a ship in 1.4.2, and am now landing an identical one in 1.4.4, and I can tell just looking at it and comparing the predictions to their Pe's, which are the same, that it's off by at least 80 - 100 km, + or - a random number of 10 and 20 km's.  These are from atmospheric landings on Eve.

**Comment by lamont-granquist** [comment]
should be fixed by the revert in e0c2515361494aaa0f787b460e87427342bb0766
