### ISSUE TITLE
RCS in landing guidance 2.7.3 in KSP 1.4.5

### ISSUE THREAD

**Issue by Fitz0uille** [MuMech/MechJeb2#1040]
Hello, 

I have just tried to land with the landing guidance on Minmus.
I didn't have any RCS on my vessel so I had uncheck the use RCS for small adjustement

During the landing phase it try to use them and stay lock in a sort of loop.
the link in the forum didn't work so i don't know how to send here the debug of this situation.

**Comment by lamont-granquist** [comment]
probably a dup of many other landing guidance bugs referenced off of #1052
