### ISSUE TITLE
Ascent Guidance cannot toggle navball target

### ISSUE THREAD

**Issue by CWHS** [MuMech/MechJeb2#1042]
Have tried multiple version stable or dev build, on all vanilla KSP 1.4.
All checkbox and option combination and ascent profile

Ascent Guidance cannot toggle navball target by the function "Show ascent navball guidance"

Unless Engage autopilot, the target will keep updating flawlessly 
Once autopilot disengage, target will frozen on the moment when you disengage AP.

Of course AP works to archived a orbit, but this function used to worked on prior KSP 1.4.
Sometimes display the ascent path on navball would useful if doing some complicated manual ascent maneuver. Appreciate if any assistant.

**Comment by lamont-granquist** [comment]
I don't think there's any available time to work on changing this behavior.
