### ISSUE TITLE
(Don't know where to put this) Landing guidance needs to be improved

### ISSUE THREAD

**Issue by imanairconditioner** [MuMech/MechJeb2#1045]
I really want to see an overhaul of the landing guidance, the one thing I see needs a bit of work. When I get Mechjeb to land on something (like a barge), it seems to just land wherever its horizontal speed reaches zero. I want a mode where MJ will not pass a certain threshold (How far I'll let it land away from the target) and if it does, it either does a hop or drifts towards the target and then lands. Also, instead of locking to retrograde, when it gets slow, don't make it follow retrograde leading to growing (and often deadly) oscillations, make it stay vertical to an extent.

Also, none of the links at the bottom of your post work and the manual tried getting me to install what I can only assume to be a virus or bitcoin miner.

**Comment by lamont-granquist** [comment]
closing as dup of #1052
