### ISSUE TITLE
Does Ascent Guidance / Cirularization take retro SRB into account?

### ISSUE THREAD

**Issue by Gordon-Dry** [MuMech/MechJeb2#1049]
It seems that the dV of retro SRB to get rid off spent stages is calculated as positive dV because all circularization burns since I use the dev 804 are offset.

250km comes out as 278km / 219km (RSS).

**Comment by Gordon-Dry** [comment]
At the end of that session I had a huge exception spam about planting a flag ...
https://forum.kerbalspaceprogram.com/index.php?/topic/178829-plant-flag-on-earth-explosion-sound-no-controls-log-spam/

**Comment by Gordon-Dry** [comment]
Full log and stuff:
https://www.dropbox.com/s/bhrz3bhiyrcd9nd/2018-10-09_1%20KSP.log%20and%20stuff.7z?dl=1

**Comment by lamont-granquist** [comment]
Gotta give more information about what ascent guidance you're using.  There's three different versions of ascent guidance in stock.  If you're using 804 and not my PEG build but are using the Atlas-Centaur "PEG" guidance, then the code there is pretty much all abandoned and bugs have either been fixed or are not longer applicable -- that is 2 generations behind at this point.  If you're using PEG ascents with RSS and don't have "skip circularization" checked then that will only cause problems (newer guidance will have options that don't apply to the particular ascent style removed from the menu to reduce confusion).

**Comment by Gordon-Dry** [comment]
Actually I use 804 with Classic Ascent Guidance.

**Comment by lamont-granquist** [comment]
Those algorithms all just burn down the dV of the node that gets placed to circularize which doesn't even bother to care about the stage dV calculation or whatever retros might be there.

**Comment by lamont-granquist** [comment]
Similar to RT devs, can't reproduce or concieve of what code might be wrong.
