### ISSUE TITLE
Mechjeb for version 1.4 not compatible with KPS 1.5

### ISSUE THREAD

**Issue by pcanoe** [MuMech/MechJeb2#1069]
Dear sir or madam

Mechjeb for version 1.4 not compatible with KPS 1.5. When I install it in Steam then I have an error. When I start KPS I  message saying one mod is not compatible with 1.5 and this is the only mod I installed. I have a brand new installed KPS 

Thank you

**Comment by sarbian** [comment]
Mechjeb v2.8.1 is compatible with KSP 1.5. Check if you have this version.
