### ISSUE TITLE
KSP 1.6?

### ISSUE THREAD

**Issue by SylcanAbly** [MuMech/MechJeb2#1088]
Just started with KSP again - sadly I have KSP `1.6.0` which does not seem to support MechJeb2 `2.8.1.0`. Is there a solution, or do I just need to be patient? Remember old MechJeb - and loved it!

**Comment by lamont-granquist** [comment]
there were no code changes from 1.4 to 1.6, the latest CKAN version will work on 1.6 without recompilation, or use the latest dev branch: https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/
