### ISSUE TITLE
Script Ascents need to support Launch to Rendezvous / Plane / Interplanetary

### ISSUE THREAD

**Issue by lamont-granquist** [MuMech/MechJeb2#1105]
As part of fixing most everything to do with scripted ascent guidance in #1103 / #1104 I broke these features and then ran out of gas.

I suspect if the state was handled better in the AscentAutopilot that it could be fixed without changes to the scripting code.

Also need to have autowarp config added to the ascent scripts (just saving the node executor state throws, so probably do need to save + restore this one setting as a one-off)

**Comment by RenatoUtsch** [comment]
Any updates on this? I'm trying to use launch to rendezvous and it takes me to around 200km after the target.

If you can provide me with pointers I can try to take a crack at this issue.
