### ISSUE TITLE
Tweaks to Jenkins for Sarbian

### ISSUE THREAD

**Issue by lamont-granquist** [MuMech/MechJeb2#1107]
-  The CKAN repo job ( https://ksp.sarbian.com/jenkins/job/MechJeb2-CKAN-REPO/ ) could have its metadata tweaked so that new dev builds have:

```
    "ksp_version_min": "1.4.0",
    "ksp_version_max": "1.6.9",
```

- MechJeb2-RO could be renamed MechJeb2-KSP13 or something like that and turned into a 13 backport branch.  We'd need a "Revert_to_1.3.diff", but the problem is that the shaders are binary, so a plain old GNU diff/patch won't work.

**Comment by sarbian** [comment]
The min/max part is done. I'll think about how to deal with the RO version later.

**Comment by lamont-granquist** [comment]
:+1:

**Comment by lamont-granquist** [comment]
@sarbian looks like build 844 and 845 didn't make it into the tarball.  Downloading MechJeb2-ci.tar.gz it looks like the last one is 843 and there's this in the output of the job which might be an error:

```
+ /home/ksp_www/rebuildRepo.py 1.4.0 1.6.99 2.8.1.0 845 https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/845/ MechJeb2-2.8.1.0-845.zip /home/jenkins/jobs/MechJeb2-Dev/workspace/MechJeb2-2.8.1.0-845.zip
Can not find the file MechJeb2-2.8.1.0-845.zip
```

https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/845/console

**Comment by sarbian** [comment]
Yeah, it works better when I edit the script on the active server instead of the old one...

**Comment by lamont-granquist** [comment]
not as bad as the old `shutdown -r now` on a dev box and then realize you just rebooted production ...
