### ISSUE TITLE
[Suggestion] Stage before circularization.

### ISSUE THREAD

**Issue by YpsilonTM** [MuMech/MechJeb2#1117]
Hi,

I was wondering if it's possible to add a function in the ascent module that stages before circularization (for example at a periaps of 35 km) and a text box of the desired stage at circularization.
Why would I like this... , to reduce space debris. Often I get a lifter in orbit with like 50m/s Delta-V. So this feature would be nice to dump the lifter just before circularization so I get less space debris. I know its inefficient but it makes it a bit more realistic.
Then it would be like the auto stage feature has the stop at stage#. But then you enter the stage number with what you want to end with in orbit.

Just a suggestion though. 
And PS: Thank You for making KSP 10x more awesome for the last years !

## MechJeb Version
2.8.1
## KSP Version
1.6.1

**Comment by lamont-granquist** [comment]
ideally this would be part of #951 done somehow so that all the ascent styles could take advantage of it, and then the PVG optimizer could take advantage of it as well.

**Comment by YpsilonTM** [comment]
I am going to close this because I don't see this happening soon. And I don't like open issues.

Greetings Ypsilon <3
