### ISSUE TITLE
Advanced part filtering does not work in VAB when Mechjeb is installed

### ISSUE THREAD

**Issue by grzegrzk** [MuMech/MechJeb2#1128]
## MechJeb Version
2.8.1.0

## KSP Version
1.6.1

## Description
When you are in "VAB" it is impossible to use filers in "Advanced Mode"

## Replication Case
- Install MechJeb (I tested it with only this single mod)
- Run KSP
- Go to VAB
- Click "Enable Advanced Mode" in top left corner of the screen
- Click "Filter by Cross-Section Profile"
- Select profile sizes one-by-one

The filtering does not work. Moreover from now on even simple filtering will not work - you must exit VAB and enter again to reset it.

## KSP.log

Here is whole log:

https://pastebin.com/DuM4WSb0

I do not see any exception related to Mechjeb. The one that happens when I try to filter the part is:

[EXC 01:38:14.702] NullReferenceException: Object reference not set to an instance of an object
	KSP.UI.Screens.PartListCategories.BulkheadProfile.ExclusionCriteria (.AvailablePart aP)
	EditorPartListFilter`1[AvailablePart].FilterList (System.Collections.Generic.List`1 parts, System.Func`2 filter)
	EditorPartListFilterList`1[AvailablePart].FilterList (System.Collections.Generic.List`1 list)
	KSP.UI.Screens.EditorPartList.RefreshPartList ()
	KSP.UI.Screens.EditorPartList.Refresh ()
	KSP.UI.Screens.EditorPartList.Refresh (State state)
	KSP.UI.Screens.PartCategorizer+<UpdateDaemon>c__Iterator5.MoveNext ()
	UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)
[LOG 01:38:25.214] [MessageSystem] Save Messages

It does not occur when Mechjeb is not installed.

**Comment by lamont-granquist** [comment]
this is already fixed in dev builds by #1125
