### ISSUE TITLE
Zenon craft delta v

### ISSUE THREAD

**Issue by holmesmi** [MuMech/MechJeb2#1139]
## MechJeb Version
2.81

## KSP Version
1.61

## Description
I'm flying my ship, which is down to Zenon fuel and the Dawn engine. The MechJeb delta V window is showing that I've got nothing, but I clearly do.

**Comment by holmesmi** [comment]
This seems to happen with every Zenon craft I have, so replication shouldn't be a problem. I'm assuming you don't need logs, but if you do, let me know, and I'll grab some.

**Comment by sarbian** [comment]
Just replying to say that I have seen your issue. I just need some quiet time to look into it...

**Comment by lamont-granquist** [comment]
Yeah I validated in the VAB and on the pad and with available eC, both on 1.5.x

I'm guessing I broke something in FuelFlowSimulation, but nothing seems obvious to me.

**Comment by sarbian** [comment]
I think it is when you refactored this https://github.com/MuMech/MechJeb2/commit/c3abe3a8444e81b8d10ba1df638389dbb82e3c41#diff-dc9768afe4b434960c417797ed67938aL655

I do not find the check for ResourceDensity > 0 anywhere. I guess the easiest fix would be to add any propellant with a density of 0 to the freeResources list ?

**Comment by sarbian** [comment]
Fix pushed from my lunch break without a compiler around. Followed by a reminder that MJ is not coded in python ( 43fb12f0d4d1e8fe9bd99a8bd202c7cfacd58ec5 )

**Comment by lamont-granquist** [comment]
right that just came up the other day on the RO discord that batteries have a wet mass and dry mass for the batteries, but zero resource density, or something crazy like that.

**Comment by lamont-granquist** [comment]
not working for me unless i did something equally dumb like forget to make install again...  which it looks like i did do...

i'll try to take a look at it later now that i have a good hint...

**Comment by lamont-granquist** [comment]
868 ought to fix this:  https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/868/

**Comment by lamont-granquist** [comment]
@sarbian  You want to do a patch release of the code as it is now?  It seems like this fix for Xenon ∆v and the fix for launch-to-plane might warrant it.  I've got some major changes that I'm thinking about shipping which would risk more destabilization and it feels like this might be a fairly happy point right now.  No rush tho.

**Comment by sarbian** [comment]
@lamont-granquist Yes, we should do a release.
