### ISSUE TITLE
Duplicate icons in science tree.

### ISSUE THREAD

**Issue by ethan-roth** [MuMech/MechJeb2#1158]
## MechJeb Version
2.8.3

## KSP Version
1.7.0.2483

## Description
After adding MechJeb to an existing career mode, the science tree has several branches that contain duplicate icons for certain parts. For example, Advanced Flight Control has 28(!) icons for the Place Anywhere 7 RCS port. Also, Specialized Control has two icons for the Vernor Engine.

## Replication Case
https://imgur.com/a/eHxwwKf

See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) for
information on how to create a good replication case.
-->

**Comment by lamont-granquist** [comment]
Nobody else has reported this and I can't see how this would be MJ (or what to debug, or how to repro or anything).  Would need some more information of some sort to even guess about what bug might need fixing.
