### ISSUE TITLE
1.7 Dev Build Reccomendation 

### ISSUE THREAD

**Issue by enderger** [MuMech/MechJeb2#1159]
## MechJeb Version
 N/A

## KSP Version
1.7.0

## Description
 Do you recommend any beta builds of MechJeb for 1.7.0? 

## Replication Case
MechJeb release does not work on 1.7, but betas do.

**Comment by sarbian** [comment]
As I explained in the forum thread I was on a trip for 4 weeks and will do a release soon.

**Comment by enderger** [comment]
I was more asking what testing build to use until release.

**Comment by sarbian** [comment]
The last one. They are built for 1.7
