### ISSUE TITLE
Aircraft autoland unusably unstable

### ISSUE THREAD

**Issue by cpcallen** [MuMech/MechJeb2#1163]
## Description

The Autoland feature in Aircraft Approach & Autoland seems to be unusably unstable, tending towards wild oscillations in attitude and speed, especially in pitch.  Changing PID values in Attitude Adjustment panel have no effect; indeed, it seems clear that that Autoland is not using the usual SmartASS PID controller because if I click "RESET" in Attitude Adjustment while autoland is running it makes no effort whatsoever to auto-tune itself until I abort autoland and renable SmartASS.

Autoland seems to be using its own separate attitude controller (reasonable enough, given that it should probably be doing banked turns), but its control parameters are unsuitable, especially for large (Mk.3) aircraft with large rotational inertia.

## Steps to Reproduce

1. Load this example craft: [Island Hopper.craft](https://github.com/MuMech/MechJeb2/files/3221627/Island.Hopper.craft.txt)
2. Take off and fly manually to somewhere plausible to start an approach from.
3. Open Aircraft Approach & Autoland.
4. Turn on Navball Guidance.
5. Activate Autoland.

### Expected behaviour

Aircraft aligns itself with target marker, then flies wings level at the configured speed.

### Actual behaviour

Aircraft bucks wildly in pitch, or repeatedly rolls left and right, never making an effort to roll out of the turn until past the desired heading.  (Ironically, the only time I see good pitch stability is during these repeated S-turns.)

With some craft I have, the pitch oscillations will get worse and worse until the craft stalls.

### Desirable additional behaviour

SmartASS allows manual keyboard override, but for some reason Autoland does not.  It would be very good it if did, because then there would be some way to damp down these autopilot-induced oscillations without havnig to disengage Autoland completely.

**Comment by Monniasza** [comment]
It happened to me too. Vessel used: [MegaCarrier.zip](https://github.com/MuMech/MechJeb2/files/3291735/MegaCarrier.zip)
Approach settings: Island Runway 09, approach speed 180, glideslope 3, touchdown speed 60.
G-forces were as high as 6 Gs.
Mods used: AirplanePlus, B9 Aerospace, CommunityCategoryKit, Firespitter, FShangarExtended, JSI, KIS, MechJeb 2, TweakScale, ModuleManager

**Comment by chengyufei** [comment]
It happened to me too.

**Comment by Fadamor** [comment]
I had a similar problem with flying but when using the autopilot for normal cruise. The pitch control of my canards was way too high so it would oscillate the nose up and down for even the smallest pitch adjustments. Turing the pitch control of the canards down to about 30 solved the issue.

**Comment by papasid26** [comment]
can confirm. was testing the other day with opt planes. tried with many different crafts but all of them result in oscillating stalls.
