### ISSUE TITLE
Autoland causes crash

### ISSUE THREAD

**Issue by Monniasza** [MuMech/MechJeb2#1168]
## MechJeb Version
MechJeb2-2.8.3.0

## KSP Version
1.7

## Description
I was flying in 
[MegaCarrier.zip](https://github.com/MuMech/MechJeb2/files/3291735/MegaCarrier.zip)

Mods used: AirplanePlus, B9 Aerospace, CommunityCategoryKit, Firespitter, FShangarExtended, JSI, KIS, MechJeb 2, TweakScale, ModuleManager

## Replication Case
1. Open given aircraft
2. Fly to good approach place
3. Activate autoland
4. Wait until landing

## KSP.log
[output_log.txt](https://github.com/MuMech/MechJeb2/files/3291739/output_log.txt)

## Expected behavior
Aircraft lands smoothly

## Actual behavior
Two engines crashed

**Comment by lamont-granquist** [comment]
closing as a dup of #1163
