### ISSUE TITLE
Breaking Ground Scanner Arm affects Rover Autopilot Stability Control

### ISSUE THREAD

**Issue by TonkaCrash** [MuMech/MechJeb2#1171]
## MechJeb Version
MechJeb Dev #889 but was first noticed in earlier versions

## KSP Version
KSP 1.7.2 with Breaking Ground DLC only other mod installed was Module Manager. Rover control keys were remapped to number pad arrow buttons (8246) for forward/reverse/left/right instead of WASD.

## Description

[See related forum post](https://forum.kerbalspaceprogram.com/index.php?/topic/154834-17x-anatid-robotics-mumech-mechjeb-autopilot-284-14-june-2019/&do=findComment&comment=3625282)

Adding a scanning arm to a rover affects MechJeb behavior at low speed. If you engage the Rover Autopilot Stability Control, something is throwing off what MechJeb is using for the requested attitude at low velocities. 

From the video you can see the Requested Attitude Arrow is pointing up and a little left of center at zero velocity. As the rover moves forward it changes to down and a little right. Once speed is up high enough (around 5 m/s) MechJeb settles down to what it should be doing.  

All problems go away without the Scanning Arm on the craft. Moving the location of the scanning arm around the rover changes the Requested Attitude vector at zero velocity. I was unable to find a position to zero out the effect of the arm.

## Replication Case

[youtube video](https://youtu.be/cvdXRmJZI1c)

[Related Craft File](https://www.dropbox.com/s/4821rhkd9ei63ia/MechJeb%20Scanner%20Arm%20Bug.craft?dl=0)

## KSP.log

No warnings, errors or exceptions were if the Log around the time the AP is engaged.

**Comment by Sinomen** [comment]
I have the same issue.

**Comment by lampeh** [comment]
The problem [occurs here](https://github.com/MuMech/MechJeb2/blob/dev/MechJeb2/MechJebModuleRoverController.cs#L180) because the raycast hits the scanning arm's "rangeTrigger" sphere collider on layer 15 ("Local Scenery") and uses its normal vector at that points.

If the velocity is high enough, the ray looks past the scanner and hits the surface again.

Possibly related to an earlier [KSP bug](https://bugs.kerbalspaceprogram.com/issues/22908)

**Comment by lampeh** [comment]
Passing [QueryTriggerInteraction.Ignore](https://docs.unity3d.com/ScriptReference/QueryTriggerInteraction.Ignore.html) to Physics.Raycast seems to be the solution and makes MJ see the surface again. Thanks, [StackOverflow](https://stackoverflow.com/questions/44402021/how-to-make-raycast-ignore-trigger-colliders).

```
diff --git a/MechJeb2/MechJebModuleRoverController.cs b/MechJeb2/MechJebModuleRoverController.cs
index 7375ddbc..d49c53c1 100644
--- a/MechJeb2/MechJebModuleRoverController.cs
+++ b/MechJeb2/MechJebModuleRoverController.cs
@@ -177,7 +177,7 @@ public void CalculateTraction()
                {
                        if (wheels.Count == 0 && colliders.Count == 0) { OnVesselModified(vessel); }
                        RaycastHit hit;
-                       Physics.Raycast(vessel.CoM + vesselState.surfaceVelocity * terrainLookAhead + vesselState.up * 100, -vesselState.up, out hit, 500, 1 << 15);
+                       Physics.Raycast(vessel.CoM + vesselState.surfaceVelocity * terrainLookAhead + vesselState.up * 100, -vesselState.up, out hit, 500, 1 << 15, QueryTriggerInteraction.Ignore);
                        norm = hit.normal;
                        traction = 0;
 //                     foreach (var c in colliders) {

```
