### ISSUE TITLE
UI to big for small screens

### ISSUE THREAD

**Issue by theScrabi** [MuMech/MechJeb2#1172]
KSP: 1.7.2.2556 (Linux)
Mechjab2: 2.8.3.0

UI is to big to be usable on a small screen like 1355x766:

![mechfail mp4](https://user-images.githubusercontent.com/1891273/61175437-abb2ea80-a5af-11e9-9bf4-af4527f56608.gif)

**Comment by sarbian** [comment]
There is an UI scale settings in the "Setttings" tab.

**Comment by lamont-granquist** [comment]
this is also a dup of #1144
