### ISSUE TITLE
Issue with mechjeb and crew

### ISSUE THREAD

**Issue by Hydropi** [MuMech/MechJeb2#1173]
Using Mechjeb version 2.8.3 and KSP version 1.7.3 I have been having an issue when I have a pod filled with crew. When I use the same rocket without crew and just MJ I am able to get into orbit and dock with my station just fine, but when I add a crew member to the capsule on launch my ship not only fails to make orbit but MJ just has it point the other way until the rocket disintegrates into nothing.

![KSP_x64_2019-07-26_21-57-17](https://user-images.githubusercontent.com/5299358/61988528-67ccd600-aff0-11e9-9c5a-256995078037.png)
Example about 20 seconds into flight without a crew member.

![KSP_x64_2019-07-26_21-59-31](https://user-images.githubusercontent.com/5299358/61988551-ae223500-aff0-11e9-9a4e-f476a9948216.png)
Example about 20 seconds into a flight with a crew member.

I have even tried disabling the reaction wheels on multiple parts(including the ones the pilot controls) to try and see if that was the issue and it appears to not be as the exact same thing happens everytime I try with a crew-member on board.

**Comment by lamont-granquist** [comment]
blue nav ball vs orange nav ball. 

presumably you have your crew capsule upside down but you have a normal oriented probe core, but with crew on board your crew capsule gets promoted to be the primary control and "up" becomes "down".

this is just how the KSP game engine works.

**Comment by Hydropi** [comment]
Oh that makes a lot of sense, I did have my capsule oriented upside down to get the fairing to work better, but after fixing this it seems to function perfectly normal
