### ISSUE TITLE
Autowarp doesn't activate in Maneuver Planner

### ISSUE THREAD

**Issue by Monniasza** [MuMech/MechJeb2#1175]
## MechJeb Version
2.8.3.0

## KSP Version
1.7.3

## Description
Time warp doesn't activate when selected in Maneuver Planner

## Replication Case

Build or choose a spaceship
Reach orbit
Design any maneuver in Maneuver Planner
Activate Autowarp

## KSP.log

It's too big

**Comment by Gordon-Dry** [comment]
my two cents::

if the attitude is not 100% perfect (no tolerance or a very low tolerance) then the autowarp does not kick in.

So it depends your vessel somehow.

Perhaps a setting with a slider for the allowed autowarp attitude tolerance could be implemented.

**Comment by Monniasza** [comment]
The autowarp activates only when I type in tolerance.

**Comment by Monniasza** [comment]
Please add autowarp attitude tolerance

**Comment by lamont-granquist** [comment]
It is probably this check for angular velocity which is too low:

https://github.com/MuMech/MechJeb2/pull/973/files

If you manually increase warp one step it should take over though.
