### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by Sinomen** [MuMech/MechJeb2#1178]
If possible, I'd like to set time window margins for the Hohman Transfer Planner as well as for the Advanced Transfer Window Planner via numerical user input for within what time frame they should look for a calculation. The Advanced Transfer Planner (pork chop) has this already graphically implemented, but it's quiet a hassle to use this with the mouse pointer, a numerical data input would be much easier to use.

**Comment by lamont-granquist** [comment]
That's probably covered by #1058, although I don't think I explicitly called out the relationship between the porkchop planner in the transfer planner, the need for some kind of porkchop for simple node transfers (hohmann/bi-elliptic) and also with launch to rendezvous planning (which are all, ultimately, rendezvous problems).  There's definitely a meta-UX problem there.

I think I'm going to close this though as a dup of that epic.
