### ISSUE TITLE
Ascent autopilot should add a change inclination burn at equatorial DN

### ISSUE THREAD

**Issue by wac-** [MuMech/MechJeb2#118]
The inclination after launch tends to be a degree (few tens of delta-V) in error. It would be helpful if the ascent autopilot added a corrective burn for inclination at the next equatorial DN after the circularization burn.

**Comment by lamont-granquist** [comment]
Classic Ascents got a lot better with my launch inclination fixes.  PEG solves this very well.  The circularization burn in classic now also tunes the inclination.
