### ISSUE TITLE
Incompatibility with mods such as FireSpitter

### ISSUE THREAD

**Issue by papasid26** [MuMech/MechJeb2#1188]
## MechJeb Version
--- 872-132 Mar10 Release 

## KSP Version
 1.8.0 

## Description
 It's stuck on "Verifying Expansion: Breaking ground SquadExpansion/Serenity" on loading screen. console shows exception: reflectiontypeloadexception: Exception of type "system.reflection.reflectiontypeloadexception"

## Replication Case

i did a fresh install with opt spaceplane parts and firespitter core. i used opt, opt_legacy and opt_reconfig and firespitter core

**Comment by sarbian** [comment]
Where did you get the version of FireSpitter  that was build for KSP 1.8 ?

**Comment by daniyalkrahat** [comment]
From Ckan - MJ prevents loading past *Expansion packs* with firespitter installed which is required by USI in my case - is there a way to use NJ also.?

**Comment by sarbian** [comment]
The last version for Firespitter is "7.13.0 for KSP 1.7.x". Obviously it was not built for KSP 1.8.

CKAN is wrong to allow an installation on KSP 1.8. And I will not do support for other mods problems

**Comment by daniyalkrahat** [comment]
That makes sense - Thank you! There's more than one life support mods, but only one Mechjeb - I know what i must do!

**Comment by enbock** [comment]
Just as info ;) When you remove then Particle FX implementation(does not found other solution yet) from Firespitter and recompile it for .Net 4.0, then work it together with current MechJeb in KSP 1.8 :)

**Comment by merket** [comment]
Hello,

Firespitter has just been updated to v7.14 supporting 1.8, but unfortunately installing mechjeb along with it, still halts the loading of the game =(

**Comment by lamont-granquist** [comment]
The fix is in the firesplitter issue:

https://github.com/snjo/Firespitter/issues/217#issuecomment-547060901

Complaining here won't get it fixed any faster.
