### ISSUE TITLE
MechJeb launch into plane of target time bug

### ISSUE THREAD

**Issue by cbase2** [MuMech/MechJeb2#1193]
## MechJeb Version
2.8.3 + dev fixes for new unity

## KSP Version
1.8

## Description
MechJeb miscalculates time for launch into inclined target orbits. Simple example: Minimus is still 2.8° inclined.

## Replication Case
https://imgur.com/gallery/SXPXSAO

## KSP.log
[KSP.log](https://github.com/MuMech/MechJeb2/files/3777520/KSP.log)

**Comment by cbase2** [comment]
I did dig into LaunchTiming.TimeToPlane, but it is hard to understand with current documentation.

**Comment by lamont-granquist** [comment]
You need to show what the value is of the phase angle next to "launch to plane" is before you press the button to launch.  If that is not zero then you are entering a manual offset in degrees to lead the launch.
