### ISSUE TITLE
Problems with new Kerbal Version (did not start)

### ISSUE THREAD

**Issue by ManfredFuchs** [MuMech/MechJeb2#1195]
Kerbal Space Programm dosn´t Start after the install from MechJeb2.
The Game hang in the Start screen. No Error is on the Screen.

**Comment by sarbian** [comment]
We can not help if you do not share a log, as explained in the issue template. Add a log and reopen the issue.

**Comment by ManfredFuchs** [comment]
Hy Sarbian,
If Mechjeb is installed in the GameData Folder, Kerbal doesnt start. The bar stand by 100% percent and stands. After 20 Minutes I´ve closed the Game. When i removed Mechjeb2, everything is Fine :-(

thx for your help
[KSP.log](https://github.com/MuMech/MechJeb2/files/3800891/KSP.log)

**Comment by sarbian** [comment]
You have a bunch of mods that were not updated for KSP 1.8. Even without MJ you will have problems when playing and may loose your saves.
