### ISSUE TITLE
[Suggestion] Web UI

### ISSUE THREAD

**Issue by 2JS** [MuMech/MechJeb2#1198]
## MechJeb Version

(Not necessary)

## KSP Version

(Not necessary)

## Description

I suggest a KSP hosted local web, which contains all the controls and indicators so that controls can be done on the other display or devices. For example, users may play with a clean KSP window while MechJeb controls are available in my iPad.

**Comment by lamont-granquist** [comment]
Given the other 140 open issues against MJ, many requiring hundreds of hours of code, I think the chances of this one happening are so low that I'm going to close it.

Its more likely that I'll wind up extracting most of the math and state machines in MJ out to a library and someone else could implement this in their own mod if they wanted to (but don't hold your breath on even that first step happening).
