### ISSUE TITLE
[Feature Requests] Please add throttle control to Scripting Module

### ISSUE THREAD

**Issue by Xyphos** [MuMech/MechJeb2#1199]
I like your scripting module, it makes automating tasks a lot easier than trying to make kOS scripts.

But, I feel that it needs a throttle controller since it's currently not possible to start/stop engines without using node execution. this would help control payload deployment after decoupling from a vessel.

in addition, I'd also like to request landing guidance for spaceplanes from orbit. currently, my plane attempts to land on the pad in retrograde instead of the runway in prograde and no known way to abort the landing guidance once it's activated.

Being able to name docking ports individually would help reduce confusion when targeting docking ports. currently, it's trial/error via guess-and-test.

Scrolling would be greatly appreciated, long scripts tend to cause the GUI to go off-screen when not in compact mode.

Thank you for your consideration.

**Comment by BloodyRain2k** [comment]
I'd like to second this request, it's kind of pointless for launch control if it can't even cut the throttle.
