### ISSUE TITLE
Engine spool down is not taken into account of maneuver burn calculation

### ISSUE THREAD

**Issue by Gordon-Dry** [MuMech/MechJeb2#1200]
All my observations point to the same conclusion.

As soon as an engine got engineDecelerationSpeed defined, this spool down time is not taken into account of the calculations for maneuver burns.
This leads to overburning at the end of the maneuver.

The bigger the engine/the greater the spool down time, the higher the overburn.

**Comment by lamont-granquist** [comment]
I think that's known in some other bug that I can't find.

It's also not likely to get fixed any time soon.

Probably up to a user that cares deeply about that to patch MJ to make it work.

**Comment by lamont-granquist** [comment]
Closing this as I can't see anyone getting the time to work on it, and suspect it'll never be fixed.
