### ISSUE TITLE
Landing Guidance Warp Issue

### ISSUE THREAD

**Issue by GalacticRuler** [MuMech/MechJeb2#1205]
## MechJeb Version
2.9.1.0 (Acquired from Curse)

## KSP Version
1.8.1

## Description
the Landing Guidance module seems incapable of maintaining a steady warp to its next target along a descent path. (It can warp successfully to a Deorbit burn, however) It stutters back and forth between 1x and 5x speed.

## Replication Case

https://youtu.be/qQGjRF-rFRQ As shown in the video
This persists across all vehicles that I attempt to land; no matter they type or parts.

## KSP.log
Log contains no useful information; aside from warp-stutter related pack/unpack spam

**Comment by GalacticRuler** [comment]
Actually, the landing guidance autopilot may simply be interrupting all warping while coasting; once Autowarp was disabled and I attempted to manually warp and it took the timescale back down to x1

**Comment by lamont-granquist** [comment]
dup of #992 and #967 ?

**Comment by GalacticRuler** [comment]
Likely a dupe; sorry

I searched but could not find anything
