### ISSUE TITLE
Spawning a probe core in KIS 1.23 locks up the game (1.8.1)

### ISSUE THREAD

**Issue by millenniumtree** [MuMech/MechJeb2#1206]
## MechJeb Version
2.9.1.0

## KSP Version
1.8.1

## Description
The minimum requirements for reproducing the error are:

Kerbal Inventory System (KIS) 1.23
MechJeb2-2.9.1.0

## Replication Case
Enable itemDebug in KIS settings.cfg, start a new game, put jeb in a lander can, EVA, press tab to open the inventory, spawn the HECS2 probe core (or any other probe).

The inventory window goes gray and you can't do anything. The game appears to be locked up, but it's not COMPLETELY frozen - you just get about 1 frame every 10-60 seconds.

Doing this produces a NullReferenceException: Object reference not set to an instance of an object.

I posted this on the KIS github, and they've sort of worked around the issue in 1.24, but it doesn't solve the whole issue. See the KIS issue here: https://github.com/ihsoft/KIS/issues/354

Obviously not many people are going to be spawning probe cores or lander cans with a debug option of a completely different mod, but maybe this is easy to solve, or the error could be triggered in some other way heretofore unknown.

## KSP.log
https://github.com/ihsoft/KIS/files/3929882/KSP.log

**Comment by lamont-granquist** [comment]
sarbian already answered in that thread that you linked to:

https://github.com/ihsoft/KIS/issues/354#issuecomment-562983928

opening an issue here doesn't change that answer
