### ISSUE TITLE
Mechjeb not showing correctly .

### ISSUE THREAD

**Issue by Hendrivdv** [MuMech/MechJeb2#1210]
Hey.

I am having a problem with mechjeb 2 on ksp 1.8.1 as the attached picture is showing please need help
![Untitled](https://user-images.githubusercontent.com/59209177/71423459-3edd6980-2692-11ea-86d8-1e2132f7df4a.png)

**Comment by Hendrivdv** [comment]
See its almost impossible to read

**Comment by Hendrivdv** [comment]
Every thing start with #Mechjeb

**Comment by lamont-granquist** [comment]
You probably have wound up with a build missing GameData/MechJeb2/Localization/en-us.cfg, latest dev build should fix that.

**Comment by Hendrivdv** [comment]
thank you
