### ISSUE TITLE
1 more warp

### ISSUE THREAD

**Issue by alexzk1** [MuMech/MechJeb2#1212]
## MechJeb Version

2.9.1

## KSP Version
1.8.1

I play carier mode, so was unlocking abilities. All was OK, until I got last "randevuz", then I started to see, that maneur planer do not warp ...
I think I found what is it - "auto warp" checkbox into "randevuz autopilot" window is unchecked by default and it stops all kinds of warps as well.
So once I did additional step - opened that window and checked box all is back to normal. But that is bug as for me ... local ability controls global setting.
Upd: oh well, I figured maneurs box has "auto warp" checkbox too, but I was reading it as "Auto warp Tolerance" because of that close design ... Maybe you can just split it a bit or add some visual separator....it confuses. Also un-checking this box by another windows confuses as well. Maybe some color attraction - like red when unchecked?

**Comment by lamont-granquist** [comment]
this is really just working as designed, there's a known learning curve to MJ, it has a lot of dials and buttons.
