### ISSUE TITLE
Need to update for version 1.9.x

### ISSUE THREAD

**Issue by elonmuskforpresident** [MuMech/MechJeb2#1234]
## MechJeb Version
2.9.1

## KSP Version
1.9

## Description

basically i just downloaded it today 15//02/2020 ad it says doesnt work for 1.9.x version, you just need to update

**Comment by sarbian** [comment]
2.9.2 was released yesterday and does not display the message on KSP 1.9.

**Comment by elonmuskforpresident** [comment]
where i can download it?

**Comment by elonmuskforpresident** [comment]
also very fast response, i like that

**Comment by sarbian** [comment]
From the KSP forum MechJeb thread.
https://forum.kerbalspaceprogram.com/index.php?/topic/154834-19x-anatid-robotics-mumech-mechjeb-autopilot-292-14-february-2019/
or directly from the build server
https://ksp.sarbian.com/jenkins/job/MechJeb2-Release/

**Comment by elonmuskforpresident** [comment]
thank you
