### ISSUE TITLE
MJ causes game to stutter

### ISSUE THREAD

**Issue by PotatoesForEternity** [MuMech/MechJeb2#1243]
## MechJeb Version
2.9.2.0

## KSP Version
1.9

## Description
In the VAB, when i place or grab parts, i notices stutters and pauses that last around .5 - 2 seconds. In flight, i also notice stutters that last around 1 second. Stutters happen more severly when i place command parts, however the stutters are still appearant no matter what.

## Replication Case
https://imgur.com/a/7RGHW1Q

## KSP.log
https://gist.github.com/PotatoesForEternity/597f00f3402f3f109d5151ba9b5ebcc2

**Comment by sarbian** [comment]
The log does not have anything that could explain it. Are you sure it only happens when MY is installed ? And can you give the specs of your PC ?

**Comment by PotatoesForEternity** [comment]
> The log does not have anything that could explain it. Are you sure it only happens when MJ is installed ? And can you give the specs of your PC ?

Yes, the stutters only occur when MJ is installed. here are my specs:

AMD Ryzen 5 1400 Quad Core Processor
16 Gb RAM
RX 580 GPU

**Comment by lamont-granquist** [comment]
If you go back to build 935 (https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/935/) and ignore the compat checker does that fix the stutter in the VAB and does 936 exhibit the stuttering?

**Comment by PotatoesForEternity** [comment]
> If you go back to build 935 (https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/935/) and ignore the compat checker does that fix the stutter in the VAB and does 936 exhibit the stuttering?

Stutter still occurs :/ 

One of the things i thought would be possible is the DLC's conflicting with MJ. My friend who has all the same mods as me aswell as MJ doesnt have this issue, but he also doesnt have all the DLCS like i do.

**Comment by PotatoesForEternity** [comment]
I unistalled all of my mods except mechjeb. When i loaded into the VAB, there was no stuttering, however the moment i placed down a mechjeb hub the stuttering began to happen.

**Comment by tinygrox** [comment]
@PotatoesForEternity  This is likely due to the Localization. But it may be fixed in #1240 .Not really sure, but it's worth a try, put this file in the `GameData/Mechjeb2/plugins/` folder. 
[MechJeb2.zip](https://github.com/MuMech/MechJeb2/files/4319131/MechJeb2.zip)

**Comment by PotatoesForEternity** [comment]
> The log does not have anything that could explain it. Are you sure it only happens when MJ is installed ? And can you give the specs of your PC ?

Yes, the stuttering does not occur no matter how many mods i have installed. The moment MJ is added, the problem occurs.

i have a Ryzen 5 1400 quad core processor ,

16 gb of ram , 

Radeon RX 580 Graphics Card

**Comment by PotatoesForEternity** [comment]
> @PotatoesForEternity This is likely due to the Localization. But it may be fixed in #1240 .Not really sure, but it's worth a try, put this file in the `GameData/Mechjeb2/plugins/` folder.
> [MechJeb2.zip](https://github.com/MuMech/MechJeb2/files/4319131/MechJeb2.zip)

Didnt work :/

**Comment by sarbian** [comment]
Sorry for the silence on my end. I need to run the game in dev mode to have a look at the unity profiler and see what is going on. I ll try to do it over the weekend

**Comment by sarbian** [comment]
The dev build #949 should help. Tell use how it performs for you.
https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/949/artifact/MechJeb2-2.9.2.0-949.zip
