### ISSUE TITLE
Aircraft Autopilot Missing Translation

### ISSUE THREAD

**Issue by pmckeen** [MuMech/MechJeb2#1247]
- Minor Issue -
## MechJeb Version
2.9.1.0

## KSP Version
1.9.1

## Description
One of the buttons in the Aircraft Autopilot window is missing its English translation (I assume). The visible portion is "...craf..." when it likely should be "Set".

## Replication Case
As soon as the "Aircraft Autopilot" window is available, the problem is visible on the "Speed Hold" toggle.
![image](https://user-images.githubusercontent.com/4690779/75898576-1ccd3980-5def-11ea-840e-4a6c4f7ea910.png)

## KSP.log
https://pastebin.com/Hyvu59ea

**Comment by sarbian** [comment]
This is fixed in 1.9.2 which has been out for a a couple of weeks.
