### ISSUE TITLE
[Bug] When objects are close to each other in orbit, Maneuver Planner doesn't work

### ISSUE THREAD

**Issue by Monniasza** [MuMech/MechJeb2#1248]
## MechJeb Version
2.9.2.0

## KSP Version
1.8.1

## Description
Attempting to create any approach maneuver using Maneuver Planner of two similar orbits with different sizes creates error  

## Replication Case

* Put two objects very close (up to 100 km)  on the two orbits varying in Pe and AP by about 10km
* Set other object from first one as target.
* Open Maneuver Planner
* Try to create any maneuver which involves target.

## Mods required
HyperEdit
MechJeb 2

## KSP.log
[KSP.log](https://github.com/MuMech/MechJeb2/files/4325754/KSP.log)

**Comment by lamont-granquist** [comment]
What specifically are you trying to do?  Hohmann transfer from identically hyperedited orbits which only differ in true anomaly (for example) is nonsensical, you need to use the phasing orbit functionality to adjust the orbit.  Similarly move closer won't work either.  Any single impulse you attempt to do to intercept closer will necessarily involve changing the orbit and moving away.

**Comment by Monniasza** [comment]
I use **two-impulse** Hohmann transfer on two **slightly different** orbits, where science collector's orbit is bigger and slower.

**Comment by lamont-granquist** [comment]
so exactly what are the keplerian elements of the target and destination orbit?
