### ISSUE TITLE
Multi stages confuses landing auto pilot

### ISSUE THREAD

**Issue by chriscamacho** [MuMech/MechJeb2#125]
This is most noticeable when Mun landing - (no atmos)

I'm assuming its the multiple stages that's the fault!

Assuming you have a stage that got you to the Mun with a little fuel left, and that the last (capsule) stage engines are a lot less powerful...

It looks like MechJeb is assuming the engine has the same power (after separation) as the previous stage - resulting in sufficient contact velocity to spoil any Kerbals day...

**Comment by lamont-granquist** [comment]
rolling this up in #1052
