### ISSUE TITLE
MechJeb does not allow me to open my map.

### ISSUE THREAD

**Issue by RyanNovakovic** [MuMech/MechJeb2#1250]
## MechJeb Version
 v2.9.1.0 

## KSP Version
 v1.8.1 

## Description
 Mechjeb does not allow me to open the map. I uninstalled mechjeb and tried to open the map on my main save and it worked. But when I installed it again it wouldn't allow me to open the map on my main save. I created a new save and it allowed me to open the map with mechjeb installed. So something might be wrong with my save and mechjeb. Is there like a cache or something that I can clear for mechjeb?

## Replication Case

I have no idea how to replicate this. It just randomly happened. One minute it allowed me to open the map and I exited the game and the next time I loaded it it wouldn't let me open it. 

## KSP.log
 https://gist.github.com/RyanNovakovic/607c2362cfb4b0197ed8a2e559c1c8ec

**Comment by lamont-granquist** [comment]
You probably need v2.9.2 and it looks like bugs in that version may be getting into a fight with KerbalKonstructs and/or BDArmory.

Mod-mod conflicts was a known issue.

**Comment by RyanNovakovic** [comment]
> You probably need v2.9.2 and it looks like bugs in that version may be getting into a fight with KerbalKonstructs and/or BDArmory.
> 
> Mod-mod conflicts was a known issue.

Where can I find v2.9.2 because its not on curse forge. Only 2.9.1 is.

**Comment by lamont-granquist** [comment]
https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/939/

**Comment by RyanNovakovic** [comment]
I installed v2.9.2 and uninstalled KerbalKonstructs and BDArmory and its still not working.

KSP.log: https://gist.github.com/RyanNovakovic/f3e100459e73ba3fd27f05fd49349c6c

**Comment by lamont-granquist** [comment]
There's tons of these kinds of errors in your logs:

```
[LOG 17:28:53.122] PartLoader: Part 'AirplanePlus/Parts/Aero/smallwings/wing6/smallwingConnector5' has no database record. Creating.
[LOG 17:28:53.124] DragCubeSystem: Creating drag cubes for part 'smallwingConnector5'
[LOG 17:28:53.145] PartLoader: Compiling Part 'AirplanePlus/Parts/Aero/smallwings/wingtip/smallwingConnectortip'
[ERR 17:28:53.148] Cannot find a PartModule of typename 'FMRS_PM'
```

A lot of this:

```

[LOG 17:31:40.451] PartLoader: Compiling Internal Prop 'ASET/ASET_Props/Control/Push_Button_Modular/MECHJEB/pb_MJ_HOHMANN_TRNSF-F03G-B2/pb_MJ_HOHMANN_TRNSF-F03G-B2'
[ERR 17:31:40.453] Cannot find an InternalModule of typename 'JSIActionGroupSwitch'

[ERR 17:31:40.453] Cannot find an InternalModule of typename 'JSIActionGroupSwitch'

[ERR 17:31:40.453] Cannot find an InternalModule of typename 'JSICallbackAnimator'

[ERR 17:31:40.453] Cannot find an InternalModule of typename 'JSILabel'

[ERR 17:31:40.453] Cannot find an InternalModule of typename 'JSILabel'

[ERR 17:31:40.453] Cannot find an InternalModule of typename 'JSICallbackAnimator'
```

and alot of this:

```
[EXC 17:33:16.349] KeyNotFoundException: The given key was not present in the dictionary.
	System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	MapViewFiltering.CountVessels () (at <9d71e4043e394d78a6cf9193ad011698>:0)
	MapViewFiltering.RefreshCounts () (at <9d71e4043e394d78a6cf9193ad011698>:0)
	MapViewFiltering+<RefreshInOneFrame>d__18.MoveNext () (at <9d71e4043e394d78a6cf9193ad011698>:0)
	UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <5aeafee3fea24f37abd1315553f2cfa6>:0)
[EXC 17:33:16.351] KeyNotFoundException: The given key was not present in the dictionary.
	System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	MapViewFiltering.CountVessels () (at <9d71e4043e394d78a6cf9193ad011698>:0)
	MapViewFiltering.RefreshCounts () (at <9d71e4043e394d78a6cf9193ad011698>:0)
	MapViewFiltering+<RefreshInOneFrame>d__18.MoveNext () (at <9d71e4043e394d78a6cf9193ad011698>:0)
	UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <5aeafee3fea24f37abd1315553f2cfa6>:0)
```

Based on the middle one I'm suspicious of an interaction with ASET Props and maybe @MOARdV knows what is going on?

Wonder if localization of MJ busted something somehow...

**Comment by MOARdV** [comment]
> Based on the middle one I'm suspicious of an interaction with ASET Props and maybe @MOARdV knows what is going on?

There's no RasterPropMonitor DLL.  Skimming through the log, I see the folders, but the DLL is not listed in the DLL list at the beginning of the log.  FWIW, I routinely play KSP that way, since I stopped working on RPM a few years ago (and I've uninstalled it), but I still have ASET props for MAS development.

**Comment by RyanNovakovic** [comment]
I removed RasterPropMoniter and ASET props and its still not working in my save. I think Im just going to have to start a new save because everything works fine in a new save but not in my main save.
