### ISSUE TITLE
incompatible mods detected: mechjeb2

### ISSUE THREAD

**Issue by vsarrg** [MuMech/MechJeb2#1254]
## MechJeb Version 
 MechJeb2-2.9.1.0.

## KSP Version
 1.9.12788

## Description
 Hi there, i am new, I have installed Twitch and through this ive got MechJeb2-2.9.1.0. 
Every time i launch the game i got this message: incompatible mods detected

This mods are incompatible with ksp 1.9.1.2788

**Comment by lamont-granquist** [comment]
That is correct you need to find a 2.9.2.0 version.  The latest one here will work:  https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/
