### ISSUE TITLE
Known issue with ascent navball guidance not showing up?

### ISSUE THREAD

**Issue by MuadDev** [MuMech/MechJeb2#1257]
Is there a known issue with the navball guidance target not showing up? I see it showing up in some youtube videos about mechjeb but not if I try it out myself.

![image](https://user-images.githubusercontent.com/29200372/79333840-7e6ce180-7f1f-11ea-99f7-9a6b1649076c.png)
If I set it on auto pilot do it everything works as expected.

**Comment by lamont-granquist** [comment]
Autopilot has to be running for it to show up.  The calculations do not run in the background if it isn't engaged.
