### ISSUE TITLE
Strange label strings in linux

### ISSUE THREAD

**Issue by jeffclay** [MuMech/MechJeb2#1258]
## MechJeb Version
2.9.2.0

## KSP Version
1.9

## Description
Labels look wrong

This is running on Fedora 31 Linux

![Screenshot from 2020-04-17 02-43-05](https://user-images.githubusercontent.com/1380084/79546826-add33980-8058-11ea-8c0e-4dbe1297b324.png)

**Comment by lamont-granquist** [comment]
Looks like you haven't installed it correctly and don't have GameData/MechJeb2/Localization/en_us.cfg, if you're trying to upgrade from prior versions just by overwriting the dll you would see this behavior.
