### ISSUE TITLE
Ascent guidance window manages some parameter globally

### ISSUE THREAD

**Issue by ns88ns** [MuMech/MechJeb2#1263]
## MechJeb Version
2.9.2.0

## KSP Version
1.9.1

## Description
Ascent guidance window manages following parameters globally:

**Prevent engine overheats
Limit Q to
Limit acceleration to
Limit throttle to
Keep limited throttle over
Electric limit**

## Replication Case
- Prepare a Mechjeb managed rocket and put it on launch site
- Being at launch site, before rocket lauch, open window Mechjeb - Utilites. Check for sure that all parameners are unchecked there. Don't close the window.
- Open Ascent guidance window. Change the parameters above there. See as these parameters are changed in the Utilites window.

Now you can see as these parameters are appliend on rockets engines even when ascent guidance autopilot is disengaged. By logic - these parameters should be configured separatedly: one global set and one set for ascent autopilot, shouldn't they? And the parameters configured for ascent autopilot must not be applied when the autopilot is disengaged.

At the same time some other parameter in Ascent gudance window are managed locally and don't affect the same parameters in Utilites window (it is as expected):

**Autostage
Autodeploy solar panels
Autodeploy antennas**

So, it can be a bug. Could you, please, re-check?

## KSP.log
No logs attached because no exceptions there.

_Thank you for your efforts and this amazing mod._

**Comment by lamont-granquist** [comment]
closing as a dup of #706
