### ISSUE TITLE
KSP doesnt load.

### ISSUE THREAD

**Issue by dsfddsfds** [MuMech/MechJeb2#1275]
Hello there! SO I'm having a issue on 1.8.1 where when loading, it doesnt happen with any other mod, it shows this: 
![image](https://user-images.githubusercontent.com/33441944/82583583-71f82c00-9b50-11ea-89c0-793262d0fb85.png) And after i disable all the dlc's, I see this:
![image](https://user-images.githubusercontent.com/33441944/82584297-8983e480-9b51-11ea-8db5-bfb2d744f012.png)
Can someone help me?

**Comment by Supercreeper1935** [comment]
I have this same issue too, i have downloaded mechjeb in the past and had a computer reset recently and when i tried to download it, i had some issues and fixed those. i thought the download was going smoothly until it got stuck on "Loading Expansions...".

**Comment by lamont-granquist** [comment]
Probably a dup of #1188, even if the conflicting mod isn't Firesplitter.

Make sure you are using the latest dev release of MJ:  https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/

And then ensure that you have all your other mods correct with KSP 1.8 versions of the mods.  MJ does trigger crashes in other mods when they are not 1.8 compatible and loaded alongside MJ.

**Comment by dsfddsfds** [comment]
Yet even after installing the latest build, it still shows this: 
![image](https://user-images.githubusercontent.com/33441944/82692584-35decd00-9c1d-11ea-9b5f-15a99acd3050.png)

**Comment by dsfddsfds** [comment]
All mods I have are compitible with 1.8.x and have never had a issue. Also, without that bluedog, it still shows this.

**Comment by lamont-granquist** [comment]
Try removing every mod.  Also post a link to the entire KSP.log

**Comment by dsfddsfds** [comment]
Hello! The log is a bit big. SO I had to upload it to Mega. Here you go! https://mega.nz/file/SxYCkIDL#i-DfqsOXzGpebpXPxMhZmIJxXVzDjj9QHaIM6fV14Xc

**Comment by lamont-granquist** [comment]
MiniAVC is going insane with timeout errors:

```
[LOG 15:33:05.086] MiniAVC -> System.Net.WebException: The request timed out
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00049] in <376e8c39bbab4f1193a569c8dbe4305c>:0
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <376e8c39bbab4f1193a569c8dbe4305c>:0
  at MiniAVC.Addon.FetchRemoteInfo () [0x0002e] in <946c68c810554a77bc35cab54adcb678>:0
  at MiniAVC.Addon.ProcessRemoteInfo (System.Object state) [0x00045] in <946c68c810554a77bc35cab54adcb678>:0
```

You probably have firewalling issues.

**Comment by lamont-granquist** [comment]
Closing as this doesn't seem to be directly related to MechJeb
