### ISSUE TITLE
MechJeb2 does not load

### ISSUE THREAD

**Issue by Ludwik292** [MuMech/MechJeb2#1280]
im using 1.9 ksp and i was re-instaling my modpack for the game.I installed MechJeb2 via CKAN and it couses the Serenity loading problem.it is one of my main mods pls help

**Comment by WeiGitHub2020** [comment]
> im using 1.9 ksp and i was re-instaling my modpack for the game.I installed MechJeb2 via CKAN and it couses the Serenity loading problem.it is one of my main mods pls help

same I have struggle to install the MechJeb 2 and not appear on the game... anything you have ideas with the problem?

**Comment by 7ranceaddic7** [comment]
First suggestion, remove it via CKAN.
Then, go to the GameData folder and make sure it's gone.  Delete GameData\MechJeb2 folder.
There are no dependencies, so you don't have to worry about that.

Next, just for good measure startup KSP and quit after loading.

Then, reinstall and see what that does.

**Comment by sarbian** [comment]
> 
> 
> > im using 1.9 ksp and i was re-instaling my modpack for the game.I installed MechJeb2 via CKAN and it couses the Serenity loading problem.it is one of my main mods pls help
> 
> same I have struggle to install the MechJeb 2 and not appear on the game... anything you have ideas with the problem?

First create a new issue instead of commenting on one that is closed. Then you need to provide a log if you want us to be able to understand what is wrong.

**Comment by lamont-granquist** [comment]
These have all proven to be some other mod which is incompatible, but which MJ's reflection utilities cause to crash making it look like MJ is responsible when it is not.
