### ISSUE TITLE
Suggestion: 'add to last maneuver' in maneuver planner

### ISSUE THREAD

**Issue by FredMSloniker** [MuMech/MechJeb2#129]
Sometimes I have reason to make two maneuvers in rapid succession--an inclination change followed by a periapsis change, for instance. While I can plot the latter following the former, it's likely the latter will burn in a direction other than the former's burn, wasting some of that delta-V. In addition, the shorter the interval between maneuvers, the less accurate the second burn will be (as the rocket will likely have moved past the second node), while the longer the interval, the more likely I'll waste additional delta V because of not being at the optimal point to make the second burn.

I'd like to see the option to, in addition to 'create a new' and 'change the last', 'add to the last' when plotting a maneuver. It wouldn't be applicable to every maneuver--not everything can be done in a single burn, after all--but it'd at least attempt to keep all other orbital aspects the same while changing the specified aspect.

**Comment by lamont-granquist** [comment]
Fixed in #915!  only took 4 years...
