### ISSUE TITLE
[feature suggestion] Landing auto pilot - landing site slope warning

### ISSUE THREAD

**Issue by chriscamacho** [MuMech/MechJeb2#130]
When picking a landing site on the map it is impossible to tell what the slope of the terrain is like, it would be very useful if when a site is picked you would get an indication of the slope of the landing site.

by checking the ground height at two points near to the site on each ground axis, the two angles of the grounds angle from vertical can be combined to make a single angular distance from vertical... (ok not sure I described that too clearly?)

Can you guess who has just had to do an emergency accent before his craft fell over on a Munar slope? :smile:

**Comment by lamont-granquist** [comment]
closing in favor of #1052 epic
