### ISSUE TITLE
Script Editor not loading scripts

### ISSUE THREAD

**Issue by traisjames** [MuMech/MechJeb2#1300]
#857  MechJeb Version
Dev #978

## KSP Version
1.9.1.2788

## Description
Loading script into script editor does not work until something is first added to the window.

## Replication Case
https://youtu.be/nGhfYvx3CEo

## KSP.log
https://github.com/traisjames/Logfiles/blob/master/KSP.log.zip

**Comment by caver115** [comment]
I can confirm, that the scripting throw a exception for ascending guidance.
But i can find a workaround for this issue, you must simply open (or open/close) "Ascent guidance" dialog.

**Comment by pkerts** [comment]
Thank you for this. This issue still persists in 2.12.0, scripting module won't load scripts until you open the "Ascent guidance" window
