### ISSUE TITLE
KSP Version 1.10 Support

### ISSUE THREAD

**Issue by Mr-Pine** [MuMech/MechJeb2#1309]
Is KSP Version 1.10 Support planned or currently being worked on? KSP shows it as incompatible at the moment.

**Comment by 7ranceaddic7** [comment]
Give it time.  It's only been 3.5days AND it's a holiday in the States.
Many are probably a little preoccupied this weekend.

Large well-developed mods tend to upgrade and support each new version.

As nicely as I can say it, pestering days after a release is not chill.

Play 1.9.1 for another couple weeks.

**Comment by Mr-Pine** [comment]
@7ranceaddic7 OK. I am new to KSP and just wanted to ask for me and other inexperienced players like me if support is planned / what the approximate timeframe for development is.

**Comment by sarbian** [comment]
It is done now and there was a dev build 2 days ago. We do it for free on our spare time...

**Comment by lamont-granquist** [comment]
When you cut this issue you deleted this text:

```
  - DO NOT CUT ISSUES ASKING FOR RELEASES ON NEW VERSIONS OF KSP.  EVER.  (and this applies to any KSP mod
    not just MechJeb).  CKAN SUPPORT WILL HAPPEN, BE PATIENT.  USE THE DEV RELEASE (and if it doesn't work
    yet, be patient).
```
