### ISSUE TITLE
Enabling aircraft autopilot cause an significant drop of altitute

### ISSUE THREAD

**Issue by morphelianus** [MuMech/MechJeb2#1311]
## MechJeb Version
2.10.0.0

## KSP Version
Stock 1.10.0.2917 de-de
Making History 1.10.0
Breaking Ground 1.5.0

## Description
After lift off or while in flight and enabling aircraft autopilot with an altitude hold set higher than the current one the plane neither keep the same height nor increases to the set one. It sometimes even decreases to an even much lower altitude causing crashes as the plane cannot pull out of the dive in time due to the high negative vertical speed. Only after a couple of seconds it starts climbing. This happens with all of my planes and is not dedicated to only one or a specific design.

## Replication Case
In case it is needed I can share some planes via the Steam Workshop.

## KSP.log
What is meant by that? Shall I attach the KSP.log? Please reply in case you need anything else.
[KSP.log](https://github.com/MuMech/MechJeb2/files/4887175/KSP.log)
[KSP_x64.gc.log](https://github.com/MuMech/MechJeb2/files/4887176/KSP_x64.gc.log)

**Comment by lamont-granquist** [comment]
@felixscheffer looks like you've got some bugs coming in now that MJ got released.

**Comment by felixscheffer** [comment]
@morphelianus can you provide a plane so I can reproduce the issue (ideally as zip file)?

**Comment by lamont-granquist** [comment]
(there's also two other related issues as well)

**Comment by felixscheffer** [comment]
@morphelianus 

I have done dozens of takeoffs and had no issues at all.

Can you check that
1. Autopilot is engaged
2. Altitude mode is engaged
3. "Set"-Button for Altitude and V/S is white (not green)

You can also check the PID controller for pitch. There should be no significant difference between the current and the target value.

**Comment by morphelianus** [comment]
[K-5 Pigeon.zip](https://github.com/MuMech/MechJeb2/files/4902643/K-5.Pigeon.zip)
[K-4 Hawk MJ.zip](https://github.com/MuMech/MechJeb2/files/4902644/K-4.Hawk.MJ.zip)

@felixscheffer 
These are just two airplanes to reproduce the mentioned behaviour. While I would consider the K-4 as even Jeb safe the K-5 is might a little bit tricky. Both utilize the following action groups. The important ones for the tests are:

Landing gear:
Gear extending / retracting, gear lights off / on, flaps extend / retract

AG1 (start preparation):
Engine on, gear brake, retract ladder, extend flaps, retract airbrakes

Meanwhile I followed the suggested steps as I usually engage the autopilot. All prerequisits had been fullfiled. I captured a video clip flying my K-5 showing the behaviour but couldn't upload it. Do you have a dropbox account? This time the drop was decent but it is visible.

**Comment by felixscheffer** [comment]
@morphelianus  Can you upload the video to youtube?

**Comment by morphelianus** [comment]
@felixscheffer 
Just did. Please find my link attached.
https://youtu.be/ZW9xlwytxWg

After engaging the autopilot the airplane droped 76 meters. In a real airplane I guess the passengers would freak out. Nothing I realized in my real life flights. But I am not a pilot and can't compare MechJeb with real life autopilots. I hope the video helps. Don't hesitate in case you need more details.

**Comment by morphelianus** [comment]
@felixscheffer 
2nd video showing a drop of 45 meters after engaging the autopilot.
https://youtu.be/A68AWgkF1wM

**Comment by morphelianus** [comment]
@felixscheffer 
And a final 3rd one with different conditions round about the set altitude hold. But each time it end up in a dive of several meter. Especially the last one starting at minute 5 I managed a decent climb but engaging the autopilot caused a drop of roughly 100 meter.
https://youtu.be/2vTjOg7SyuM

**Comment by felixscheffer** [comment]
@morphelianus 
Thank you for the videos. I created a fix that should solve the issue.

**Comment by morphelianus** [comment]
Good job. After several tests I can confirm that the issue is solved.
