### ISSUE TITLE
Aircraft Approach & Autoland does not release flight controls after touch down

### ISSUE THREAD

**Issue by morphelianus** [MuMech/MechJeb2#1313]
MechJeb Version
2.10.0.0

## KSP Version
Stock 1.10.0.2917
Making History 1.10.0
Breaking Grounds 1.5.0

## Description
After a successful touch down Aircraft Approach & Autoland does not release flight controls of the plane. In some cases I like to steer the plane to a parking position close to an hangar. But MechJeb wont let me steer to the right or left as it tries to correct the heading to the one it utilized for approaching the runway. Only disabling manually MechJeb solves this issue but then you have to manually activate it again in case the flight shall continue. Beside of that it would be nice that after a touch down and full stopp MechJeb does not restore the old thrust level used in flight before this module was enabled.

## Replication Case
This happens to all of my planes and is not dedicated to a single design.

## KSP.log
[KSP.log](https://github.com/MuMech/MechJeb2/files/4887387/KSP.log)
[KSP_x64.gc.log](https://github.com/MuMech/MechJeb2/files/4887388/KSP_x64.gc.log)

**Comment by felixscheffer** [comment]
This is a kind of known issue that existed before. I am going to look at it when I have time.

**Comment by morphelianus** [comment]
I can confirm. Issue is solved.
Thx
