### ISSUE TITLE
Landing guidance does not engage 

### ISSUE THREAD

**Issue by poopYeeter** [MuMech/MechJeb2#1315]
## MechJeb Version

2.10.0
## KSP Version

1.10.0.2917
## Description

The landing guidance does not engage and always the spaceship pass-thru the point of the correction burns it time warps all the way thru the beginning point. I also tried the CKAN and it's the same. And in the video below I'm also using CKAN

## Replication Case
https://www.youtube.com/watch?v=OA3ViOUvX4k

## KSP.log
I  cant put the file sorry says it cant support the file how can I put it?

**Comment by poopYeeter** [comment]
Sorry if its not with the best English.

**Comment by sarbian** [comment]
> I cant put the file sorry says it cant support the file how can I put it? 
Upload the file to a file sharing site (such as Dropbox, Pastebin or File2web). We can not do much about bugs without logs

**Comment by poopYeeter** [comment]
https://drive.google.com/file/d/1o4KV_bI7WfCY8RoEWXPIyQpYaGiPfW6r/view?usp=sharing
I think is this

**Comment by sarbian** [comment]
This version may fix the problem : https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/995/
Can you try it and tell us ?

**Comment by poopYeeter** [comment]
Thank you very much I will try now

**Comment by poopYeeter** [comment]
Do I need to delete the module manager?

**Comment by poopYeeter** [comment]
Thank you very much for the mod it's performing perfectly!
