### ISSUE TITLE
Antenna do not Auto Employ when toggled ON

### ISSUE THREAD

**Issue by joannplano2005** [MuMech/MechJeb2#1320]
## MechJeb Version
 V2.9.2

## KSP Version
V1.9.1

## Description
 When auto Deploy Antenna is set True, Antenna do not deploy when the Solar Array deploy

## KSP.log

[Player.log](https://github.com/MuMech/MechJeb2/files/4906076/Player.log)

**Comment by lamont-granquist** [comment]
low effort bug report, no other complaints
