### ISSUE TITLE
Aircraft Approach and Autoland doesn't turn on waypoint

### ISSUE THREAD

**Issue by morphelianus** [MuMech/MechJeb2#1322]
## MechJeb Version
2.10.0.0

## KSP Version
Stock 1.10.0.2917 de-de
Making History 1.10.0
Breaking Ground 1.5.0

## Description
After starting form KSC Runway 27 and reaching a dedicated altitude utilizing the autopilot I engaged autoland for KCS Runway 09. The first turn was fine but at the second one the airplane just kept heading straight ahead instead of turning toward the selected runway.

## Replication Case
I captured a video.
https://youtu.be/NZfUlFS7bAs

## KSP.log
[KSP.log](https://github.com/MuMech/MechJeb2/files/4912275/KSP.log)
[KSP_x64.gc.log](https://github.com/MuMech/MechJeb2/files/4912276/KSP_x64.gc.log)

**Comment by felixscheffer** [comment]
@morphelianus  can you double check that the issue still exists in the latest dev build?

**Comment by morphelianus** [comment]
@felixscheffer Sure. Can I simply download the zip of the dev branch or do I have to do something else?

**Comment by morphelianus** [comment]
I tried CKAN as described to switch to the dev branch. But was not able due to found inconsistencies.
* MechJeb2-dev 2.10.0.0-1001 conflicts with MechJeb2
* MechJeb2-dev 2.10.0.0-1001 conflicts with MechJeb2

**Comment by morphelianus** [comment]
Sure, just installed it. Will do some test this weekend.

**Comment by morphelianus** [comment]
## MechJeb Version (DEV RELEASE)
2.10.0.0-1001

I did some tests and I was unable to reproduce the issue. Nevertheless, I think approaching behaves somehow odd compared to version 2.10.0.0 of MechJeb. As far as I recall the airplanes turned 180° and the airplane flew parallel to the runway intercepting the 1st waypoint of runway 09. Then it should turn heading toward the runway. Overall the flown route looked somehow like a 0. Now, it seems that the waypoint is located somewhere in a straight line of the runway and the route looks like a 8. Compared to the airport at my hometown I would expect a 0 but I don't know if the 8 is intended. As usuall I captured a video. https://youtu.be/r9hsG_9pvps

Beside of that it seems that the landing point has moved toward the center of the runway. Which is fine for the runway of KSC and small airplanes at low landing speed. But for the island runway or airplanes coming in with 80m/s have issues as they could overshot the runway. https://youtu.be/E4EQSC6VtHc

I don't have valid results for the desert runways yet. But it seems that the airplanes are still crashing. I will add a comment to issue #1324 after I did some reliable tests.

**Comment by felixscheffer** [comment]
> ## MechJeb Version (DEV RELEASE)
> 2.10.0.0-1001
> 
> I did some tests and I was unable to reproduce the issue. Nevertheless, I think approaching behaves somehow odd compared to version 2.10.0.0 of MechJeb. As far as I recall the airplanes turned 180° and the airplane flew parallel to the runway intercepting the 1st waypoint of runway 09. Then it should turn heading toward the runway. Overall the flown route looked somehow like a 0. Now, it seems that the waypoint is located somewhere in a straight line of the runway and the route looks like a 8. Compared to the airport at my hometown I would expect a 0 but I don't know if the 8 is intended. As usuall I captured a video. https://youtu.be/r9hsG_9pvps

In real-world it should be a 0-shaped pattern (see https://en.wikipedia.org/wiki/Airfield_traffic_pattern). In Mechjeb the aircraft is indeed flying towards a point that is on the extended centerline of the runway. The result is what you described as 8.  Feel free to open a new issue for that.
 
> Beside of that it seems that the landing point has moved toward the center of the runway. Which is fine for the runway of KSC and small airplanes at low landing speed. But for the island runway or airplanes coming in with 80m/s or even greater have issues as they could overshot the runway. https://youtu.be/E4EQSC6VtHc

I am aware of this behavior. There's something in the code called "waiting for flare" that makes the aircraft steer towards the end of the runway. It basically sets the v/s target to 0.8m/s or something like that. At some point, the aircraft is low enough and eventually flares and lands. I already reduced that "waiting for flare" altitude from 10m to 5m to reduce that effect but I admit that it still looks odd. Also, the flare maneuver could be better. Right now, I don't have a good solution for that.
 
> I don't have valid results for the desert runways yet. But it seems that the airplanes are still crashing. I will add a comment to issue #1324 after I did some reliable tests.

**Comment by morphelianus** [comment]
> > Beside of that it seems that the landing point has moved toward the center of the runway. Which is fine for the runway of KSC and small airplanes at low landing speed. But for the island runway or airplanes coming in with 80m/s or even greater have issues as they could overshot the runway. https://youtu.be/E4EQSC6VtHc
> 
> I am aware of this behavior. There's something in the code called "waiting for flare" that makes the aircraft steer towards the end of the runway. It basically sets the v/s target to 0.8m/s or something like that. At some point, the aircraft is low enough and eventually flares and lands. I already reduced that "waiting for flare" altitude from 10m to 5m to reduce that effect but I admit that it still looks odd. Also, the flare maneuver could be better. Right now, I don't have a good solution for that.

This behavior changed with the recent changes, e.g. the landing point for Island runway 09 was right at the beginning of the runway at 70 meters. It even sometimes seemed that the airplane will crash into the hill but it was just fine.

**Comment by morphelianus** [comment]
I guess the issue is solved. I can't reproduce it.

**Comment by morphelianus** [comment]
See my last comment.
