### ISSUE TITLE
Aircraft Approach and Autoland cause airplane crash on Desert Runway 38

### ISSUE THREAD

**Issue by morphelianus** [MuMech/MechJeb2#1324]
## MechJeb Version
2.10.0.0

## KSP Version
Stock 1.10.0.2917 de-de
Making History 1.10.0
Breaking Ground 1.5.0

## Description
I took Desert Runway 18 and engaged the autopilot by setting altitude to 2500 meters and speed to 120 m/s while heading straight north course 000. After reaching 1500 meters I engaged aircraft approach and autoland on Desert Runway 38. But the airplane never reached runway 38 as it crashed following the slope to the next waypoint.

Picking Desert Runway 18 causes an airplane crash too. It seems that the airplane is too high and autolander tries to correct that error by going on a stow flight.

BTW: In contrast to Altitute Hold the checkboxes for Vertical Speed Hold, Heading Hold and Horizontal Speed Hold are still checked after engaging Autoland. Doesn't it make more sence to unckeck these too?

## Replication Case
I captured videos and uploaded it on youtube.
Runway 38: https://youtu.be/NZfUlFS7bAs
Runway 18: https://youtu.be/rQ0gO4jC34w

## KSP.log
[KSP.log](https://github.com/MuMech/MechJeb2/files/4915436/KSP.log)
[KSP_x64.gc.log](https://github.com/MuMech/MechJeb2/files/4915437/KSP_x64.gc.log)

**Comment by felixscheffer** [comment]
Thanks for the videos. I'll see what I can do here.

**Comment by Sinomen** [comment]
I've a similar issue, though on KSP runway 27, plane is coming in way too fast, MJ did not use the air brakes to reduce speed during the final approach which it did in earlier versions. Touchdown speed was 140 m/s instead of 60 m/s, breaking on the runway caused the plane to flip and crash. Manual landing with lower speed was fine, breaking 60 m/s on the runway is much easier than 140 m/s.
MJ #1000 on KSP 1.10

**Comment by felixscheffer** [comment]
@Sinomen I would be surprised if MechJeb has ever used speed brakes to decelerate. There is no such code (at least not that I am aware of). If it ever has, it must have been a long time ago.

**Comment by Sinomen** [comment]
Odd... well, I do remember that some versions ago (I usually don't do anything with planes, maybe once every other month), if I did set the touch down speed to say 60 m/s, the actual touch down speed was indeed 60 m/s. And the plane is the same I did use earlier. 
At least it's easy to circumvent this issue but just changing the speed values in time to much lower numbers.

**Comment by morphelianus** [comment]
@Sinomen 
You can use speed brakes indirectly. Assign them to the Gear action group. As MechJeb triggers it to extend and retract the gear it will trigger the speed brakes too. You can see something similar in my video. While I just trigger the first action group which starts the engines, enables gear brakes, retracts ladder, extends flaps and retracts airbrakes and speedbrakes you can do whatever you want, e.g. extend/retract airbrakes and gear.

**Comment by morphelianus** [comment]
## MechJeb Version (DEV RELEASE)
2.10.0.0-1001

@felixscheffer 
I can't comfirm this fix. Issue still occurs.

**Comment by felixscheffer** [comment]
> @felixscheffer
> I can't comfirm this fix. Issue still occurs.

This is strange because my tests were fine. Anyway, I need more information.

**Comment by morphelianus** [comment]
I took Desert runway 18 and after my lift off I engaged the autopilot with Altitude Hold set to 2500 meters, Vertical Speed Hold to 10 m/s, Heading Hold to 0°, Bank Angle to 15° and Horizontal Speed to 80 m/s. After reaching 2200 meters I engaged aircraft approach and autoland for Desert runway 38. I never reached it as my airplane hit the ground roughly 3.6 km south of Desert runway 38.
https://youtu.be/XjeIndjDZ5g

**Comment by morphelianus** [comment]
A test with the same prerequisits but destination was Desert runway 18 and airplane was my K-6 end up in an endless circle above one of the waypoints. https://youtu.be/kR5z7gkHBJY

**Comment by felixscheffer** [comment]
> I took Desert runway 18 and after my lift off I engaged the autopilot with Altitude Hold set to 2500 meters, Vertical Speed Hold to 10 m/s, Heading Hold to 0°, Bank Angle to 15° and Horizontal Speed to 80 m/s. After reaching 2150 meters I engaged aircraft approach and autoland for Desert runway 36. I never reached it as my airplane hit the ground roughly 3.6 km south of Desert runway 36.
> https://youtu.be/XjeIndjDZ5g
> 
My bad. I forgot to mention that 2.5 degrees glideslope is to shallow for Desert runway 36. 3.0 degrees worked for me but it's still very close to the ground.

**Comment by felixscheffer** [comment]
> A test with the same prerequisits but destination was Desert runway 18 and airplane was my K-6 end up in an endless circle above one of the waypoints. https://youtu.be/RiwyKYkf4hY

Looks like the aircraft is circling around the initial approach point. It should work if you use more bank angle or if you wait until the aircraft is further away from the runway before engaging autoland.

**Comment by morphelianus** [comment]
> > I took Desert runway 18 and after my lift off I engaged the autopilot with Altitude Hold set to 2500 meters, Vertical Speed Hold to 10 m/s, Heading Hold to 0°, Bank Angle to 15° and Horizontal Speed to 80 m/s. After reaching 2150 meters I engaged aircraft approach and autoland for Desert runway 36. I never reached it as my airplane hit the ground roughly 3.6 km south of Desert runway 36.
> > https://youtu.be/XjeIndjDZ5g
> 
> My bad. I forgot to mention that 2.5 degrees glideslope is to shallow for Desert runway 36. 3.0 degrees worked for me but it's still very close to the ground.

Sorry, but I still can't confirm the fix. I tested it twice. Once with my K-4 and the other one with my K-5. I only changed the glide slope as you suggested and kept everything else. Even the flight pattern were the nearly equal. With 3.0 degrees both planes touched the hill south of Desert runway 36 and start jumping toward the runway. Normally that ended with an crash a couple of jumps later.
3.5 degrees reviealed something interessting. At the outer most waypoint the target altitude was set to something above 4000 meters. After reaching that altitude and the inner waypoint the target altitude was set to something around 800 meters. But my airplane was not capable to accelerate to the needed -100 m/s vertical speed.
The desert topographic seems to be a pain point.

**Comment by morphelianus** [comment]
> > A test with the same prerequisits but destination was Desert runway 18 and airplane was my K-6 end up in an endless circle above one of the waypoints. https://youtu.be/RiwyKYkf4hY
> 
> Looks like the aircraft is circling around the initial approach point. It should work if you use more bank angle or if you wait until the aircraft is further away from the runway before engaging autoland.

I didn't assume that aircraft approach and autoland still pay attention to the setted values of the autopilot. Is bank angle the only one? May I suggest that aircraft approach and autoland should ignore the autopilot values and use its own instead. Nevertheless, I cannot reproduce the this specific reported issue anymore. Regardless of 15° or 30°. This time the airplane just circuled twice (I guess to reach the correct target altitude) and then it turned toward the runway. Maybe I should have waited a couple of circles and everything would have been fine. Hence I would say circles of death are not an issue.
