### ISSUE TITLE
Landing Guidance not working 

### ISSUE THREAD

**Issue by FreyaWarrior** [MuMech/MechJeb2#1326]
## MechJeb Version
2.10.0.0

## KSP Version

1.10.0.297
1.10.0 Making History
1.5.0 Breaking Ground
[KSP.log](https://github.com/MuMech/MechJeb2/files/4935392/KSP.log)

## Description

Landing guidance has not been working since the latest update. When activating the auto land function it does not even preform the deorbit burn.
## KSP.log

[KSP.log](https://github.com/MuMech/MechJeb2/files/4935394/KSP.log)

**Comment by 7ranceaddic7** [comment]
All those REALLY BIG words and you still failed to understand them.

**Comment by FreyaWarrior** [comment]
Sorry I did not see that at first. However when I went to grab the video capture it was working so I have know idea why it was not working before.
