### ISSUE TITLE
AscentGuidance

### ISSUE THREAD

**Issue by CyannRogue** [MuMech/MechJeb2#1332]
Hi. I have a problem with scaling of the ascent Guidance tab, it is too long im not able to use other functions on it. I cant use the crucial button Engage Autopilot
![image](https://user-images.githubusercontent.com/67227375/88116788-b12b1380-cbb9-11ea-8adc-c8258319551b.png)

**Comment by lamont-granquist** [comment]
you need to use the settings menu to drop the ui scaling down.
