### ISSUE TITLE
[Request] Option to disable physics warp from auto-warp (So the user can manually set it)

### ISSUE THREAD

**Issue by Avera9eJoe** [MuMech/MechJeb2#1337]
Greetings! I have a rather odd request related to physics warp and auto-warp with Ascent Guidance.

Many of my craft fly at 4x time warp and as soon as a craft starts coasting to apoapsis, auto-warp automatically kicks in, lowers the warp rate to 2x. I suspect this is because most vessels fly at 1x warp and thus MechJeb would go to 2x when coasting to save time. However in my case it adds time because I am already using a higher warp rate.

Would it be possible to add a toggle option that disables physics warp from the auto-warp feature? Doing this should prevent all of the physics warp slow-downs.

## MechJeb Version
2.10.0

## KSP Version
1.10

## Description
Add a toggle-able option to disable physics warp from auto-warp

## Replication Case
Video: https://youtu.be/w0UaOA-OStY

Notice how I can warp to space at 10x warp (BetterTimeWarp mod), but as soon as the vessel starts coasting to apoapsis Mechjeb takes control of physical warp and caps it at 2x.

## KSP.log
N/A

EDIT: Funny note, this is Issue number 1337. Nice.

**Comment by lamont-granquist** [comment]
probably not, MJ is descending into endless toggle-hell.  it can't be everything to everyone.

**Comment by Avera9eJoe** [comment]
Did you watch my example video? It's a rather annoying feature




Get Outlook for Android







On Tue, Jul 28, 2020 at 11:50 AM -0700, "Lamont Granquist" <notifications@github.com> wrote:















Closed #1337.
