### ISSUE TITLE
Rover Autopilot - Traction Issue

### ISSUE THREAD

**Issue by mintmii** [MuMech/MechJeb2#1338]
## MechJeb Version
2.10.0.0

## KSP Version
1.10.1

## Description
Rover autopilot, traction percent starts at 100% then drops to 17% and randomly chnages between 87-33% but noramlly sits at 17% tested on Eeloo and Duna with craft that previously were fine on Duna

## Replication Case

Video of Replication 
https://youtu.be/qziEbXWKxXk

## KSP.log
https://www.dropbox.com/sh/od6gww451pokyer/AABKsziqon2cDEnDSGMI-E9ua?dl=0

**Comment by lampeh** [comment]
A minimal change that works for me is to use the wheelbase instead:
https://github.com/lampeh/MechJeb2/commit/3a1cd758826e6ee92481dbeed764dea3238c6658

I have tested this only with stock rover wheels, not with steerable landing gear or mod parts.

**Comment by sarbian** [comment]
Nice. Can you do a PR ?
