### ISSUE TITLE
Stopped showing mechjeb

### ISSUE THREAD

**Issue by Fargus3222** [MuMech/MechJeb2#1345]
(I am Russian, excuse me for my English :))

The problem is that when entering the game, the new version of the mod is no longer displayed. The module detail is there, but the setup menu is not. Tried both release and beta. Does not help. The old one was displayed well and without bugs.

Help me please.

**Comment by sarbian** [comment]
You need to share your KSP.log so we can see what is wrong with your install. You can find it in the directory where the game is installed.

**Comment by Fargus3222** [comment]
> Вам нужно поделиться своим KSP.log, чтобы мы могли увидеть, что не так с вашей установкой. Вы можете найти его в каталоге, в котором установлена ​​игра.

[KSP.log](https://github.com/MuMech/MechJeb2/files/5026598/KSP.log)

If that's not it, then I'm sorry. I'm a little stupid in the morning :)

**Comment by lamont-granquist** [comment]
[ERR 15:39:23.865] MechJeb caught a ReflectionTypeLoadException. Those DLL are not built for this KSP version:
[ERR 15:39:23.865] Kopernicus.Components 1.0.0.0 GameData\Kopernicus\Plugins\Kopernicus.Components.dll

update the rest of your KSP mods for the correct KSP version
