### ISSUE TITLE
"Return from a moon" maneuver periapsis is very incorrect

### ISSUE THREAD

**Issue by Rogach** [MuMech/MechJeb2#1348]
When I select "return from a moon" in Maneuver Planner and set approximate final periapsis to for example 50km resulting periapsis is incorrect. For example, here's an image of me trying to return from the Mun to Kerbin. Observe how Kerbin periapsis is not even shown because it's underground instead of at 50km:

![20200807173115_1](https://user-images.githubusercontent.com/898831/89656928-f8611600-d8d4-11ea-896f-c79b7776b2a9.jpg)

Steps to reproduce:

1. Start new sandbox game.
2. Create a new craft in the VAB - I used FL-T400 fuel tank with LV-T30 Reliant engine, with MechJeb AR202 case attached to the side.
3. Launch, use Alt-f12 Cheats Set Orbit to set orbit to the Mun, semi-major axis 460000, eccentricity 0.0001, all other parameters to 0. (eccentricity can also be set to zero, I just don't like wobbling periapsis and apoapsis in map view)
4. Open Maneuver Planner, select "return from a moon" in Maneuver Planner, set approximate final periapsis to 50km, press create node.
5. Look at Kerbin and notice that trajectory intersects the ground.

Mods installed (if some interference from other mods is suspected I can try uninstalling them):
MechJeb 2 (MechJeb2 2.10.0.0)
BonVoyage (BonVoyage 1:1.0.1.1)
Community Category Kit (CommunityCategoryKit 5.1.0.0)
Community Resource Pack (CommunityResourcePack 1.3.0.0)
Docking Port Alignment Indicator (DockingPortAlignmentIndicator 6.9.1)
Kerbal Alarm Clock (KerbalAlarmClock v3.13.0.0)
Kerbal Attachment System (KAS 1.7)
Kerbal Inventory System (KIS 1.26)
Kerbal Planetary Base Systems (KerbalPlanetaryBaseSystems v1.6.12)
Module Manager (ModuleManager 4.1.4)
Precise Maneuver (PreciseManeuver 2:2.4.4)
scatterer (Scatterer 3:v0.0621b)
Scatterer Default Config (Scatterer-config 3:v0.0621b)
Scatterer Sunflare (Scatterer-sunflare 3:v0.0621b)

**Comment by Rogach** [comment]
Forgot to include KSP version:
1.10.1.2939 (LinuxPlayer) en-us
1.10.1 Making History
1.5.1 Breaking Ground

**Comment by lamont-granquist** [comment]
This is as good as MechJeb can do right now given the way that the optimizer in this problem is written.

For this maneuver along with fine-tune-closest-approach and other maneuvers, the result won't be done with precision and you're expected to have to tweak the burn vector manually to get what you want.

Fixing this right would take months of effort with graduate-level math, which I don't see happening before KSP 2 gets released (even if KSP 2 turns into Fallout 4 or HL3).  This is likely just the way MJ will work.
