### ISSUE TITLE
Aircraft Autopilot allows to set negative Vertical Speed values

### ISSUE THREAD

**Issue by morphelianus** [MuMech/MechJeb2#1349]
## MechJeb Version (DEV RELEASE)
2.10.0.0-1001

## KSP Version
Stock 1.10.1.2939 de-de
Making History 1.10.1
Breaking Ground 1.5.1

## Description
Aircraft autopilot allows to set Vertical Speed Hold to negative values. Same for VS +/- in case Altitude Hold is enabled. Setting a negative value causes the airplane to decrease altitude even if Altitude Hold is set to a much higher height. Regardless of that I always question the reason why it should be possible to set negative values. Doesn't the label already indicate that the entered values counts for ascent and descent? Shouldn't it be just allowed to enter positive values? At least I would expect that and that would be my suggestion.

## Replication Case
n/a

## KSP.log
[KSP.log](https://github.com/MuMech/MechJeb2/files/5010286/KSP.log)

**Comment by zerg960** [comment]
if the plane starts out at 20,000m and needs to descend to 10,000m, a negative vertical speed hold would be.. useful.

**Comment by morphelianus** [comment]
> if the plane starts out at 20,000m and needs to descend to 10,000m, a negative vertical speed hold would be.. useful.

Not if the negative value causes the airplane to ascent. It can be compared to absolute values. Hence the values represent positive and negative values and a Vertical Speed of 10 m/s means that the airplane is allowed to ascent or to descent by 10 m/s.

That is at least my understanding and how I would utilize an autopilot.

**Comment by morphelianus** [comment]
Hi, after a couple of month I start playing KSP again and have to report that the issue is not solved as expected. While my suggestion was to not allow negative values whenever Altitude Hold is enabled now negative values cannot be entered at all. In cases Altitude Hold is not enabled zerg960 is right and negative values should be possible to decent. Hence, you should check whether the Altitude Hold checkbox is check and decide on this value if negative values are allowed or not.
