### ISSUE TITLE
Autopilot Rendezvous not working very well

### ISSUE THREAD

**Issue by derpyjul45** [MuMech/MechJeb2#1353]
I think one of the issues is with my spacecraft design very wobbly with rcs). But even when I get it stable, MechJeb wants to accelerate too early sometimes and change its heading right before executing certain burns

**Comment by derpyjul45** [comment]
It also might be I have no idea how to use it correctly, but I have had 3 successful attempts out of 4 so far. Sometimes it is really easy, other times it completely wastes my fuel without getting anywhere close

**Comment by lamont-granquist** [comment]
Supporting wobble rockets is going to be nearly impossible.  You should use KJR or autostrut everything to its grandparent part (EEX makes this easy).  The vessel flexes which means that MJ has to react, which makes the vessel flex, etc.   The only good solution is to make it less flexible.
