### ISSUE TITLE
Maneuver Node planner executing too late. 

### ISSUE THREAD

**Issue by kspbeginner** [MuMech/MechJeb2#1354]
running 1.10.1. Whenever I plan a maneuver node and have Mechjeb execute it, The burn is executed 20+ seconds too late, affecting the final trajectory. The late burn time is dependent on the length of the required burn.

**Comment by lamont-granquist** [comment]
The node executor has code which does this.  You need to include more information about how you're determining it is too late, what the burn looked like, what the expected and actual final conditions were, the delta V stats of your vehicle, if there was anything usual about the vehicle, etc.

**Comment by felixscheffer** [comment]
@kspbeginner have you tried the latest dev build?

**Comment by lamont-granquist** [comment]
closing due to no response and not enough details
