### ISSUE TITLE
How change language?

### ISSUE THREAD

**Issue by ev-kov** [MuMech/MechJeb2#1358]
Yes i live in country when many people speak russian, but it extremely uncomfortable navigate with new transkate.
Fisrt - menu item change they position in they list.
Second - meny term sound & write difference between ang & ru.
Third - i looking for instruction how switch the language, tried to search some in code but....
Please add this in settings or instruction.

**Comment by ev-kov** [comment]
Then, i deleted all localization files except "en" variable. 
All is working now.
But i think it will bу good if u add the possibility to choise lang.
How ever thank u kingly for MechJeb.

**Comment by sarbian** [comment]
It is not possible to add a setting. If you want MJ in English you need to delete the Ru localization or switch KSP to English.
