### ISSUE TITLE
Advanced transfer to another planner suggesting large radial burns

### ISSUE THREAD

**Issue by Mattias-reimark** [MuMech/MechJeb2#1363]
When creating the maneuver node for advanced trafer the "optimized" maneuver always contain a large radial burn. This will often result the maneuver dipping into the atmosphere or full on crashing into the planet I would be departing from.

I've had this issue since updating to ksp 1.10.0. I've done clean installs of ksp and mechjeb and the problem still persists.

[KSP.log](https://github.com/MuMech/MechJeb2/files/5147199/KSP.log)

**Comment by lamont-granquist** [comment]
You need to use larger parking orbits or higher thrust engines.  This is not a bugfix, adding path constraints to the optimizer would graduate-degree-in-physics level of hard to implement.

**Comment by Mattias-reimark** [comment]
Still does not explain why this problem didn't happen before ksp 1.10.0? Ive used MJ for years, this issue never happened before.

**Comment by Mattias-reimark** [comment]
Its not that the burn is so long that it dips into the atmosphere, it accually does a radial in burn
