### ISSUE TITLE
Button "MechJeb Vessel Info" now also shows Question Mark (in Toolbar Plugin)

### ISSUE THREAD

**Issue by Gordon-Dry** [MuMech/MechJeb2#1373]
The icon file
GameData\MechJeb2\Icons\Vessel_Info.png
is not shown anymore for some reason.

Now I got a total of 6 buttons with question marks, the others have been like that for years because there is no icon .png file for them, but this new case is weird as there is an icon .png file for it.

I only can assume that the file reference in the code became wrong.

**Comment by lamont-granquist** [comment]
fixed by #1405
