### ISSUE TITLE
MechJeb Causing ReflectionTypeLoadException in 1.10x

### ISSUE THREAD

**Issue by Vortex295** [MuMech/MechJeb2#1375]
I can load as many other mods into KSP 1.1x and encounter no issues, but the moment I add Mechjeb i get a reflectiontyploadexception, and the game refuses to load to main menu. I have tried loading with no other mods except Mechjeb, to the same result. I have also tried older versions of both Mechjeb and Kerbal Space Program, also with the same result every time. I was wondering if this is a common issue, and if there are any know workarounds. Not that the game is unplayable without it, but the convenience of not having to manually calculate planetary transfers in invaluable

**Comment by sarbian** [comment]
You need to provide a log. You are not the first to report this and each time the problem was actually in an other mod but MJ code made it more obvious.

**Comment by Vortex295** [comment]
I will share a log tonight, I'm away from my computer at the moment

**Comment by Vortex295** [comment]
[KSP.log](https://github.com/MuMech/MechJeb2/files/5294984/KSP.log)


There you go
sorry for the delay. I found a couple .dlls that were broken, but in the console it just says "list of broken dlls:" and then there isnt a line after that

**Comment by sarbian** [comment]
The GroundConstruction.dll in NearFutureElectrical is breaking something.

**Comment by Gordon-Dry** [comment]
^that dll does not belong there.

**Comment by Vortex295** [comment]
thank you a whole lot. looks like the ScanSat mod was causing interference too
