### ISSUE TITLE
ksp will not load with mechjeb

### ISSUE THREAD

**Issue by clv57** [MuMech/MechJeb2#1388]
every time i try to load up ksp it starts up but will not finish loading the files. i have checked and both the mod and the game are up to date.
@
[cloud_log.txt](https://github.com/MuMech/MechJeb2/files/5535327/cloud_log.txt)

**Comment by sarbian** [comment]
The log you shared is not a KSP log. We need the one in
C:\Users\<username>\AppData\LocalLow\Squad\Kerbal Space Program\

**Comment by clv57** [comment]
i dont have an app data folder i am using it on steam, is this the one
[KSP.log](https://github.com/MuMech/MechJeb2/files/5541977/KSP.log)

**Comment by sarbian** [comment]
The Module Manager (ModuleManager.2.6.21.dll) version that you have installed is really really old.
You should replace it with the current version : https://ksp.sarbian.com/jenkins/job/ModuleManager/lastSuccessfulBuild/artifact/ModuleManager.4.1.4.dll
It should fix all your troubles.

**Comment by clv57** [comment]
thanks so much
