### ISSUE TITLE
Ascent Guidance Target

### ISSUE THREAD

**Issue by Aegarain** [MuMech/MechJeb2#1389]
When Ascent Guidance is on, the guidance target on the navball will not show up, regardless of whether or not autopilot is enabled(#1257)

KSP Version: 1.10.1.2939
MechJeb Version: 2.11

![screenshot0](https://user-images.githubusercontent.com/63934486/100180199-81a05680-2e8c-11eb-9e4f-1a543ca15190.png)
![screenshot3](https://user-images.githubusercontent.com/63934486/100180224-8ebd4580-2e8c-11eb-9e7b-a82b9dd865b1.png)

**Comment by lamont-granquist** [comment]
dup of #1295
