### ISSUE TITLE
Problems launching the game

### ISSUE THREAD

**Issue by Krulledull** [MuMech/MechJeb2#1390]
The game gets stuck while i'm launching at it says "veryfying expansion" i only have mechjeb, kerbal engineer, and both of the dlc's.

**Comment by philipsavage** [comment]
Did you ever figure out the problem? I’m having the same one. Everyone I’ve talked to says it works fine for them but no dice for me.

**Comment by lamont-granquist** [comment]
you either have the wrong version of MJ for your KSP version, or you have some other mod installed which has the wrong version for your KSP version (MJ's use of reflection can cause other incorrectly installed mods to fail hard).
