### ISSUE TITLE
[Bug!] Autopilot causing wild pitch oscillations

### ISSUE THREAD

**Issue by Phelidai** [MuMech/MechJeb2#1396]
When flying my craft and engaging the altitude hold module of the autopilot, mechjeb takes to wildly pitching up and down to the point of a stall. It only seems to happen on around 20% of my aircraft, but none of those 20% share any major similiarities that they don't also share with my entire aircraft library.

No idea what could be causing this. I've tried every fix I could find, and none worked. Any help would be appreciated, and I'd be happy to hand over any files you need. Thanks!

**Comment by lampeh** [comment]
You might need to fiddle with the PID controls, depending on the characteristics of your plane. Speed control with slow-reacting engines might increase the problems, too. This test plane exhibited large oscillations until I tuned down the pitch i-parameter.
![pid1](https://user-images.githubusercontent.com/758097/104675935-bab7b300-56e6-11eb-9eef-3ab431a9c163.jpg)

**Comment by Phelidai** [comment]
Ah, thanks! In my case it was lowering the Kp that fixed it. Thanks again.
