### ISSUE TITLE
Toolbar buttons missing

### ISSUE THREAD

**Issue by Machine-Maker** [MuMech/MechJeb2#1403]
Having an issue where buttons are missing from toolbar. Linuxgurugamer said issues with missing buttons should be reported here. As you can see I’ve unlocked delta V, but it’s not an option in the toolbar available buttons. 
![image](https://i.imgur.com/tM7t0Zr.png)

**Comment by Machine-Maker** [comment]
Ok, looking into the code a bit, I think it’s because the Preset windows don’t override the IconName method, so it just returns the default name from DisplayModule.cs

**Comment by sarbian** [comment]
I guess I never implemented it. There may be more to it than overriding IconName. I doubt the button will add/remove themselves when windows are added/removed.
I can not work on it currently so if you want to try to implement it feel free to submit a PR.

**Comment by Machine-Maker** [comment]
Yeah, I can try but idk how successful I'll be. I have literally 0 experience with C#

**Comment by Machine-Maker** [comment]
> There may be more to it than overriding IconName

Also, I do think that's actually it. Because the string returned by IconName (passed through GetCleanName) is used as the buttons ID. So its trying to add a bunch of buttons with the same ID, each one overriding the previous. Will test here shortly, I think I got my environment almost working for dev.
