### ISSUE TITLE
Unmanned parts dissapear on hovering over menu in Editor

### ISSUE THREAD

**Issue by kna27** [MuMech/MechJeb2#1407]
In the editor (either SPH or VAB), if there is only one part in the vessel, if you right-click on the part to see its options, it disappears if you move your mouse cursor onto the options menu. This issue gets resolved if you place another part onto the vessel, or if you place another part onto the vessel and then delete that. The video below explains this better than I can.

Also, if a command pod with crew capacity is placed, deleted, and then an uncrewed part is placed, an icon of the previously placed command pod will go to the cursor.

I have never experienced this bug before, this is a one-time occurrence. After restarting KSP, the issue happened again. After deleting MechJeb and restarting KSP, it was fine.

I am using KSP 1.11.1 with MechJeb 2.10.0.

https://user-images.githubusercontent.com/43799189/109585511-a6cae380-7ad1-11eb-8125-b922bdb015de.mp4

**Comment by lamont-granquist** [comment]
Can't see how this has anything at all to do with MechJeb
