### ISSUE TITLE
KSP problem with Mechjeb2

### ISSUE THREAD

**Issue by Thegamerdu1325** [MuMech/MechJeb2#1416]
Hello I have a problem with the mechjeb2 mod. When i open the game i can't find the Mechjeb2 pannel control. I install the mod with forge and i verify the version of the mod and the game are in the same version. I put the log with this if you have an issue to resolve the problem.
Thank's you
[KSP.log](https://github.com/MuMech/MechJeb2/files/6270314/KSP.log)

**Comment by DKashgamingYT** [comment]
I have the same problem as the person above but I install manually. I put the mechjeb2 mod folder into the gamedata folder, but I cannot see the panel on the left. I used it before. I can also attach a picture if needed.

**Comment by lamont-granquist** [comment]
You don't have ModuleManager installed or you need to use the part.
