### ISSUE TITLE
MechJeb2 not working on version 1.12 

### ISSUE THREAD

**Issue by OmegaDan122** [MuMech/MechJeb2#1475]
Can someone help me with this problem i have been trying to fix it by uninstalling and reinstalling mechjeb but still not working and i have but the mechjeb files into the files you would normally but other mods into for them to work and i have installed other mods and they work perfectly fine but mechjeb not working on 1.12 . I would greatly appreciate if someone can help me on this issue.

Thank you

**Comment by Sueic** [comment]
https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/lastSuccessfulBuild/artifact/MechJeb2-2.12.0.0-1092.zip

**Comment by Sueic** [comment]
Passed Test on My PC

**Comment by deushon** [comment]
It's work, thank you)
