### ISSUE TITLE
Advanced Transfer to Another Planet crashes game

### ISSUE THREAD

**Issue by thebloggingchef** [MuMech/MechJeb2#1478]
Every time I pull up the maneuver planner and try to use the Porkchop Selection to transfer to another planet, when I hit "Create Node," the game freezes and will then crash. This happens time and time again without fail.

**Comment by thebloggingchef** [comment]
Here is the log, I think. I haven't done this before: https://www.dropbox.com/s/3rhv9nq0nuukf3n/Player.log?dl=0

**Comment by sarbian** [comment]
Unfortunately, the log does not help much in this case. It is full of exceptions, but they are in the stock code of KSP and I never saw that specific code crashing like that before. You have a lot of mods and the MJ you are running is not the current Dev which is the only version currently build for KSP 1.12. 

@lamont-granquist if you have more idea here is the relevant section of the log.

`[MechJeb] porkchop scanning found DVminsqr = 1197922.23420864 DVmaxsqr = 96555398073587.5 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1704.44138675799, -1514.17731327211, 3.85529886556834] vpos = [-1221.36810351669, -3099.97793839839, 382.638598834885] r = [-451279.517233709, 508242.593548857, 93.0862713003043] dt = 280.618463648075 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [2175.05315290163, 678.866587021379, -3.64085725956431] vpos = [1421.42773352685, -3036.11566785141, 58.4939237635506] r = [202869.648555782, -649117.696314123, 387.364273690756] dt = 1091.24249091455 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1870.45256314278, -1303.42908298034, 3.86527560167039] vpos = [-1015.09997284401, -3107.57999030613, 748.465921977398] r = [-388440.954500764, 557769.654969321, -42.6238948539852] dt = 245.503644219888 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1759.00956672494, -1450.39301156354, 3.86417909792262] vpos = [-1168.13767042812, -3111.81948027664, 447.158483526876] r = [-432261.364971657, 524521.33997861, 50.6978560820973] dt = 269.637507585984 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-707.626881849019, -2167.4697777054, 3.17077623341205] vpos = [-1385.18662054767, -3051.45375026583, 136.77151598096] r = [-646059.485020545, 210948.048109164, 660.450803890174] dt = 438.336746378321 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [2220.76815024893, -512.074046243464, -2.48761713906393] vpos = [810.455410871809, -3253.22327585861, 62.3296887422299] r = [-152478.570726114, -662611.537839051, 882.78716675604] dt = 933.356652088906 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1412.85676151383, -1789.43831960958, 3.7409416423993] vpos = [-1458.52579472843, -3010.90516353381, 235.728064898528] r = [-533349.512252959, 421267.660770731, 293.074354115465] dt = 333.136735366526 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [278.747956281683, -2262.89272682082, 1.93116874048876] vpos = [-782.607456975761, -3259.91109997439, 95.0793172423715] r = [-674533.099360653, -83196.5681965464, 999.182506329442] dt = 568.990655037891 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1095.66506140213, -1999.50822008247, 3.52535622529201] vpos = [-1636.81305586106, -2922.14274418951, 174.927533874993] r = [-595980.863127991, 326667.606433734, 474.49494083143] dt = 382.955288732967 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1054.09789121039, -2021.73603391632, 3.49169498017061] vpos = [-1609.06872690168, -2937.83667629794, 169.446145736877] r = [-602608.015820324, 314271.170399948, 496.126660255229] dt = 389.120541869196 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1091.35088765326, -2001.86684644729, 3.52191528982085] vpos = [-1633.92310110939, -2923.79538304154, 174.336594731868] r = [-596684.078979312, 325380.999276528, 476.760929353016] dt = 383.598370991986 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1100.71011310252, -1996.73464600264, 3.52936442229526] vpos = [-1640.19588323781, -2920.20290318758, 175.625392684138] r = [-595153.932440967, 328172.183564132, 471.838853174763] dt = 382.202293291395 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1101.24006218546, -1996.44233647746, 3.52978447301747] vpos = [-1640.55136901386, -2919.99871923422, 175.699119917063] r = [-595066.781473851, 328330.229481697, 471.559459181137] dt = 382.123135309001 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1101.29245524522, -1996.41342752173, 3.52982599087549] vpos = [-1640.58651430241, -2919.97852946823, 175.706405861001] r = [-595058.162379444, 328345.854586212, 471.531833051404] dt = 382.115308778098 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1101.32899089657, -1996.39326715749, 3.52985494175595] vpos = [-1640.61105277012, -2919.9644319491, 175.711495180976] r = [-595052.151644097, 328356.750559452, 471.512567882714] dt = 382.10985097657 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1101.2931836001, -1996.4130256242, 3.5298265680332] vpos = [-1640.58700502714, -2919.97824670953, 175.706520994273] r = [-595058.042555234, 328346.071802408, 471.531448994924] dt = 382.115199974874 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1101.2725622269, -1996.42440411787, 3.52981022725686] vpos = [-1640.57318833548, -2919.9861856152, 175.703625329005] r = [-595061.435009531, 328339.921920835, 471.542322447953] dt = 382.118280431658 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1101.26001381784, -1996.43132796268, 3.52980028351517] vpos = [-1640.5647343878, -2919.99104019866, 175.701914962526] r = [-595063.499327334, 328336.179627412, 471.548939049142] dt = 382.120154926342 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1101.28011097798, -1996.42023888841, 3.52981620906663] vpos = [-1640.57827403342, -2919.98326351172, 175.704681996569] r = [-595060.193162323, 328342.17317368, 471.538342076684] dt = 382.117152788062 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1101.26776804429, -1996.42704941966, 3.52980642821288] vpos = [-1640.56995845045, -2919.98804070944, 175.702965846142] r = [-595062.223696123, 328338.492158863, 471.544850358532] dt = 382.118996592521 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1101.27427504666, -1996.42345902608, 3.52981158453928] vpos = [-1640.57434229916, -2919.98552202635, 175.703874221143] r = [-595061.153234034, 328340.432732533, 471.54141929874] dt = 382.118024568316 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1101.27206337947, -1996.42467936925, 3.52980983195696] vpos = [-1640.57285227508, -2919.98637792832, 175.703568324929] r = [-595061.517074673, 328339.773150306, 471.542585484042] dt = 382.118354950141 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1101.2732332272, -1996.42403387665, 3.52981075897498] vpos = [-1640.57364040759, -2919.98592546264, 175.703725929639] r = [-595061.324623529, 328340.122032259, 471.541968637676] dt = 382.118180196736 
[MechJeb] singleImpulseHyperbolicBurn mu = 3531600000000 r0 = [144984.052419189, 664280.312131024, -874.331549870779] v0 = [-2226.8745710889, 485.004947542002, 2.52351463144424] v_inf = [455.183501971737, -805.13449631211, 24.8968108984706] 
[MechJeb] singleImpulseHyperbolicBurn vneg = [-1101.2725622269, -1996.42440411787, 3.52981022725686] vpos = [-1640.57318833548, -2919.9861856152, 175.703625329005] r = [-595061.435009531, 328339.921920835, 471.542322447953] dt = 382.118280431658 
System.NullReferenceException: Object reference not set to an instance of an object
  at PatchedConics._CalculatePatch (Orbit p, Orbit nextPatch, System.Double startEpoch, PatchedConics+SolverParameters pars, CelestialBody targetBody) [0x0015a] in <a5c262f7fe724eb9918d4487db8b635e>:0 
[repeated 12 748 592 times]`

**Comment by lamont-granquist** [comment]
yeah @sarbian i was thinking of pinging you about this.  there's a FIXME here that needs fixing -- again in the patched conic "shooting" code:

https://github.com/MuMech/MechJeb2/blob/dev/MechJeb2/OrbitalManeuverCalculator.cs#L1180-L1215

i'm not sure if i screwed something up when i tried to extract that as its own method out of the Transfer planner code mess.

**Comment by Flyingpig123321** [comment]
i have this issue too when i try to trasfer to duna how do it fix it?

**Comment by sarbian** [comment]
Find the error in the linked code and submit a PR.

**Comment by Flyingpig123321** [comment]
i am new to this how?

**Comment by Flyingpig123321** [comment]
i found that just using "transfer to another planet" instead of "advanced transfer to another planet" works fine

**Comment by thebloggingchef** [comment]
Thanks for looking at it Sarbian!

**Comment by lamont-granquist** [comment]
probably fixed by #1490

definitely all the bugs will be completely different now.
