### ISSUE TITLE
engines turn on and off super fast when trying to use manuver autopilot

### ISSUE THREAD

**Issue by Flyingpig123321** [MuMech/MechJeb2#1483]
with some ships if i try to get it to autopilot a manuver it will work fine until the burn starts and then it just starts turning throttle on and off super fast.

i made sure that the COM was completly balanced and it doesnt wobble or turn when i manually use throttle. it seems like it happens more on big ships. i turned off all the options in Utillity in case they were causing problem and same thing happens

**Comment by thebloggingchef** [comment]
Make sure you have a control point set on your vessel. Select "Control from Here" on the command module or drone core.

**Comment by Flyingpig123321** [comment]
that fixed it thanks!
