### ISSUE TITLE
Possible solution for PVG 1.5 stage rocket support

### ISSUE THREAD

**Issue by h0yer** [MuMech/MechJeb2#1484]
I guess someone might already have come up with this, but...

According to the documentation, MJ's PVG needs to know when exactly to stage the half stage.
So we just need the burn time of the half stage, which usually is a known variable, but no way to tell MJ when to stage. And that number is especially necessary for accurate Dv and TWR calculations, since the missile needs to know where it is.

The GUI could get another input field, "half stage burn time", including an option to enable half stage support, similar to hotstaging and its pre-ignition time.
The current time value could be read from either the mission time, or start to count after launch clamp release.

After this set time has passed, MJ could simply perform one single staging event.

The rocketeer needs to take care that this staging event comes directly after the main engines' staging, probably ignoring launch clamps/umbilicals.
Or one would need to specify which stage# contains the decoupler that separates the half stage.

Atlas go brrr.

**Comment by lamont-granquist** [comment]
I'm not interesting in supporting this, someone else would need to do the UX work
