### ISSUE TITLE
2.12.2.0 Does not save config in KSP 1.10.1

### ISSUE THREAD

**Issue by misiektw** [MuMech/MechJeb2#1486]
After last update configs did not work properly. So I removed PluginData with old configs. 
It worked, but now Mechjeb doesn't generate new config files in PluginData/Mechjeb2, and reverts to default settings after each savegame load....
This in on 1.10.1 with RO/RP-1 under Linux. (It's not filesystem access issue, Mechjeb directory belongs to my user on ext4, it generates empty PluginData/Mechjeb on game start).

**Comment by sarbian** [comment]
Stupid C# not converting the path separator properly... I will fix it tonight.

**Comment by misiektw** [comment]
Build 1098 works again. Thanks Sarbian :)
