### ISSUE TITLE
TWR control to Ascent Guidance.

### ISSUE THREAD

**Issue by vipAavos** [MuMech/MechJeb2#1499]
Hello. 
I have this question: is it possible to add a twr restriction on the time of ascent to orbit? 
For example, I set a limit of 1.8, and from the moment of start until the required apocenter is reached, TWR is maintained at a given level. 
Thanks.

**Comment by vipAavos** [comment]
Ascent Guidance

**Comment by lamont-granquist** [comment]
That's the g-limiter
