### ISSUE TITLE
engineDecelerationSpeed not taken into account at PVG orbit insertions

### ISSUE THREAD

**Issue by Gordon-Dry** [MuMech/MechJeb2#1502]
_Maneuvers, planned and executed by MechJeb, are capacle of throttling down soon enough to avoid an overburn because of the engineDecelerationSpeed._

---

At the end of a PVG ascent - with or without coasting - the burn stops "on point" but ignores the engineDecelerationSpeed which results in an overburn.

At the end the perispasis is nearly perfect, but the apoapsis is way too high.
The amount of error depends of the engineDecelerationSpeed, so the time the engine needs to spool down.

**Comment by lamont-granquist** [comment]
i recommend not using that setting

**Comment by Gordon-Dry** [comment]
Well, some engines just got it.

**Comment by lamont-granquist** [comment]
I am not interested in fixing that.
