### ISSUE TITLE
SpaceX style booster Landing Guidance 

### ISSUE THREAD

**Issue by SkW3rL** [MuMech/MechJeb2#1503]
Apologies if this has been brought up before.  I am playing non-RSS/RO/RP/Scaled KSP version 1.12.2 and was attempting to perform SpaceX style booster return burns with MechJeb version 2.12.3 based on an older video on YouTube (for reference, the version of MechJeb on this video was 2.9.2). I followed the streamers directions to a tee and could not land my rocket back at KSC or on a SpaceX style drone ship; not with any degree of accuracy, at least. The difference I noticed in the video (v2.9.2), as the rocket re-entered the atmosphere, the booster performed a "deceleration burn", but would not perform the same burn in the newer 2.12.3 version. My rocket would continue plummeting towards Kerbin, gaining speeds in excess of 1000m/s and would finally kick on the engines at roughly 300-500m above Kerbin, which would not be enough to stop.  Without the deceleration burn, the rocket would land in the water, or at KSC, 1-3km away from my designated landing zone target. The MechJeb 'Landing Guidance' pop-up showed as "Coasting to deceleration burn", but the burn was never performed, regardless of how fast, or slow, I was going. I went through the GitHub files and found there was a version history and a few changes to the decelerationburn.cs & coursecorrection.cs (obviously other changes were made to other files too, but I didn't feel the other changes affected this instance) between 2.9.2 and 2.12.3, but I am only smart enough to know there was a change, and not what that change actually does or means. I then reverted my downloaded version of MJ to 2.9.2 and the landing guidance worked. Flawlessly! 100% of the time. The rocket would slow down enough, even with atmosphere (I had read in a lot of places MJ couldn't calculate the atmospheric landing guidance very well), landed perfectly, within a few meters or so. So, in short, v2.9.2 landing guidance works perfectly. V2.12.3, not so much (in my case).

So far, 2.9.2 has not given me any problems on my 1.12.2. install, but to be honest, I only used it for the Landing Guidance and nothing else. Maybe you know about this, maybe you don't, but this is what I found. It's a great mod for what I have used it for and look forward to learning its other functions in the future. I really wish I could help further, and would like to learn how to do this, but as of now, this is the best information I can provide. I can provide all logs, if necessary, but didn't feel this was relevant to any issue on my machine. If logs are necessary, please let me know, I will redownload 2.12.3, perform the different scenarios and try to screen capture as well. If this is not the correct or desired format to list an issue, please let me know. I just want to help and would like to assist as much as possible.

If this is a mistake on my part, please let me know, and I will attempt to make this work on the newer version. Thanks!

**Comment by SkW3rL** [comment]
I'm not sure which log you need, so I grabbed them both. Tried it out with the new 2.14.1.0 version to see if it would work but appears to still be the same issue. The landing guidance "deceleration burn" is skipped over and is not slowed down enough to land. 2.9.2 has no issues with this style landing Thanks in advance for your help.

Hopefully these will help.

[Player.log](https://github.com/MuMech/MechJeb2/files/8447241/Player.log)

[KSP.log](https://github.com/MuMech/MechJeb2/files/8447240/KSP.log)
.

**Comment by lamont-granquist** [comment]
MJ doesn't really support this, there's tons of other bugs around landing guidance being buggy.  Most of the code in the landing guidance existed before SpaceX was landing rockets.

**Comment by SkW3rL** [comment]
Gotcha, thanks for looking into this. As I said, it works well in 2.9.2 and that's ok with me. Appreciate your time.
