### ISSUE TITLE
Support for KSP 1.12.3

### ISSUE THREAD

**Issue by darkdhamon** [MuMech/MechJeb2#1513]
CurseForge version of MechJeb is no longer working. I get a warning that the mod is not compatible with the current version of the game. And I can not find the MechJeb components in the Tech Tree. This is with a fresh install of both the game and the mod.

![image](https://user-images.githubusercontent.com/2166510/150659303-f7e6f307-fd1b-4eef-80d6-e81b9af8afd7.png)

**Comment by EnochEnzeLi** [comment]
It still works for ksp 1.12.3 so you should be fine for now

**Comment by Duvillard22** [comment]
Sorry, but they also tell me that Mechjeb does not work in version 1.12.
![Screenshot_25](https://user-images.githubusercontent.com/100075924/154843354-f3013e01-6a3e-4954-a8cf-7dde25eefb00.png)
3

**Comment by hartd01** [comment]
It still works on this version, i think the warning is just a warning. Would be nice to fix, but I'm happy with what i got at the moment.

**Comment by darkdhamon** [comment]
In my case playing in career mode Mechjeb has not been in the research tree
since this message popped up. I have not been playing KSP since the Mod
stopped working. I will attempt to reinstall KSP and this mod after work
today. But unless a new update to Mechjeb is available on curse forge I
doubt I will be playing for longer than it takes to find Mechjeb in the
tech tree.

**Comment by DRVeyl** [comment]
CKAN is probably your friend here.

MJ 2.14.* reports supporting KSP 1.12.3.  This is the latest in the releases page in this GitHub, so you don't need to go to the dev releases section.
