### ISSUE TITLE
CKAN DEV Release 2.14.0.0-1114 compatible for KSP 1.10.0-1.12..99

### ISSUE THREAD

**Issue by kretze** [MuMech/MechJeb2#1527]
CKAN DEV Release 2.14.0.0-1115 compatible for KSP 1.12.0-1.12..99
CKAN DEV Release 2.14.0.0-1114 compatible for KSP 1.10.0-1.12..99

KSP reports that version 2.14.0.0-1114 is not compatible

**Comment by sarbian** [comment]
Ah, 1114  was built before I changed the config but with the code that limit version. I removed it and it should now be fine.
