### ISSUE TITLE
(minor) remove the version warning for ksp 1.8-1.11

### ISSUE THREAD

**Issue by Kerbinator-CN** [MuMech/MechJeb2#1544]
MJ is 100% compatible with 1.8-1.11.
however a warning is popped out during MJ loading.
It does function completely normally in 1.8.1 (as I tested, because of a unfinished yearlong project that forced me to use 1.8.1 temporarily to mission end for a video production)
so it can be best to remove the warning for all >=1.8.1 version (MJ don't have version file. seems that it's hardcoded into DLL?)

**Comment by lamont-granquist** [comment]
You need to get onto 1.12.x, you're trying to export your personal issue onto the rest of the world.  That isn't a fair thing to do for a volunteer open source project.

And if it works fine, you can ignore the warning.
