### ISSUE TITLE
Improve Principia node execution (improve ullage)

### ISSUE THREAD

**Issue by DanielFabian** [MuMech/MechJeb2#1562]
I've noticed that in the presence of ullage, Mechjeb has a tendency to start the principia burn too late in the following sense.

In case we have a stable burn, then the burn is spot on.

In case we are unstable, Mechjeb will very reasonably start the burn with a bit of RCS first to avoid unstable ignition. This does unfortunately lead to delaying the burn by the ullage time and thus we are consistently off by a few seconds.

I'd like to propose front-loading that burn by a bit, e.g. by the lead time and start burning RCS `leadTime` many seconds too early when we are not at stable ignition.

This is just an approximation of course:
- in case the lead time is enough to get to 100% stable ignition, we only wasted a tiny bit of RCS fuel, but got the burn moment exact. The amount of wasted RCS fuel would be `[lead time] - [actually needed ullage burn time]`.
- in case the lead time is not enough to get to 100% stable, we at least delay the burn by the lead time less than today.

If our lead time is approximately the time needed to get to stable ignition (or maybe a tiny bit higher), we'd significantly improve the precision for very little fuel cost.

**Comment by lamont-granquist** [comment]
I think I just fixed this.
