### ISSUE TITLE
Position of the MechJeb window

### ISSUE THREAD

**Issue by KommandantGalileo** [MuMech/MechJeb2#1565]
the window is stuck in the upper left corner
[KSP.log](https://github.com/MuMech/MechJeb2/files/9037785/KSP.log)
r

**Comment by sarbian** [comment]
The current release of MJ is v2.14.1. You are using v2.12.3.0, which is nearly a year old.

**Comment by KommandantGalileo** [comment]
> The current release of MJ is v2.14.1. You are using v2.12.3.0, which is nearly a year old.

right, I'll update to the newest version and see if it fixes it's self
