### ISSUE TITLE
Ascent Guidance doesn't like "gimbalRange = 0" in engine configs

### ISSUE THREAD

**Issue by Gordon-Dry** [MuMech/MechJeb2#1579]
Example:
In RP-1, the ROEngines/PartConfigs/XLR11_Al2Me6 defaults to have
`gimbalRange = 0`
in **ModuleGimbal** and in several entries of **ModuleEngineConfigs** as well, just because there is that _one_ tech upgrade to XLR35-RM-1  which got a
`gimbalRange = 5`

It seems that MechJeb Ascent Guidance assumes that the engine always got gimbaling, no matter which config is used, because it just finds a ModuleGimbal with a defined gimbalRange.

That upper stage is out of control and tumbles around.
Only the "BetterController" even tries to fiddle with pitch and yaw to fix it, the other controllers just don't even try to do anything.

**Comment by lamont-granquist** [comment]
A gimbal with a gimbalrange of zero not being controllable seems like correct behavior and not a bug.

**Comment by Gordon-Dry** [comment]
Of course.
I mean that MJ assumes the stage should be controllable as it is not.

**Comment by Gordon-Dry** [comment]
I added InternalRCS parts and for some reason those have not been used as well - as MJ really "wants" to use the gimballing first.

**Comment by lamont-granquist** [comment]
ascent guidance doesn't work with uncontrollable stages, that isn't really a bug either.  and the attitude controllers don't know anything about where the torque is coming from or have any code in them for targeting particular different torque providers, they just give pitch/yaw/roll commands to KSP which is responsible for figuring that out.
