### ISSUE TITLE
Hotstaging: sometimes it works, sometimes not

### ISSUE THREAD

**Issue by Gordon-Dry** [MuMech/MechJeb2#1581]
Could it be that a low performance PC makes the code lag out and so a result of a subroutine "is late" which makes the main process omit a step and the result is that in some cases a hotstaging is not happening but the 2nd stage's engine already ignites as soon as the launch clamps were released?

In RP-1 that is (by CKAN Express Install).

**Comment by lamont-granquist** [comment]
This isn't a bug report
