### ISSUE TITLE
Ascent autopilot PVG - throttle resets very bad when using in RSS/RO 

### ISSUE THREAD

**Issue by NameTakenWasTaken** [MuMech/MechJeb2#1584]
I'm finding the Prime Vector Guidance pretty much impossible to use and understand currently.
Any time I press engage autopilot it cut's the throttle to zero before then doing what it wants (Max throttle), resulting in single ignition engines dying.
Perhaps I am missing some documentation but I could not find any.
It is also impossible to let the rocket laucnh from standstill by itself since engine spool up times don't allow for autostaging to work correctly.

**Comment by lamont-granquist** [comment]
This isn't a help channel, you need to look on the RSS reddit forum, the RO discord or read the wiki articles:  https://github.com/KSP-RO/RP-0/wiki/TroubleshootingMechJebPVG
