### ISSUE TITLE
Inclined launch with preset LAN

### ISSUE THREAD

**Issue by KSPanier** [MuMech/MechJeb2#159]
Could you please add a feature, that allows us to time inclined launches to meet a set angle of the LAN. This really would help to execute precalculated interplanetary flights.
I imagine it to be a additional window located next to the inclination window, where I can type in the wished location of my AN, but so I can also disable the feature, so my equatorial launches don't have to wait for ages just because KSC is slightly off the equator.
This could also include a new feature for the manouver generator so I can change my inclination relativ to a specific  LAN. Look at KSPTOT for comparison.

**Comment by lamont-granquist** [comment]
closing in favor of #1053
