### ISSUE TITLE
The configuration window appears as a small arrow and can't open it or move

### ISSUE THREAD

**Issue by GeneralGrievous07** [MuMech/MechJeb2#1600]
![imagen_2023-01-24_181916299](https://user-images.githubusercontent.com/123520204/214451291-b8fe674a-4d10-4da1-9229-5f0eaf04ffb5.png)

**Comment by JPSmee** [comment]
I have encountered this issue as well.

**Comment by lux7328** [comment]
If you click on Setting in the Mechjeb menu., for some reason it lets you open all the other windows except for settings and rover auto pilot. I'm trying to find an actual solution

**Comment by tylerbobs** [comment]
I had the issue, but I installed Toolbar Control for another mod and it seems to have fixed the issue
