### ISSUE TITLE
Mech Jeb Menu Malfunction

### ISSUE THREAD

**Issue by lux7328** [MuMech/MechJeb2#1602]
For some reason the mech jeb menu is trapped in the upper left corner of the screen. It can't be moved and none of its windows will open for more than half a second. I scanned through some of the previous issues reported and noticed some other people had the same issues. One Person stated that if you click on the settings window, the mechjeb menu will jump to the opposite side of the screen and can be used properly all except for the settings window and the rover autopilot window. I tried that and it did work as he stated, but it also removed several other windows including all of stats windows such as rendezvous, atmosphere, target, vessel and some other ones as well. There appears to not be any resolution to this through the other reported issues, but I know absolutely nothing about coding. Even if I knew how to open the code, I wouldn't know what to do with it.

@MuMech

@lamont-granquist 

<img width="189" alt="Screenshot 2023-02-09 181828" src="https://user-images.githubusercontent.com/124810519/217960823-f1d482aa-f2a1-4e17-a084-48c2ec93ac7f.png">

**Comment by lux7328** [comment]
I reviewed the KSP log and I believe the conflict is with the mod "editor extensions". There are serveral "MechJeb caught a ReflectionTypeLoadException." stated in the log. I uninstalled editor extensions, and it is working properly now but I would love have both mods installed....

[KSPlog.txt](https://github.com/MuMech/MechJeb2/files/10710071/KSPlog.txt)

**Comment by lamont-granquist** [comment]
```
ERR 12:27:58.047] [AssemblyLoader] Exception when getting assembly attributes: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.

Additional information about this exception:

 System.TypeLoadException: Could not load type of field 'EditorExtensions.AppLauncherButton:button' (0) due to: Could not resolve type with token 01000008 (from typeref, class/assembly ApplicationLauncherButton, Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:ApplicationLauncherButton member:(null) signature:<none>
```

EEX is broken, either the latest version of it doesn't work with 1.12.5 or else your install of it is busted.

That exception is being thrown by KSP's AssemblyLoader, not MechJeb, this has nothing to do with MJ.
