### ISSUE TITLE
Maneuver planner scheduling broken

### ISSUE THREAD

**Issue by asymptoto** [MuMech/MechJeb2#1607]
With the most recent update `2.14.3.0`, some of the maneuver planner scheduled events are not working anymore.
Tested with RP-0, when scheduling an AP change at the DN for a GTO, the node is created ~295 seconds after the DN.
I encountered several similar issues where the node was created at the wrong time, but I did not have time to investigate further.
With a rollback to `2.14.2.0`, the issue went away.

**Comment by luoluo39** [comment]
I have encountered this issue as well.

**Comment by sarbian** [comment]
Can you test with [this version](https://ksp.sarbian.com/jenkins/job/MechJeb2-Release/lastSuccessfulBuild/artifact/MechJeb2-2.14.3.0.zip) ?
