### ISSUE TITLE
A little guidence trying to program autoland for rss

### ISSUE THREAD

**Issue by falcon470** [MuMech/MechJeb2#1608]
So i went into the landingsites,cft, and updated the coordinates for the 3 landing sites around the ksc in my modded install, told it coordinates, earth, only thing i wasnt sure about is when i tried to use real world coordinate calculating websites/tools to calculate distance i got insane numbers compared to the orgional runways, lke 5 k, needless to say for what ever reason they dont show up in game, i called them 1 2 and 3 well ksc runway 1 2 and 3. Is this possible or am i just doing some thing wrong any way if youll help heres the files see what i did wrong coords are from in game alt 12 menu distance calculation was from a site meant to be used on the real earth like irl not game. Heres the file i had to rename its file extension or github didnt like it.
[LandingSites.txt](https://github.com/MuMech/MechJeb2/files/11047235/LandingSites.txt)

**Comment by falcon470** [comment]
Update, mabey it did work i am not sure yet ill test, distance to runway seems to mabey match up ill find out, see if it flys to the right locations

**Comment by falcon470** [comment]
after some testing the runways that do show up ksc runway 09 for example says its 3297833m away

**Comment by arrowmaster** [comment]
See #1563
