### ISSUE TITLE
ArgumentException: OrbitExtensions.GetEccentricAnomalyAtTrueAnomaly

### ISSUE THREAD

**Issue by mihemihe** [MuMech/MechJeb2#1609]
* Using MechJeb2 in combination with a RSS/RO/RP1 Express setup, on  clean 1.12.3.
* Been using this setup for several weeks without issues
* During the past 2 days most of the times I leave the earth SOI and start orbiting the sun I get this exception spammed, to the point the game becomes unresponsive.

This is the issue:

[EXC 16:27:45.409] ArgumentException: OrbitExtensions.GetEccentricAnomalyAtTrueAnomaly: True anomaly of 2.69600474693162 radians is not attained by orbit with eccentricity 2.19997327302083
	MuMech.OrbitExtensions.GetEccentricAnomalyAtTrueAnomaly (Orbit o, System.Double trueAnomaly) (at <24b14848e53c4c4492718006da41870f>:0)
	MuMech.OrbitExtensions.TimeOfTrueAnomaly (Orbit o, System.Double trueAnomaly, System.Double UT) (at <24b14848e53c4c4492718006da41870f>:0)
	MuMech.OrbitExtensions.TimeOfAscendingNodeEquatorial (Orbit o, System.Double UT) (at <24b14848e53c4c4492718006da41870f>:0)
	MuMech.MechJebModuleInfoItems.TimeToEquatorialAscendingNode () (at <24b14848e53c4c4492718006da41870f>:0)
	(wrapper dynamic-method) System.Object.lambda_method(System.Runtime.CompilerServices.Closure,object)
	MuMech.ValueInfoItem+<>c__DisplayClass14_0.<.ctor>b__0 () (at <24b14848e53c4c4492718006da41870f>:0)
	MuMech.ValueInfoItem.UpdateItemCache () (at <24b14848e53c4c4492718006da41870f>:0)
	MuMech.ValueInfoItem.UpdateItem () (at <24b14848e53c4c4492718006da41870f>:0)
	MuMech.MechJebModuleCustomInfoWindow.UpdateWindowItems () (at <24b14848e53c4c4492718006da41870f>:0)
	MuMech.MechJebModuleCustomInfoWindow.WindowGUI (System.Int32 windowID) (at <24b14848e53c4c4492718006da41870f>:0)
	MuMech.DisplayModule.ProfiledWindowGUI (System.Int32 windowID) (at <24b14848e53c4c4492718006da41870f>:0)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (System.Int32 windowID) (at <58f888e0d56a4620958c8e58a768c70d>:0)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.GUI+WindowFunction func, System.Int32 id, System.Int32 instanceID, UnityEngine.GUISkin _skin, System.Int32 forceRect, System.Single width, System.Single height, UnityEngine.GUIStyle style) (at <58f888e0d56a4620958c8e58a768c70d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

Thanks in advance

**Comment by lamont-granquist** [comment]
think this got fixed
