### ISSUE TITLE
"VTOL Mode" for Ascent and Landing Guidance

### ISSUE THREAD

**Issue by Benie76** [MuMech/MechJeb2#164]
First off, I'm new to Github. I'm hoping that this is listed as a feature request, and not a bug.

I'm wondering if it's possible, if "VTOL Mode" can be an option for taking off and landing for people that have Damned Robotics installed, and using the thing that makes them rotate.

It'll make it easy to fly a VTOL-powered craft. If this is possible.

**Comment by lamont-granquist** [comment]
VTOLs should probably use SMARTASS / Translatron and if there's specific bugs in there, those should get addressed with individual bugs against those modules.  Doubt that changing Ascent/Landing guidance to both support Rockets+VTOL is the way to go.
