### ISSUE TITLE
Burn time execution only

### ISSUE THREAD

**Issue by Strikeout11** [MuMech/MechJeb2#1677]
Is there any way to execute precisely the burn time without control of the ship? I am trying to send a lunar impactor on a rp-1 install and the last stage of my ship is unguided, so I point the ship in the right direction and make it spin before launching the probe, but I can't find a way to cut the engine exactly at the right time, when I click "execute node" in the manoeuver planner or editor, it doesn't do it or it doesn't stop when reaching 0.1 ms

**Comment by lamont-granquist** [comment]
No, I'm thinking about how this might get done eventually but right now the maneuver node editor assumes you have control.
