### ISSUE TITLE
Persistent Rotation compatibility

### ISSUE THREAD

**Issue by Vagabond-77** [MuMech/MechJeb2#1685]
DEV builds released after MechJeb2-2.14.3.0 are not compatible with PersistentRotation.
As soon as any vehicle is launched the logs fill up with spam [EXC .....
[Player.log](https://github.com/MuMech/MechJeb2/files/11629701/Player.log)
[KSP.log](https://github.com/MuMech/MechJeb2/files/11629704/KSP.log)

**Comment by lamont-granquist** [comment]
PRs reflection will have to be updated after the dev branch is stable, this isn't a bug in MJ.  Since principia and RO have their own PR-like mechanics and conflict with PR this isn't a priority.
