### ISSUE TITLE
[Suggestion] Auto-adjusting rotation to 360°/orbit

### ISSUE THREAD

**Issue by Rogem** [MuMech/MechJeb2#172]
So, I came into the resolution that making my space station rotate exactly 360° every single orbit around Kerbin was somewhat impossible manually. What I'd like to have in MechJeb is simply an utility to achieve this. Should be a simple button, that I can click in the orbit.

This so, that a space station, a satellite or a probe will always be positioned the same to the planet, making it easier to apply solar panels, etc. knowing that they won't be blocked by other parts of the construct.

Thanks for your time making such a great mod.

**Comment by lamont-granquist** [comment]
PersistentRotation is the mod
