### ISSUE TITLE
Feature request: disable interface while there is no connection

### ISSUE THREAD

**Issue by olegst90** [MuMech/MechJeb2#1733]
I've seen an old discussion on here about disabling MechJeb when there's no signal, and it was closed when RP-1 implemented autopilot shutdown when avionics aren't active. However, if avionics aren't shut down, you still can use and control autopilot even if there is no signal. 

Is it possible to disable autopilot's interface when there is no signal while the autopilot continues to work? Then the user will have to think in advance and, say, use the scripting module (which I absolutely love) and plan the actions beforehand, and be unable to change the program until the signal is regained.

**Comment by lamont-granquist** [comment]
There's no plans to do anything else.
