### ISSUE TITLE
Reduced Thrust Limiter not factored in (RP-1) Separator's Burn Time calculation (both VAB and live)

### ISSUE THREAD

**Issue by Bloodsucker** [MuMech/MechJeb2#1781]
When using the Separator Motor or the Radial Separator Motor (and possibly others) in the VAB on a separate stage, if the engines have their Thrust Limiter reduced (e.g., to 50%), the expected Burn Time isn't recalculated. Instead, it continues to display as 0.8s, which is incorrect. With a Thrust Limiter set to 50%, it should display a value around 2 seconds or something similar. The 0.8s value corresponds to the total burn time when the thrust limiter is at 100%, even though it's not.

I am using RP-1 and I recently updated to Mechjeb2-dev. This issue doesn't appear in version 2.0.0 available in CKAN.

Steps to Reproduce:
1. Add a Separator Motor to your rocket in the VAB.
2. Move the engine to its own stage to view Mechjeb's calculated DeltaV and expected burn time.
3. Set the engine's Thrust Limiter to 50%.
4. The Burn Time still displays as 0.8s, but it should be a value between 1-2 seconds.

**Comment by lamont-granquist** [comment]
thrust limiters were totally broken in everything, even trivially in stock, should be fixed now.
