### ISSUE TITLE
Maneuver execution starts burn too late

### ISSUE THREAD

**Issue by daniilsan347** [MuMech/MechJeb2#1825]
Game version: 1.12.5
MechJeb2 version: 2.14.3.0 installed through CKAN

When you have long burns, the issue is the most noticeable. It seems like burn isn't split 50/50, but about 30/70. It isn't an auto-warp issue or craft rotating too slow. Happens no matter parts I use. Stock, ReStock, Cryo Engines, all have this. 

I've seen people reporting similar issues back in 2014, but I use the latest version, so I am clueless. Is it known for some other mods to cause conflicts?

**Comment by lamont-granquist** [comment]
Long burns have to be done with a finite burn optimizer, not with the janky way the node executor currently interacts with KSP's infinite-impulse maneuver node implementation.  This might get fixed at some point on the dev branch, but #1061 is the relevant issue and that has been open since 2018.

**Comment by lamont-granquist** [comment]
Also 50-50 isn't a rule, you need an optimizer to figure out the accurate split, 50-50 is just a close guess, but the deviation from 50-50 by the current node executor is likely very wrong anyway.

**Comment by daniilsan347** [comment]
Oh, where can I find that finite burn optimizer? Is it part of MechJeb2 or it comes as separate mod?

**Comment by lamont-granquist** [comment]
Uh no, nothing like that exists in the KSP universe, one of the algorithms in the scientific literature needs to get implemented before anyone can use it.

**Comment by daniilsan347** [comment]
Oh, well, bummer. Still, any recommendations what to do with maneuvers execution other than manual? Some kOS script or there is something more user friendly?

**Comment by lamont-granquist** [comment]
The version of the node executor in MJ-dev right now is the best of anything that I'm aware of in KSP

**Comment by daniilsan347** [comment]
I know this issue is closed, but this definitely isn't right behaviour. The burn isn't even that long, under a minute. Either MJ node execution hates LHOX engines from Cryo Engines mod, or I'm missing something.

https://github.com/MuMech/MechJeb2/assets/68712847/b44180d1-0415-42eb-9776-3f11c6ded861
