### ISSUE TITLE
how can i change the runway for landing an aircraft in rss?

### ISSUE THREAD

**Issue by Prof-Zirun** [MuMech/MechJeb2#1847]
how can i change the runway for landing an aircraft in rss? I have tried to change the document called landingsites, but it doesnt work.

**Comment by pietkokosnoot** [comment]
> how can i change the runway for landing an aircraft in rss? I have tried to change the document called landingsites, but it doesnt work.

See: https://www.reddit.com/r/RealSolarSystem/comments/1h0k4xm/comment/lz5pp7z/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
