### ISSUE TITLE
Simple but stupid BUG/problem with PVG RSS

### ISSUE THREAD

**Issue by nablabla** [MuMech/MechJeb2#1848]
Whenever engaging or disengaging or whenever avionics is insufficient and becomes sufficient again, PVG disengages and engages throttle for a second, which causes the engines to go out and not going on again. I don't understand what that would be good for. 
I increased my rocket and it is now some kg over the avionics limit, because I don't want to tool the avionics again and it does not matter if it does not work for the first 3 seconds anyways. But now I can not use ascend guidance.
What would I expect?
when I press "Engage Autopilot" and throttle is already on 100% and it wants to set throttle to 100% that it does not set it to 0% for a second

**Comment by lamont-granquist** [comment]
> I increased my rocket and it is now some kg over the avionics limit, because I don't want to tool the avionics again and it does not matter if it does not work for the first 3 seconds anyways. But now I can not use ascend guidance.

Technically, cheating.  Overbuild the avionics in your boosters for your future payloads or else pay the retooling costs.
