### ISSUE TITLE
[PVG, RO, RSS, Principia] Launch to target LAN doesn't launch the rocket (dev branch)

### ISSUE THREAD

**Issue by mmomtchev** [MuMech/MechJeb2#1855]
On the dev branch with RO, RSS and Principia, when launching to target LAN:

* starts the countdown and displays `Autopilot status: Pre launch`
* about 10 seconds before the launch, the autopilot button disengages, the countdown continues; pressing again the `Engage autopilot` button is blocked (it immediately reverts)
* once the countdown reaches 0, nothing happens, however pressing the `Engage autopilot` button at this point will actually launch the rocket

**Comment by mmomtchev** [comment]
After engaging the autopilot:

![Screenshot 2024-01-14 120459](https://github.com/MuMech/MechJeb2/assets/31410344/5cdd2696-5e2a-4003-9f30-722e7e3ea789)

After pressing `Launch to target LAN`:

![Screenshot 2024-01-14 120536](https://github.com/MuMech/MechJeb2/assets/31410344/93666d70-f5df-4bef-aabe-a53d74f32ff3)

At about 10 seconds left to launch (immediately after the final countdown starts):

![Screenshot 2024-01-14 120556](https://github.com/MuMech/MechJeb2/assets/31410344/a338d5d7-2682-4eac-9ade-ea57324d41a1)

**Comment by lamont-granquist** [comment]
yeah that ones been around for months, i've just been lazy about fixing it...

should be fixed by #1856
