### ISSUE TITLE
(2.14.3.0) Maneuver Planner - Bi-Impulsive (Hohmann) transfer to Mun is planning for Munar impact for some reason.

### ISSUE THREAD

**Issue by ThePhaseMaster** [MuMech/MechJeb2#1858]
- MechJeb 2.14.3.0
Launched Vehicle with Ascent Guidance to 80x79km orbit. Planned Hohmann transfer to Mun. Planner is for some reason making a node that would cause impact with the Munar surface.
- [Mod List - 2024.01.17.txt](https://github.com/MuMech/MechJeb2/files/13970048/Mod.List.-.2024.01.17.txt)

Image showing Orbit around Kerbin.
![image](https://github.com/MuMech/MechJeb2/assets/154425118/4f61c227-a620-42a9-9162-71e8140d558f)
Image showing planned maneuver node causing impact with the surface.
![image](https://github.com/MuMech/MechJeb2/assets/154425118/53770d45-7de0-48ac-bfcf-2e8a81e039d9)

**Comment by maddavo** [comment]
Yep, the planner intercepts the target.  This is good for satellites or stations you want to intercept and dock with.  But for planets or moons you use it to make an intercept and then adjust the node so your periapsis is what you want. Then you can use the circularise function to make another node at the periapsis.

**Comment by lamont-granquist** [comment]
Yeah this is working as intended, not a bug.  The 2-burn planner treats the target as a zero-SOI target (ie more like a ship than a celestial) and tries to hit it exactly.

There's a feature request in here to have a "transfer to a moon/secondary" function which does the modelling of the patched conic SOIs and allows for targeting the inclination, periapsis and other constraints (in addition to one or more midpoint burns or in-SOI burns).  I think that is covered by other issues in the issue tracker, though, and I'm certainly vividly aware of the desire.  The work that I've done on the "return from moon" function in the dev branch is directly applicable to inverting the problem and doing "transfer to a moon".
