### ISSUE TITLE
Error while making node in advanced transfer (Optimizer DV returns NaN) along with other Man. planner issues

### ISSUE THREAD

**Issue by Ijustplaymc** [MuMech/MechJeb2#1874]
Mechjeb dev release 2.14.3.0-1392 from CKAN
KSP 1.12.5, both DLCs

Latest mechjeb dev release has issues with Advanced Planetary Transfer
Creating a node always returns an error, and the console returns
`From optimizer DV = [NaN, NaN, NaN]`
`Exception: FailedCheck: check failed`
![image](https://github.com/MuMech/MechJeb2/assets/98615903/ba415027-9fa9-4fb2-8c79-b2f018571c4f)

Any other maneuver spams the console with
`at MechJebLib.FuelFlowSimulation` errors
![image](https://github.com/MuMech/MechJeb2/assets/98615903/4cb793f3-7c91-4155-bfea-640a44edf4dd)

Similiar issues occure with mechjeb stable, both from ckan. Stable Mechjeb calculates DV poorly in the maneuver indicator, along with same console spam, and it changes with orientation, making it completely useless

Mod List
https://pastebin.com/6P3Z5wBA

KSP.log
https://fastupload.io/gfbHO2Q35QNA/fOn89FOd8oaM44o/ex5z2NVQlzKqk/KSP.log

Appears to happen even on a stock ksp instance with only mechjeb installed

**Comment by Ijustplaymc** [comment]
Appears every issue is not present in mechjeb stable 2.14.2.0 (Second latest in ckan)
il keep this open, but still its odd the older version works perfectly (Even the latest stable is seeminly broken for me)

**Comment by lamont-granquist** [comment]
This issue is a mess of multiple different issue which makes it difficult to see what to do with it.  The adv transfer issues are likely very well known and dups of #1343, #1478, #1533 and related issues.  Another issue doesn't help there, so that part of the issue should just be closed as a dup.

> Stable Mechjeb calculates DV poorly in the maneuver indicator

Not sure what this even means, but the navball information is all generated by stock KSP and MJ doesn't touch it.

The MJLib.FFS spam is interesting, but that is going to be dependent upon the vessel that you've constructed and how FFS is walking it and everything else in this issue is an irrelevant distraction.

**Comment by Ijustplaymc** [comment]
> > Stable Mechjeb calculates DV poorly in the maneuver indicator
> 
> 
> 
> Not sure what this even means, but the navball information is all generated by stock KSP and MJ doesn't touch it.
> 
(on the latest non-dev mechjeb)
The indicator for required DV (the maneuver one next to navball) changes to absurd values depending on the crafts orientation, and if I reset it and regenerate the node it changes the nodes position, causing it to change direction and require 2-4x the estimated DV

This only seems to happen with the adv transfer, normal transfer works good enough for now

This basically makes the adv planetary transfer useless as the maneuver doesn't even go where it says it will, as it just burns in random directions

Happens whenever I manually do the burn or the execute node button

Also it happens even a day before the transfer window, meaning the chance of it being too far away to calculate right shouldn't be the cause

**Comment by lamont-granquist** [comment]
closed by #1881
