### ISSUE TITLE
Cannot find Ascent Guidance/It does not exist

### ISSUE THREAD

**Issue by Useor** [MuMech/MechJeb2#1893]
![Screenshot 2024-06-14 234158](https://github.com/MuMech/MechJeb2/assets/166590906/c236b7d5-c394-4bbf-91de-d66be1f82abf)

**Comment by Ijustplaymc** [comment]
> Some modules are disabled until you unlock the proper node in the R&D tree or upgrade the tracking station
Possibly this is relevant?

**Comment by Useor** [comment]
> > Some modules are disabled until you unlock the proper node in the R&D tree or upgrade the tracking station
> 
> Possibly this is relevant?

I was in sandbox mode
