### ISSUE TITLE
All of the tabs keep moving to the corner of the screen.

### ISSUE THREAD

**Issue by eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee1** [MuMech/MechJeb2#1896]
I don't know if it's because I'm on Mac or what, but all of the tabs stay stuck in the top left corner. Ascent Guidance, Landing Guidance, all of them. Try to move them? Nope, they go right back where they came from. Anyone have any idea what's going on?

**Comment by behrad2k** [comment]
found solution: look for "mechjeb" in logs and if it says anything about incompatible dll's uninstall the mod for the dll

**Comment by YanSv12** [comment]
Faced the same problem. It was solved by reinstalling the mod with CurseForge

**Comment by lamont-granquist** [comment]
these are all install problems
