### ISSUE TITLE
Burn time incorrect for SRBs with thrust curves

### ISSUE THREAD

**Issue by JacobB094** [MuMech/MechJeb2#1899]
Currently, MechJeb doesn't take the stock thrust curve into account when calculating SRB burn time, resulting in a burn time value that's off by a large margin. This causes issues with PVG, particularly all-solid stages, which show a much shorter burn than they actually have. Could the burn time be calculated based on the curve instead?

**Comment by lamont-granquist** [comment]
No, I'm not going to put an integrator into the fuel simulation.

The dev version uses the 50% point of the SRB curve which is much closer, that's as good as it is ever likely to get.
