### ISSUE TITLE
Menu text not working

### ISSUE THREAD

**Issue by Mantchef** [MuMech/MechJeb2#1906]
![image](https://github.com/user-attachments/assets/c322d6bb-84c7-47a9-9c50-02a82a0df759)
I downloaded the mod three times, each time replacing the files, so I should not be missing any. Is there anything I missed?

**Comment by lamont-granquist** [comment]
missing localization files.

**Comment by HarryA2** [comment]
No this is a problem with mechjeb right now, I have all localisation files including en-us.cfg in the correct folder I am getting the exact same thing.
