### ISSUE TITLE
mech jeb not loading

### ISSUE THREAD

**Issue by gaster1234567** [MuMech/MechJeb2#1914]
I'm having an issue where the loading is hanging at mechjeb, I'm pretty sure I have the newest version of module manager
[KSP (2).zip](https://github.com/user-attachments/files/17520970/KSP.2.zip)
in the mean time I'll just uninstall the mod

**Comment by sarbian** [comment]
You have an issue with the TweakScale version you are using. Nothing to do with MJ.

**Comment by gaster1234567** [comment]
thank you
