### ISSUE TITLE
Incorrect stage delta-V calculations with 1.5 stage vehicle

### ISSUE THREAD

**Issue by AntonKuzin** [MuMech/MechJeb2#1916]
**Description:**
When you design a LV like Atlas, you probably do it using separate tanks and fuel priority. The problem is, when you do so, in-flight _vacuum_ delta-V readings change over time. Moreover, just after the stage separation, your can see your second stage _gaining more_ delta-V while the engines are still burning. It looks like mechjeb gets confused by the upper tank residuals. It considers it as a "free fuel", therefore increasing the remaining delta-V amount.

**MechJeb version: DEV 2.14.3.0-1412**

**Steps to reproduce:**
Use this craft as an example.
[Atlas.zip](https://github.com/user-attachments/files/17620678/Atlas.zip)
Launch from Baikonur.
Orbit parameters: 190x190km, current inclination, 40m/s pitch start, 0.85d/s pitch angle.

**Expected result:**
Mechjeb's prediction about if you can reach orbit 10 seconds before the orbital insertion should match the actual result. If it tells you you have some margin - you should reach orbit. If you don't - you should not.

**Actual result:**
Till the very end mechjeb believes it's got enough delta-V, but still fails to reach orbit just 100-150m/s short.

**Comment by lamont-granquist** [comment]
This isn't a bug.  The deltaV analyzer has no idea how you're going to fly your rocket or when you're going to drop the engines.  It fundamentally has no idea how to deal with 1.5 stage and was never designed for it.

**Comment by AntonKuzin** [comment]
@lamont-granquist Have you even opened the craft file? Of course it has very good ideas about delta-V distribution across the stages. It's not the single-tank Atlas, when the analyzer sees only one stage.

**Comment by lamont-granquist** [comment]
No, I don't have time right now.  If you're not actually using a 1.5 stage rocket then you've probably got the wrong root part.

**Comment by AntonKuzin** [comment]
That's just great. Ok, point me at the places in code where in-flight delta-v stats are calculated. I'll try to take a look
