### ISSUE TITLE
Visual Bug with Earlyshutoff / last stage 

### ISSUE THREAD

**Issue by Joshuawood1998** [MuMech/MechJeb2#1920]
![KSP_x64_2024-11-22_09-50-10](https://github.com/user-attachments/assets/4006009a-c45a-4184-b39f-c4d1b663e432)
![KSP_x64_2024-11-22_09-50-25](https://github.com/user-attachments/assets/60aefe7a-6ebd-4b7a-a0d6-c70a7478d9c1)

[R-7 Super.zip](https://github.com/user-attachments/files/17868661/R-7.Super.zip)

Here is 2 screenshots and a craft file from RP-1 showing it

**Comment by Nazfib** [comment]
The code here https://github.com/MuMech/MechJeb2/blob/1905b156fefff15d8f3f0739732fbe4587bcae76/MechJeb2/MechJebModuleAscentPVGSettingsMenu.cs#L50-L75
assumes that the index in the stage stats is the same as the corresponding KSP stage. When multiple stages have the same number, that is not the case.
