### ISSUE TITLE
[feature suggestion] steering only mode

### ISSUE THREAD

**Issue by chriscamacho** [MuMech/MechJeb2#208]
the basic contract is...

You(MJ) do the steering, I'll do the engines....

MJ is great where you have a fairly typical staging, however trying to cater to every possible design / corner case is likely to turn the code into spaghetti !

The idea would be where you have a more advanced design, the designer is the best person to be operating engines in their intended sequence / modes of operation

this would be okay where there are nodes but is going to be problematic on modes like landing ....

**Comment by lamont-granquist** [comment]
You can already turn off autostaging.  And you can control engines via action groups.  I'm not sure what the feature here is.

**Comment by lamont-granquist** [comment]
Ah, 2013, yeah this is likely fixed.
