### ISSUE TITLE
Modular Mechjeb for Career mode

### ISSUE THREAD

**Issue by Aethylred** [MuMech/MechJeb2#216]
I have a suggestion for MechJeb2 in Career mode.

Modular control systems that implement only a limited set of MechJeb features appropriately through the tech tree. These modules should be placed along the tech tree so that they're available in a the _next_ level where it's possible to do it manually.

Examples would be:
- Ascent control is available in Basic Rocketry (stage 2) as manual ascent is possible at Basic Rocketry (stage 1).
- Landing control is available in Flight Control (stage 4) as landing is 'possible' in Survivibility (stage 3) which provides landing legs.
- Docking control is available in or after Specialized Construction, which is the when the docking parts become available.

Each module should be significantly cheaper and use less power than the current complete MechJeb unit, but the complete unit should be cheaper than using multiple modules (break even around 3 or 4). ...not that money means anything yet.

**Comment by lamont-granquist** [comment]
pretty sure we've had this for ages.
