### ISSUE TITLE
Suggestion: Landing Autopilot should have "hover" button

### ISSUE THREAD

**Issue by CrashCash** [MuMech/MechJeb2#220]
When I'm landing, I often can't tell the slope of the touchdown point until the last instant. 

It would be really nice to have a "hover" button in Landing Autopilot that would abort the landing and switch to the Translatron KEEP VERT mode with 0 vertical speed. Then I could "Neil Armstrong" over the crater lip or whatever.

judging by the current Kerbal fatality rate and amount of parts scattered across the Mun, I'm just really not fast enough to do this myself.

**Comment by lamont-granquist** [comment]
closing in favor of #1052
