### ISSUE TITLE
Ascent Guidance missing in MJ 2.1

### ISSUE THREAD

**Issue by DocAnderson** [MuMech/MechJeb2#222]
First, great work. Love MJ2 ... exit fanboy mode.

Running KSP .22. Loaded MJ2 2.1. Twice. Ascent Guidance is no longer showing up in the menu. Also reverted to default in settings. Still no go.

AG is my favorite anti-tedium feature of MJ2.

**Comment by 5kyw4Lk3r** [comment]
running mechjeb 2.5.3 and I'm having ascent guidance window disappearing only reappearing after I recopy all but the plugin file with ksp 1.0.4 running and then loading back to VAB then back to launchpad. any help to solve this is appreciated. it's the best ksp mod so I can't play without it. tx.
