### ISSUE TITLE
*Delayed thrust engines not compatible alone with MechJeb

### ISSUE THREAD

**Issue by theOmniverse** [MuMech/MechJeb2#242]
Hello,

So I've been noticing that a few engines from other mods do not allow thrust control by mechjeb unless they are accompanied by a compatible engine (like a stock one).

I've noticed this particularly with the LLL (Lack Luster Labs) Large Nuclear engines. Although, I think there may be a couple non-LFO engines in the Near-Future pack that have the same issue.

when a maneuver is executed, the ship lines up, warps to, and unwarps **right at the node time** (no lead time at all) and then fails to increase the thrust. 
This is inconvenient because the thrust is also locked. which means I have to manually execute the nodes with A.S.S. help. (ugh the pain :P )

however, I have noted these engines do work in two situations:
1) when they are accompanied by a working engine
2) when landing guidance does the deorbit burn (suspicious) (but it doesn't work for the course correction in landing guidance) 

mechjeb 2.1 (public release) KSP .22

**Comment by Anbalsilfer** [comment]
Not intending to flog a dead horse here, but it seems to me there is still an issue here with MechJeb's auto landing feature. Whenever I try to land with a delayed-response LLL engine, the required thrust needed for the braking burn will be dramatically underestimated by MechJeb, causing me to crash into the surface at high speeds every time.

As a suggested work-around until a permanent fix, maybe it would be a good idea for MechJeb to actually suppress all engine response times while it is installed through a CFG addition along the lines of:

@PART[ModuleEngines*]:FINAL {
    @useEngineResponseTime = false
}
