### ISSUE TITLE
Fresh install, No interface for MechJeb

### ISSUE THREAD

**Issue by ArchAngel21** [MuMech/MechJeb2#277]
Hello,

Playing KSP .23, I cannot access the MechJeb menus. Nothing pops up when I try to launch my craft (Stock KerbalX). I recently reinstalled KSP and MechJeb to make sure I had the most current versions.

I installed the "MechJeb2" folder directly into the "GameData" folder, per standard instruction, but that did not work.

I have tried the Dev build as someone in a similar report stated. I completely deleted the first MechJeb installation, and copied the Dev build to the same locations. Same outcome, I have the parts but no menus or controls.

Any help would be greatly appreciated! My rockets tend to turn into missiles instead of spacecraft without MechJeb!

**Comment by juak123456789** [comment]
How can i add AR202 to a ship?
