### ISSUE TITLE
wish list for MJ

### ISSUE THREAD

**Issue by drtedastro** [MuMech/MechJeb2#290]
I would really like to see these 'additions' to MJ.
1. Ability to specify a Time For Launch, in the Ascent Guidance tab.  For planning gravity assist and special fly-by, it is necessary to lift off very close to prescribed times.   Something like a radio toggle button for 'Time controlled launch, and then ability to put in the time in format such as Y D H M S  or such.
1. Ability to specify Altitude above surface for final vertical descent in Landing Guidance.  It would be very helpful if it was possible to specify a target, as can be done now, via map or coordinates (Lat Lon) but also a vertical elevation above that surface location where all horizontal velocity has been zero'd and from that altitude strictly a vertical descent is made.

Thanks for such a great mod.  The only way I fly is via MJ..... thanks Sarbian and all other supporters.

**Comment by lamont-granquist** [comment]
1. I think is more addressed by the Warp Helper and KAC.  2. I is oft-requested and covered in #1052
