### ISSUE TITLE
Ascent Guidance - "guestimate" of Δv for ascent, and for circuralize

### ISSUE THREAD

**Issue by palamedes** [MuMech/MechJeb2#302]
Again, Ascent Guidance is my favorite tool -- great stuff.  

I would really like to see in the window at the bottom a guess / estimate (if possible) of roughly the Δv required to get from the surface to the selected altitude, and then another Δv estimate of the circularize maneuver, if possible.

**Comment by lamont-granquist** [comment]
#1061 will largely fix this issue.
