### ISSUE TITLE
Modular system for manoeuvres

### ISSUE THREAD

**Issue by KaoSDlanor** [MuMech/MechJeb2#309]
I love the mod and find that it executes its manoeuvres excellently, I would however like a more diverse selection of things to do with it. Rather than rattle off a list of manoeuvres I would really appreciate a way to make my own. If you could add a folder in mechjeb where you can paste files which add custom made manoeuvres I think many users would benefit

all we need is a basic API for detecting things about the ship and sending commands based on that

we could then build in amazing stuff custom made for our creations and send them with the ships so VTOLs could automatically stop in mid-air and move set distances in any direction etc etc

**Comment by lamont-granquist** [comment]
I think the solution to that is probably kOS or kRPC.  There's the scripting autopilot which allows composition of mechjeb functions.  To actually write actions would require access to the C# interface, which would be a compiled dll, not a script.  To allow a scriptable API for maneuvers would require a scripting interface that exported the C# API for Vessel+Orbit and half duplicating most of kOS.
