### ISSUE TITLE
[MJ 2.1.1]Trying Too Hard to Cancel Horizontal V During Landing

### ISSUE THREAD

**Issue by NGTOne** [MuMech/MechJeb2#322]
While I love MechJeb on large craft (I'd go nuts if I had to fly my ships manually at 1 FPS), I have an issue with it - during landing, it will try to cancel its horizontal velocity WAAAAY too close to the ground, and go chasing the retrograde node around and around until its horizontal V reaches zero - at which point the object I'm landing is angled at 15 degrees to the ground, and MJ decides to cut throttle and smash half the landing legs/wheels into dust. Or, better still, it just keeps chasing the retro node (rotating all over the navball) until it either hits the ground or runs out of fuel, in either case causing severe damage to the landed object. Trying to abort the autoland, pushing the throttle to max, then using "land somewhere", doesn't work because it does exactly the same thing.

The craft I'm using for this weighs about 1500 tons at the start of the deceleration burn on Kerbin (after a quick jaunt to orbit and being commanded to land at the KSC), and has 256 of the small reaction wheels (but engine gimballing disabled due to possible CoM issues). When the landing procedure begins, it has a TWR of approximately 1.3, and more than enough fuel to make the landing. My best hypothesis as to what is happening is that the massively powerful engines are straining ever so slightly against their mountings, and introducing a slight horizontal acceleration (that MJ goes nuts trying to correct, because horizontal V = bad).

**Comment by lamont-granquist** [comment]
Closing this as a dup of fixing all the landing things in #1052
