### ISSUE TITLE
Attempt at customization of when modules become available -> no auto-throttle

### ISSUE THREAD

**Issue by tageborg** [MuMech/MechJeb2#337]
I am trying to reconfigure my installation of MechJeb to make Ascent Guidance available at with "flightControl" tech (with the AR202 case, I never use the pod). No matter if I set MechJeb as available with "start" tech and Ascent Guidance at "flightControl", or both at "flightControl", I get the option to bring up the Ascent Guidance window when I am at the "flightControl" stage in the tech tree, but the feature itself will not control my vessel's thrust. Automatic steering/vectoring of the vessel works as expected, though. 

If I advance in the tech tree to "unmannedTech", the automatic throttle control becomes active, just as it would have if I had not edited the CFG file.

I have set the mumech_MJ2_AR202_features3 value "TechRequired" to "flightControl" and the "MechJebCore" module unlockTechs line appropriately.

I suspect this may have been introduced in jenkins build 198. (Commit efd8f10abb3c85b5a7127e423040ec0e5aa80bef)

Not sure if this really counts as a bug. Are we "supposed" to be able to reconfigure MechJeb by means of the CFG files? Still, it is bugging me. :)

**Comment by lamont-granquist** [comment]
looks fixed
