### ISSUE TITLE
Launch inclination fix

### ISSUE THREAD

**Issue by NathanKell** [MuMech/MechJeb2#341]
In ascent guidance, the inclination box doesn't actually give you an inclination; instead you're just setting launch azimuth and burning in that direction, with the plane becoming whatever. This is particularly a problem when using launch-to-rendezvous or launch-into-target-plane, which require exact inclinations.
I know it's Math :( but here is a page that should help.
http://www.orbiterwiki.org/wiki/Launch_Azimuth
With this you should be able to calculate the azimuth to launch along to achieve a desired plane, or state "plane unreachable."

**Comment by lamont-granquist** [comment]
fixed this a long time ago so it properly follows great circle routes.  then PEG came and made targeting desired inclinations really accurate.  the old trick of setting a high altitude to avoid the classic ascent guidance cutting the engine when apo > target on RO/RSS also used to mess things up terribly.
