### ISSUE TITLE
[Suggestion] User Defined Automation

### ISSUE THREAD

**Issue by akherber** [MuMech/MechJeb2#346]
Suggestion:

Action groups and staging based on user defined parameters such as going above or below an altitude or simply time. User defines which action group or stage and what the trigger is. 

Triggers might include: Time(countdown), Time(universal), Altitude(Above/Below/At), Atmospheric Pressure, Orbital Stats, Electricity Level, Fuel Level. Pretty much any value (or percent of one!) that you can show could be a relevant trigger. The more available actions we can control using these triggers opens up a very large list of possibilities.

Specifically, the issue I am trying to solve is staging at a specific altitude in my descent.

Dev routes that may ease transition while allowing people to use this quickly would be simple scripting <trigger><action>. For example altLessThan:200mactionGroup:1 or electricChargeLessThanVal:20<actionGroup6>. This could eventually turn into drop down menus and custom windows/buttons all doing preprogrammed actions allowing people to customize MechJeb for specific vessels or import created functions from other users?

I just see a very large potential for this as a customizable feature that would set MechJeb on a whole new level of functionality.

I am aware there are other mods out there that have accomplished this, but I don't want to add anymore parts to my rockets when I have MechJeb!

**Comment by lamont-granquist** [comment]
This I'm going to close this as covered by the scripting autopilot, and concrete bugs/enhancements need to get opened against that.
