### ISSUE TITLE
AI get stuck performing course correction during landing guidance

### ISSUE THREAD

**Issue by ichaleynbin** [MuMech/MechJeb2#384]
![image](https://cloud.githubusercontent.com/assets/2417892/3497101/a9d89988-05e8-11e4-87b9-527113ca9b2c.png)
I have had successful landings with the landing guidance, however, this landing I have screencapped and the landing immediately prior to it, the AI is getting stuck trying to course correct. Right now, it shows an error in the hundreds of meters or so, though it varies wildly (100-400m) but the problem is that it was too busy course correcting to bother to slow down. This landing is still in progress, as of writing, but the previous landing with this issue, the target difference was measured in millimeters much of the time, and no more than 5m, but the AI was still attempting to course correct by 0.0m/s when it smacked into Mun at full speed. 

Suggestions to fix: Lower tolerances for course, allow higher errors in landing prediction, and/or input an override onto the course, such that when it's time for the deceleration burn, any course corrections necessary are forgotten about. Missing by 100 meters is better than smacking into the moon full speed, this should be obvious, but the AI does not think so.

**Comment by lamont-granquist** [comment]
Another dup of #1052
