### ISSUE TITLE
Coasting-free ascent to orbit

### ISSUE THREAD

**Issue by EbbiDos** [MuMech/MechJeb2#393]
It would be really nice to have an option in the Ascent Guidance AP for a coasting-free ascent to orbit. I use a bunch of mods like RSS, Engine Ignitor etc. and restarting engines after a coasting phase isn't always possible depending on the engine. As in real life rockets mostly burn as long as orbit isn't achieved yet.
For example: I tried recreating the launch of the SpaceX Falcon 9.1 Orbcomm OG2 launch of July, 14th. The real rocket acheived an 743 x 640 km orbit after 578 seconds of non-stop burning (except the 6 second pause during stage separation). It's impossible to do that with MJ because MJ cuts off the engine as soon as Apoapsis reaches 'Orbit altitude'. With that coasting-free option enabled MJ could change the ascent path to keep the value of Apoapsis constant. Engine cutoff would then be at reaching a circular orbit or - to reference some good ideas in issue #25 - a desired periapsis is reached.

**Comment by lamont-granquist** [comment]
either this is done with PEG or its part of #1061
