### ISSUE TITLE
Feature Request: Bring back Autom8

### ISSUE THREAD

**Issue by rspeed** [MuMech/MechJeb2#400]
MechJeb 1 had a feature called Autom8 which would allow users to write Lua scripts that controlled MechJeb. You should bring that back, or at least add an API for other plugins to control MechJeb.

**Comment by ninja4826** [comment]
I was just looking around for a way to do an automated launch, FTL jump (using another mod) to a station, and dock. Bringing back Autom8 with an updated API would make something like this a breeze.

**Comment by rspeed** [comment]
Have you taken a look at [kOS](http://forum.kerbalspaceprogram.com/threads/68089-0-90-kOS-Scriptable-Autopilot-System-v0-17-0-2015-4-18)?

Also, didn't realize this was still open. Closing for self-apparent reasons.
