### ISSUE TITLE
Mechjeb researched in R&D but not useable

### ISSUE THREAD

**Issue by BIGMOS** [MuMech/MechJeb2#401]
I have unlocked mechjeb 2.3.1 in ksp .24.2, but when i go to uses it, it says i still need to unlock it When I try to attach it to a ship.
Part requiers and entry purchace in R&D.

**Comment by Monniasza** [comment]
[Video evidence](https://youtu.be/_UUwBsIxCEQ)
[KSP.log](https://github.com/MuMech/MechJeb2/files/3717831/KSP.log)
Please reopen.
