### ISSUE TITLE
Auto-warp overshoots node

### ISSUE THREAD

**Issue by fdepee** [MuMech/MechJeb2#402]
When I'm doing interplanetary burns I often have nodes that lie 20 days+ into the future, sometimes 200 days+

Sometimes after clicking "execute next node" in Maneuver Planner when a node lies very far into the future, the auto-warp seems to miss the node and 'brakes' too late. I've had overshoots of more than 2 hours worth.

It still aligns the craft and performs the burn, but the resulting orbit is totally out of whack due to the late burn.

setup details:
- I'm using 2.3.1.270 (Jul 25, 2014 7:45:30 PM) an have KSP 0.24.2 via Steam
- I have no other mods installed
- MJ2 seems to otherwise work correctly for me (besides some quirkiness with delta-V displays, but that could also be caused by my crazy staging schemes)

to reproduce:
- attempt node execution for a node that lies 100 days+ into the future (sometimes it doesn't occur so one might have to give it a few tries)
- in case it's hard to reproduce I could try to capture it on XSplit and post a link in the comments if that's helpful

**Comment by lamont-granquist** [comment]
This has to have either been fixed or been an underlying KSP issue that was fixed or people would be screaming about it.

**Comment by Wondiws98** [comment]
For anyone landing here. I've found that the issue was caused by a mod called "Persistent Rotation".

I was experiencing the same issue, I uninstalled it, issue no longer happens.

Edit: I know this issue is pretty old but i felt it was still relevant since I was experiencing it in the latest MechJeb version.
