### ISSUE TITLE
"Limit to Terminal Velocity" setting references vertical, not surface, velocity.

### ISSUE THREAD

**Issue by adammartinez271828** [MuMech/MechJeb2#409]
MechJeb's "limit to terminal velocity" setting limits the craft's _vertical_, not surface, velocity.  This results in overacceleration and low-to-mid altitudes if your craft is not pointed vertically.

To replicate: build an overengined craft, activate the limit to terminal velocity setting, max the throttle to gain some altitude, and turn to zero pitch.  Your surface velocity will accelerate way beyond terminal velocity, but your vertical velocity will stay below terminal velocity.

**Comment by K3BaRZ4s** [comment]
I wrote up a proof that, for maximum fuel efficiency (given a pre-determined ascent trajectory):
the "total velocity" must equal the "terminal velocity".

https://www.sendspace.com/file/dm8gmt
This is an XHTLM file, which opened right up in my Firefox browser.  Let me know if I should put this up somewhere else.

So, it's true that the best is "vertical velocity" = "terminal velocity" for an ascent to be purely vertical.  And consistently, the case of an arbitrary (non-vertical) ascent has "total velocity" = "terminal velocity".  I was surprised the math comes out this way, but it does.  The physics let a correct answer also be a simple answer - it usually doesn't happen!

**Comment by lamont-granquist** [comment]
This is no longer accurate in post-KSP 1.0 non-soupy atmosphere.  You want to break through the Mach barrier as fast as possible and reduce gravity losses and benefit from Oberth, particularly for orbital-class launchers.  For sounding rockets, in Real Solar System or real-sized solar systems, then throttling down can reach higher altitudes with intermediate thrust, but the ballistic coefficient of orbital class rockets is way too large (and the Ascent AP isn't really suitable for sounding rockets).
