### ISSUE TITLE
Smart A.S.S not working with the full RSS/RO suite.

### ISSUE THREAD

**Issue by OtherBarry** [MuMech/MechJeb2#418]
I have Real Solar System, Realism Overhaul and all the required/recommended mods for that installed, which means that all of my attitude control comes from RCS. When I try and use Smart A.S.S, it moves towards my intended attitude in about 5 degree steps, spending a lot more propellant than necessary, and taking a lot longer than it should. When it finally gets to my desired attitude, it's incapable of keeping it on target, and constantly moves around. I'm pretty sure this isn't related to having overpowered thrusters, as i get the same thing when using 220N, 33N and 1.8N thrusters, which I've verified are using their correct thrust using the mechjeb 'RCS thrust' stat. If I set MJ to use stock SAS, It's much more wild to start off with, but is far more accurate once it's in a few degrees of the target, but even then, it uses much more propellant than it should need to maintaining that attitude, despite there being no external force moving it away from that attitude, and it is incapable of operating with any form of physical timewarp.

**Comment by lamont-granquist** [comment]
ModuleRCSFX was merged into KSP some time ago
