### ISSUE TITLE
Manual overrides for throttle and time warp control

### ISSUE THREAD

**Issue by tavert** [MuMech/MechJeb2#42]
During ascents and node execution, it can make sense sometimes to have MechJeb control attitude but manually control throttle. The closest approximation for that now is typing numbers in the "Limit throttle to %" box. The other places MJ controls throttle that I can think of are Translatron and Landing, for which manual throttle overrides are a bit less likely.

Likewise I don't always want MechJeb to time warp for nodes or landing (where else does it control warp? obviously the warp helper, overrides aren't meaningful there). I have some super-light ships with Kerbals hanging on to ladders, so standard time warp isn't allowed. If MechJeb weren't constantly trying to get into time warp though, I would be able to manually do physical time warp (alt-.) up to 4x.

**Comment by robot256** [comment]
The "manual throttle while executing a node" is now possible with the Smart A.S.S. "Node" button.  I'm going to investigate whether any of the new Ascent Guidance checkboxes allow you to manually throttle.  Personally, I have done some launches where I modify the "limit acceleration" option on the fly to get the behavior I want, specifically not flipping over during Max Q.

**Comment by lamont-granquist** [comment]
flipping over during Max Q will be best solved by the AoA limiter.  rest of this bug seems done.
