### ISSUE TITLE
Mechjeb closes solar panels

### ISSUE THREAD

**Issue by fl1guy2** [MuMech/MechJeb2#424]
For some reason whenever using Mechjeb, it closes all my solar panels when warping for longer amounts of time. It only happens when using Mechjeb and I've tested it on about 10 different designs. I also tried it on stock with only Mechjeb installed and the same thing happens. My output log doesn't give any hints on anything messing up either.

I can warp for 100+ years inside Kerbin SOI but the second Mechjeb warps outside the system it automatically closes all solar panels! It doesn't make any sense to me

**Comment by marosciacchitano** [comment]
Mechjeb now automatically deploys solar panels when it leaves the atmosphere and closes them when in enters an atmosphere. Unfortunately the code is buggy and it will open panels on space planes at launch and break them. This appears to be a related issue.

**Comment by Olympic1** [comment]
MJ has the ability to open/close solar panels in the latest builds

**Comment by sarbian** [comment]
no, this is totally unrelated.
