### ISSUE TITLE
DV window makes my game Judder(freze) every few seconds. 

### ISSUE THREAD

**Issue by joebopie** [MuMech/MechJeb2#448]
this is a problem that only started about 2 weeks ago for me but I have tried many different versions of MJ down to MJ.292 but all with the same affect. if i make something with above 40 parts and have MJ on it with the DV window up, it will Freeze every few seconds for a split second. both in the hanger and out.  this is very frustrating when trying to fly planes or control anything manually and just annoying to watch. it seems that the more mods that are installed makes the problem a tiny bit worse but without any other mods it still does it with over 60 parts on the ship. this is all very odd as I have never had this problem before on massive ships with even more mods. any help or idea appreciated.
joseph.

**Comment by sarbian** [comment]
Those should be fine  since the move to the KER code and its optimization of memory use
