### ISSUE TITLE
KSP MechJeb2 Launch to Rendevous: can´t get closer then 300km

### ISSUE THREAD

**Issue by RichardDantas** [MuMech/MechJeb2#466]
Hi,

I´ve read a lot, watched to several tutorials but I just cant get to my Space Station (orbiting Kerbin). All my launches are too far way to a encounter and docking.

My data:
-Space Station Orbit: 80 km
-I used Ascent Guidence to get to orbit and reverted flight to launch.
-The angle is automaticaly set in mechjeb (the flight with just made). I luch "launch to rendevous" and engage autopilot...
- After circularizing, I'm at least 250km from the Space Station!!!

Need help!!! Im using TAC Life Support and my poor kerbonauts are going to starve !

**Comment by lamont-granquist** [comment]
This is hard, see #1061
