### ISSUE TITLE
Feature Request: Satelite Positioning Planner

### ISSUE THREAD

**Issue by tfischer4765** [MuMech/MechJeb2#489]
This idea popped up when I experimented with RemoteTech and realized that currently there is no good way to use MechJeb to position satelites relative to each other/Kerbin/whatever. Here's what I propose:(phrased roughly as user stories)
- When rendezvousing with another satelite, I want to be able to specify a final distance to the target up to the diameter of the target's orbit to be able to space satelites around a celestial body.
- When "rendezvousing" with another satelite, I want to be able to specify an orbital angle ranging from -360° to 360° relative to the orbited body, where values greater than zero mean "ahead of" and negative values mean "behind", to be able to space satelites around a celestial body

These two should be fairly easy to implement, since they are basicly variants of the rendezvous maneuver, where the maneuver is targeted at a point on the target's orbit instead of the target itself. I've got some more ideas for KEO maneuvers, but I will post those as a separate issue.

Have fun coding!

**Comment by lamont-granquist** [comment]
The target period offset in #1065 is the easiest implementation of this.  Distance is not trivial but is on the list for #1058
