### ISSUE TITLE
Request: Apogee kick / inclination change

### ISSUE THREAD

**Issue by NathanKell** [MuMech/MechJeb2#491]
Request for a combined "change periapsis" and "change inclination" maneuver, to be used at the combined apogee and AN(or DN) one sets up after a non-equatorial launch to GTO. We can already change apoapsis at the AN/DN (which is great for this), but I didn't see a way to combine the maneuvers at the new GEO apoapsis. (Did I just stupidly miss something?)

**Comment by kiwivogel** [comment]
The only way to currenty do this is to make the node for the apogee kick at the AN/DN and then fiddle with the node editor unti you have what you want. I agree I'd love to see a way do do this automatically.

**Comment by lamont-granquist** [comment]
Fixed in #915
