### ISSUE TITLE
Immediate departure cannot be planned with porkchop selection/advanced transfer mode

### ISSUE THREAD

**Issue by dawnroselyn** [MuMech/MechJeb2#501]
This is for version 2.4.1 build 366

The leftmost pixel in the porkchop selection map used to be about 3-4 hours from current time.  Now it is *right now*, and if this time is selected, an invalid maneuver node will be created (timing and D/v are WAY off).  The only next option is 5 days, which isn't a reasonable wait for low orbit.

**Comment by tgharold** [comment]
It would be nice if there was a way to zoom in on the left edge of the porkchop plot, or limit it to only showing a porkchop for the next 30 days.
