### ISSUE TITLE
maneuver node planner or editor open failing to open, null reference exceptions

### ISSUE THREAD

**Issue by whiskeyfur** [MuMech/MechJeb2#502]
Dunno what I'm doing wrong here but when I have the maneuver node planner or editor open, my debug log gets filled with "[Exception]: NullReferenceException: Object reference not set to an instance of an object", and the two mentioned windows are little more then tiny boxes with the corner graphics inverted to look like a cross shaped, with nothing inside of each.
![gonebuggy](https://cloud.githubusercontent.com/assets/3805521/5515941/12d4d89e-8838-11e4-921f-148f0abf44e7.png)

I have the following installed with the dates I downloaded each
12/17/2014  09:43 PM         5,111,396 ExpPack_0.3.0.zip
12/20/2014  09:02 AM             9,531 Kerbanomics_0.1.2.zip
12/16/2014  08:36 PM           460,511 KSP-0.90-ScienceAlert-1.8.2.zip
12/16/2014  08:34 PM         4,324,830 MechJeb2-2.4.1.0.zip
12/16/2014  08:51 PM            37,988 Regolith_0.1.0.zip
12/16/2014  08:55 PM            41,443 StageRecovery-1.5.2.1_2.zip
12/16/2014  08:57 PM         5,569,478 StationScience-1.4.zip
12/17/2014  09:41 PM            48,240 TacFuelBalancer_2.4.1.1008.zip
12/16/2014  08:54 PM           248,100 VOID-0.16.zip
12/16/2014  08:51 PM         1,440,316 WarpDrive_0.1.0.zip

**Comment by sarbian** [comment]
Fixed a while back
