### ISSUE TITLE
Request: Launch into longitude of ascending/descending node

### ISSUE THREAD

**Issue by AusQB** [MuMech/MechJeb2#508]
Career contracts to put satellites in Kerbin orbit provide a longitude of ascending node, but there is no way to automate launching to match the orbit. Obviously MechJeb allows you to input the altitude and inclination, but I have to manually eyeball the orbital path in the map view to determine roughly when to launch.

If it is at all possible, could you add an option in the Ascent Guidance module to input a longitude of ascending node to launch from?

**Comment by lamont-granquist** [comment]
dup of #1061
