### ISSUE TITLE
Launch into plane of target using negative inclination

### ISSUE THREAD

**Issue by MOARdV** [MuMech/MechJeb2#518]
I have a station over Kerbin at a 51 degree inclination.  I've been timing my rendezvous launches so that they'll launch north instead of south, so the inclination should be 51 degrees.  However, once I engage the autopilot and press "launch into plane", the inclination window shows -51 degrees, and the craft launches into the orbit if I don't manually delete the '-' sign in the inclination window.  I tried deleting the value before engaging the autopilot, and it still selects -51.  This showed up sometime in or after MJ 2.4.2, I think; it's still in dev build 385.

**Comment by MOARdV** [comment]
More characterization - this bug is happening consistently if I schedule the launch about 2 hours prior to the launch window.  However, if I wait until about an hour prior, the correct inclination is selected.  It looks like the ascent guidance window is choosing the inclination for the physically nearest crossing to when the autopilot is engaged, not the inclination for the next temporal crossing.

**Comment by sarbian** [comment]
Should be OK now. I had indeed moved the inclination outside the loop and it was only updated when the button was pressed.
