### ISSUE TITLE
Solar Array AutoDeploy Problem in dev build #385

### ISSUE THREAD

**Issue by marosciacchitano** [MuMech/MechJeb2#523]
Solar Arrays on space planes auto deploy when the plane begins to accelerate, which almost always instantly breaks them. This may have something to do with MechJeb confusing the plane with the rover. Probably related to the new panel deployment feature.

Simple fix (maybe): add an option in _Utilities_ to turn off PV Panel management.

**Comment by sarbian** [comment]
Fixed in new build
