### ISSUE TITLE
request: Move Use RCS for Rotation to utilities

### ISSUE THREAD

**Issue by Felson** [MuMech/MechJeb2#526]
It would be nice to be able to disable RCS for rotation when not balancing the rest of RCS. Would help fix "Shake of death" plus, IMO, Gyros are much better for rotation anyway.

**Comment by sarbian** [comment]
Can you elaborate a bit ? This is not clear at all for me.

**Comment by Felson** [comment]
When every I try and land anywhere not close to see level, it craters. I just assumed that mechjeb couldn't tell what the altitude was at the landing site.

**Comment by sarbian** [comment]
Ok. That is not possible unless the dev changes the RCS module to add an option. 
Or use the moduleRCSFX, but it's not fully supported in MJ.

**Comment by Felson** [comment]
How do you do it with the RCS Balancer? Would it not be possible to have a mode where RCS always has full power, but doesn't fire for rotation?

**Comment by gmcnew** [comment]
This should be fixed now -- the 'Use RCS for rotation' option (in the SmartRcs window as well as the Thrust options) will work regardless of whether you're using the RCS Balancer.

**Comment by sarbian** [comment]
You committed it to master.
Commit to dev please

**Comment by gmcnew** [comment]
Oops, sorry. I've checked it into dev now.
