### ISSUE TITLE
mechjob2 tab not displaying

### ISSUE THREAD

**Issue by drackasarusrex** [MuMech/MechJeb2#539]
I have version .90 of ksp installed with mechjeb2-2.4.1.0. I can see ksp loading the mod when i first launch it. Once i go into the game I do not see the mechjeb tab anywhere. The mechjeb2 folder is currently in the gamedata folder as required. I have also tried a few different versions of mechjeb hoping that would solve the issue.

**Comment by sarbian** [comment]
Did you put the AR202 part on your ship ?

**Comment by drackasarusrex** [comment]
I am officially an idiot. Thank you very much
