### ISSUE TITLE
Allow for multiple LandingSites config files

### ISSUE THREAD

**Issue by hakan42** [MuMech/MechJeb2#541]
Currently, if an external mod wants to add nodes to the LandingSites, it needs to overwrite the one file.

I would love to have either multiple files so each mod could persist its desired landing sites or an API in MechJeb through which new site nodes could be added dynamically at runtime.

**Comment by sarbian** [comment]
It already reads the content of multiple files. The only ,node that it only process once is the RSS one. 
The other 2 format ( KerbTown/Kerbal-Konstructs and MJ native) read all the found node, so all the files
