### ISSUE TITLE
Use RCS to kill off relative velocity

### ISSUE THREAD

**Issue by tc0312** [MuMech/MechJeb2#545]
Hi!

I've been doing a lot of semi-manual docking lately.
I found that it's quite tedious to manually kill off small relative velocity to target using RCS. Keyboard isn't great to do precise input even in "shift" mode.
It would be great if MechJeb can do it for me. I checked the docking autopilot module but it will simply dock the ship for me.
I did some searching. It seems MechJeb used to have this function. Is the function removed? If yes, mind if I add it back as a button in Smart ASS?

Thanks!

**Comment by sarbian** [comment]
I added a module that does that in the last dev build. In the "SMARTRcs" window

**Comment by tc0312** [comment]
Thanks!
