### ISSUE TITLE
Ascent guidance: fine tuning and coast issues

### ISSUE THREAD

**Issue by futrtrubl** [MuMech/MechJeb2#555]
In ascent guidance fine tuning apoapsis it changes facing from ascent profile to surface vel +. Then during coasting to edge of atmosphere it faces the ascent profile again but doesn't obey limit angle of attack.
This was reported before and I believe was supposed to have been fixed, though I can no longer find the issue. It is still present in dev 414.

**Comment by lamont-granquist** [comment]
i fixed this one with the rewrite that landed with the altas-centaur PEG implementation
