### ISSUE TITLE
Docking Port

### ISSUE THREAD

**Issue by djmad** [MuMech/MechJeb2#556]
Sometimes when autodocking, dockee and docker are not saved correct in the config.
When undocking a stuck docking port occures.

**Comment by sarbian** [comment]
This is a stock bug, not a MechJeb bug.

**Comment by djmad** [comment]
ok, thx

than please delete




lg Rene Marhold

Ing. Rene Marhold
International Welding Engineer

Marhold GmbH
Industriepark 9
8682 Hönigsberg

Tel.: +43 650 3382846
Email: rene@marhold.net
Fax.: +43 3852 3042727
________________________________
Von: sarbian [notifications@github.com]
Gesendet: Mittwoch, 08. April 2015 14:00
An: MuMech/MechJeb2
Cc: Rene Marhold
Betreff: Re: [MechJeb2] Docking Port (#556)


This is a stock bug, not a MechJeb bug.
