### ISSUE TITLE
dV issues from switch to KER code

### ISSUE THREAD

**Issue by NathanKell** [MuMech/MechJeb2#559]
@sarbian with the latest MJ build (that you built for me...) I've encountered two simulation errors:
1. Procedural fairings do not count as decoupled for the stages they should be decoupled under (verified by having them decouple in the stage prior to the engine lighting, then removing them entirely--different dV values for that stage)
2. MJ seems to no longer understand "stage and a half" staging, where you ground-light your engine but also have boosters (that burn out before your engine does, and are decoupled then).

It seems a safe assumption that these are related, and that a decoupler doesn't properly remove dry mass from the simulation stack, etc.

**Comment by Barhandar** [comment]
KER also shows different, slightly lower dV value than latest Curse release of MJ.

**Comment by sarbian** [comment]
Fixed in 4acc2ac740a6991e08cf91a8054aba14847cc2a5
