### ISSUE TITLE
build #437 - TWR displayed seems to be exactly 50% of reality

### ISSUE THREAD

**Issue by DanPli** [MuMech/MechJeb2#568]
Testing the current version build 437 - TWR seems to be off by exactly half of what is displayed. Rockets begin to lift slowly at 2.01 TWR. Tests were done by simple, single stage crafts, pod-tank-engine.

**Comment by sarbian** [comment]
A rocket with an Sea Level TWR of 1.03 just barely flew up here so all seems fine. Make sure you display all stats and check the SLT and not the TWR since 1.0 engine have a different thrust at sea level (SLT) than in vacum (TWR).
I'll force the display of SLT for next version
