### ISSUE TITLE
KSP 1.0 Terminal Velocity calcs

### ISSUE THREAD

**Issue by lamont-granquist** [MuMech/MechJeb2#570]
With the new aerodynamic model in 1.0 it looks like the terminal velocity calc in mechjeb is broken.  Once you've launched it seems to plummet down to 40m/s and then only gradually goes up to around 80m/s and "limit to terminal velocity" is pretty useless to check now.

Sorry if this already got reported, but I couldn't find a relevant closed github issue via search.

**Comment by dgies** [comment]
Confirmed.  Ascent speeds are extremely low with this enabled, and the 'atmospheric drag' value from the vessel info stats shows values way less then 1G when the limiter kicks in.

One more thing you might need to watch for when fixing this is that drag is now dependent on angle of attack and we might need to relax the limiter to prevent it from kicking in too strongly at the start of a gravity turn.  Perhaps consider only the portion of drag as projected along the vessel's orientation.

**Comment by sarbian** [comment]
This was fixed in the dev version already. Did you try that ?

As for the limiter I thinks that I ll move it on real surface speed instead of the vertical component.

**Comment by dgies** [comment]
Sorry haven't tried the dev build yet.  Looking at commit 9c6f0cf3ce2e2a4b03e61f8003651030eef91eb1 I think that will solve the problem of the calculation being way off, and a brief experiment seems to confirm they still model drag as speed-squared.

I still think you'll have a problem with throttle cutting out at the start of a gravity turn when the AoA increases and the new aerodynamic model will spike the drag.  A sudden cut of throttle at that moment I suspect will lead to many rockets flipping over.

**Comment by futrtrubl** [comment]
Drag shouldn't spike too high on the gravity turn if the AoA isn't too high. If your AoA is too high then TV limiting will likely not be your greatest issue.

**Comment by dgies** [comment]
After playing around with it a fair bit I think the new version is good enough for all but extremely tall/skinny rockets.  If the AoA is causing that much of an increase in drag you have bigger stability problems then MechJeb being over-eager with the throttle limiter.
