### ISSUE TITLE
request: quick transition to translatron

### ISSUE THREAD

**Issue by chriscamacho** [MuMech/MechJeb2#571]
We've all had it happen as a landing rapidly approaches we see some less than optimal terrain feature, or maybe your base has a bunch of buildings you're about to land on.

You have to first turn off the auto pilot before you can hover and change position manually, potentially meaning at least several seconds of free fall while you engage the right setting on the translation.

It would be very useful to have an "abort to hover" button which would abort the landing and switch to a hover without horizontal velocity

**Comment by jacksonj04** [comment]
:+1:

I wouldn't even mind the horizontal velocity remaining, as long as it tries to remove vertical. The chances are I want to 'keep going' to find a landing spot, there's no sense wasting fuel removing a horizontal component only to then add it back.

The ultimate feature here would be the ability to 'pause' and 'resume' vertical descent, or a 'landing site finding' mode which limits horizontal speed as well, so if you spot bad terrain you can pause descent, and when you're happy you're over you can continue landing as normal (complete with slowing to appropriate touchdown speed, deploying legs if not already deployed etc).

**Comment by chriscamacho** [comment]
good point about the horizontal component

**Comment by lamont-granquist** [comment]
dup of many other requests compiled in #1052
