### ISSUE TITLE
Linux build errors

### ISSUE THREAD

**Issue by chriscamacho** [MuMech/MechJeb2#573]
MechJeb2/ReentrySimulation.cs(35,9): error CS0246: The type or namespace name `SimulatedVessel' could not be found. Are you missing a using directive or an assembly reference?
MechJeb2/ReentrySimulation.cs(80,108): error CS0246: The type or namespace name `SimulatedVessel' could not be found. Are you missing a using directive or an assembly reference?
MechJeb2/MechJebModuleStageStats.cs(7,7): error CS0246: The type or namespace name `KerbalEngineer' could not be found. Are you missing a using directive or an assembly reference?
MechJeb2/MechJebModuleStageStats.cs(26,16): error CS0246: The type or namespace name `Stage' could not be found. Are you missing a using directive or an assembly reference?
MechJeb2/MechJebModuleStageStats.cs(22,16): error CS0246: The type or namespace name `Stage' could not be found. Are you missing a using directive or an assembly reference?
MechJeb2/MechJebModuleStageStats.cs(23,16): error CS0246: The type or namespace name `Stage' could not be found. Are you missing a using directive or an assembly reference?

Am I missing some undocumented dependancy ?

**Comment by sarbian** [comment]
Make sure you use the newest makefile
https://github.com/MuMech/MechJeb2/blob/dev/Makefile

**Comment by chriscamacho** [comment]
Are you going to update the makefile in the "stable" branch?
