### ISSUE TITLE
Request: Additional options for Ascent Guidance

### ISSUE THREAD

**Issue by dewiniaid** [MuMech/MechJeb2#575]
It'd be handy to have the following two options added to Ascent Guidance:
- Ability to ascend directly to an elliptic orbit (e.g. 100x200).  Currently I cancel Ascent Guidance after the ascent phase and create a node in the maneuver planner instead, which means if I'm launching a craft I know to be stable I still have to pay attention to the entire alunch.
- Ability to time launches to launch into a specific LAN -- particularly for satellite contracts, but potentially useful for other situations e.g. building a GPS satellite constellation.

**Comment by dgies** [comment]
For #1 can't you use the Maneuver Node Planner and time it for some length of time by which you know circulization will have finished?  

Tell Ascent Autopilot to circularize at your desired periapsis.  Define node to raise apoapsis after a specific time, say 600s, 'Create and Execute', then enable the Ascent Autopilot and launch.

#2 See issue 102: https://github.com/MuMech/MechJeb2/issues/102

**Comment by dewiniaid** [comment]
#102 isn't entirely relevant, since when launching to a specific LAN there's no way to 'target' the orbit itself for launching to rendezvous.  (That said, the logic behind the implementation would be very similar -- it's essentially a rendezvous to a nonexistant target.)

**Comment by hoylemd** [comment]
I'd also really like to see this. I use mechjeb for my ascent, and it's tedious to time the launch by hand.

**Comment by lamont-granquist** [comment]
dup of #1061
