### ISSUE TITLE
Request: More options for Maneuver Planner inclination changes

### ISSUE THREAD

**Issue by dewiniaid** [MuMech/MechJeb2#576]
It'd be super handy if, when changing inclinations via the Maneuver Planner, the following were added as options for times:
- At the point requiring the least Delta-V.  (Or, simpler version, examining the requirements for creating at AN vs DN and choosing the cheaper of the two)
  - This should only consider places where the target inclination is actually possible to reach -- 0 degree inclination can only happen at AN/DN, for instance. 
- At the next ascending/descending node.  (If the craft will pass AN before DN, choose AN; otherwise choose DN).
- With new LAN <specify>
  - If I'm in an equatorial orbit and want an inclined orbit with a specific LAN (e.g. satellite contracts), burn normal at LAN or antinormal at LAN +/- 180.  (Satellite contracts...)

I frequently end up creating the node at AN, deleting it, and recreating at DN to see which is cheaper.  It's a bit easier now that I've added time to AN/DN to my orbital readout, but the added convenience would be nice.

**Comment by lamont-granquist** [comment]
"highest AN/DN" got added, as did burning to change LAN.
