### ISSUE TITLE
Request: Satellite separation -- or separation distance on rendezvous planner

### ISSUE THREAD

**Issue by dewiniaid** [MuMech/MechJeb2#578]
I've built several RT2 networks over time, which frequently involves a number of satellites within the same orbit with appropriate separation.  I've come up with a few of my own ways to do this (all somewhat tedious).. but there's also a forum guide that mentions some clever uses of MJ's rendezvous planner with some changes to when burns actually occur.

If the rendezvous planner could be altered to function as it does now, but assuming the target is a set amount of time behind/ahead in its orbit vs its actual location, it could be used for establishing satellite separation.  To this effect, I propose:
- Add an option to the rendezvous planner to offset the rendezvous by a certain fraction.  (Default fraction could be 1/1, negative fractions permitted)
- Rendezvous Planning then performs a rendezvous with a virtual 'target' that's located (target orbital period times fraction) time ahead of the actual target.

The result of this should result in the active vessel being in an orbit matching the target, but with a set degree of separation.  At 1/2 separation, the active vessel would reach Pe at the same time the target reaches Ap -- at 1/3 or 2/3 separation, 3 vessels would form the points of an equilateral triangle (assuming circular orbits), and so on.

**Comment by lamont-granquist** [comment]
#1065 adds this kind of feature, #1058 covers that this should be added to the rendezvous planner and extended and improved
