### ISSUE TITLE
Request: Turn Start Velocity Slider

### ISSUE THREAD

**Issue by GrayHD** [MuMech/MechJeb2#588]
This is a really minor request but it would be a nice little thing to have especially for players who don't realise you can edit this value (which I didn't for a few minutes). So as the title says the request is to add a slider to the "Turn start velocity" option in the Ascent Guidance feature. It's basically just to make sure all players realise you can change the value and it would just be a nice little ease of access thing. Would make changing the value a bit less tedious (even though it really isn't already). Anyway, you could just add it so it's basically the same as the "Turn start altitude" slider and from around 0-1000 m/s or whatever number's seem more reasonable. I know this really isn't very important but every little detail counts. :)

**Comment by sarbian** [comment]
Fixed in 4acc2ac740a6991e08cf91a8054aba14847cc2a5
