### ISSUE TITLE
Fairing mass not accounted for in VAB deltaV window

### ISSUE THREAD

**Issue by davidv1992** [MuMech/MechJeb2#595]
The deltaV window in the VAB does not take into account the mass of a fairing

To reconstruct:

Create craft with:
An FL-T400 fuel tank
Below that a LV-909 engine
An mechjeb 2 AR 202 case unit attached to the side of the FL-T400 fuel tank
An AE-FF1 aerstream protective shell without actual fairing on top.

Note deltaV
Note mass given by editor

Now edit fairing to create large (mass 2t) fairing and (if neccesary) fix staging order to put fairing in stage 0, engine in stage 1

Note that deltaV is unchanged in mechjeb window
Note that editor mass is higher

**Comment by sarbian** [comment]
Yes, it is a side effect of the hack I added to fix an other problem. That would not not be that bad if the stock fairing were not made of lead...
I ll see if I can do an other quick fix or if I should revert the whole code to a more stable version of the KER code.

**Comment by sarbian** [comment]
Fixed with 46b05b96e89d976ac00297169edb7aec6e67f0fc and 5a4b88906d5463904c17ac15e015dfcb39980795
