### ISSUE TITLE
Request: Auto-deploy fairings at specific atmospheric pressure

### ISSUE THREAD

**Issue by ErzengelLichtes** [MuMech/MechJeb2#596]
I'd like to ask that the Ascent Guidance have a checkbox like Auto-deploy Solar Panels that automatically deploys fairings at specific atmospheric pressures.
A simple implementation would include:
- Stop At Stage - Similar to Parachutes to prevent them fairings from being deployed if they're for use on other atmospheric bodies
- Atmospheric Pressure - Determines what pressure to deploy available fairings, default to something like 0.001

Mechjeb should then automatically disable the engines, deploy the fairings, then re-enable the engines after a few seconds. This would prevent the fairings from hitting the ship due to acceleration. 

A more interesting implementation would auto-calculate when the fairing's weight was more expensive than the difference in drag and perform the stop-deploy-start, but that would probably be difficult to implement, while selecting atmospheric pressure at least provides a way to handle this more automatically than setting "Limit Thrust: 0%", deploy, uncheck Limit Thrust when I see atmospheric pressure at a low enough level.

**Comment by BloodyRain2k** [comment]
We've reached the point where we'd more need something like a staging sequencer where we can setup certain actions at ascend / landing depending on certain conditions, like the fairing seperation, ditching the last booster stage before it won't deorbit anymore (PE < 10km) etc.

**Comment by lamont-granquist** [comment]
The basics of this request are done, the more complicated requests are likely overly complicated and unnecessary.
