### ISSUE TITLE
AR202 case sometimes in wrong location after loading craft

### ISSUE THREAD

**Issue by AtomicStryker** [MuMech/MechJeb2#597]
Using the latest dev build of MJ. In terms of savegame affecting mods, i am also using Kerbal Joint Reinforcement and Tweakscale.

I have reusable Booster Rockets with a 2.5m equipment storage near the top (not root part). Inside those is a tweak-scaled-down Rockomax fuel tank, and radially attached to it, 2 solar panels and the mechjeb ar202 case. Sometimes upon switching to such a craft, the ar202 case is loaded in a wrong location, such as outside the locked equipment compartment. Since it is still "attached" to the fuel tank elastically and attempting to go "back inside", it makes the craft trash and spin around, and when i open the locker doors, it pops inside and usually smashes the solar panels to bits.

Describing this i realize it is probably a tweakscale issue, but i never saw any part other than the ar202 case do this. Ah, for the record, the ar202 case is not the rocket controlling part, thats a probodyne elsewhere.

**Comment by futrtrubl** [comment]
It does sound like a tweakscale issue. It may be that the ar202 is one of the few things you radially attach to that tank.

**Comment by sarbian** [comment]
Yes, this is not a Mechjeb issue.
