### ISSUE TITLE
Request: Ascent guidance Inclination correction at circularization

### ISSUE THREAD

**Issue by marce155** [MuMech/MechJeb2#602]
Maybe through the new aero or my bad rocket design orbits after the circularization burn don’t have the exactly right inclination any more (say 1.4 or worse instead of 0).

I suggest that the circularization burn node takes into account inclination deviation (from the value enter in the ascent guidance window) which occurred during, well, ascent and corrects them with the circularization burn.

**Comment by BloodyRain2k** [comment]
Whenever the node can correct that depends entirely on where it ends up at.
If the node is at 1° N/S then you won't get below 1° inclination unless you spend amounts of dV that at best could be pulled off by Interstellar.

I'd say your rockets are just too instable during launch.

**Comment by pellinor0** [comment]
I did this in a KOS script and found it quite useful. The circularization is a very good moment to sneak in a small inclination correction. You usually can't reach the target plane exactly, but on average you will cut the error in half pretty much for free.

**Comment by sarbian** [comment]
The new code include improve the launch heading to lower the inclination error
