### ISSUE TITLE
With a specific craft, toggling autostage on (whether in utilities causes the rocket to launch immediately, same behavior when you engage ascent AP and have autostaging on

### ISSUE THREAD

**Issue by smjjames** [MuMech/MechJeb2#604]
Build 467

Excuse the long title. Anyways, as the title says, while I was trying to look into some other bug (not MJ related), I ran into a case of MJ just launching without the player actually hitting spacebar (or whatever it's bound to). However, when autostaging is off, it doesn't do that behavior. It does the rest of the ascent perfectly.

I actually haven't been having a problem with that behavior, I just hit it with that one craft.

Output log: http://sta.sh/01bcxdm8ymq2 (don't mind the explosions, that's just the boosters colliding with each other spectactularily, the main engine survives :D )

Craft file: http://sta.sh/0qbta7lud5v
Mods required for craft:
Dmagic orbital science
SCANsat
MJ and a MM config that applies it to all command parts
KJR

Steps to reproduce using these settings:
![screenshot1](https://cloud.githubusercontent.com/assets/11197436/7948847/bb280c2a-093c-11e5-8c5e-8357b9e10a6a.png)
1. load craft onto pad, set up AP, make sure autostaging is on
2. hit engage AP and off it goes

3.revert to pad.
4. This time make sure autostaging is off.
5. Hit engage AP, it waits that time.

Reproducible every time.

Also, one thing I've noticed is that with heavy wobbly rockets (a design problem rather than a MJ problem) MJ tends to panic and slam the launch button, but this one is rock steady, doesn't even sway noticeably.

Edit: New information from mikegarrison on the main thread:
"It's not the ascent AP that causes the problem for me. What happens is that when I have my ship sitting on the pad, if I turn on autostaging in the Utilities window, the ship launches immediately (no spacebar). "

I tested that method with the utilities window and it happens there as well for the same craft.

**Comment by BloodyRain2k** [comment]
From a first glance at the description and screen I can't see any issue at all, have tried altering the craft yet to see if anything makes it stop the auto launches? like adding clamps, removing the crew, etc.

I've had wobbly rockets in the past but I never had any auto launch without spacebar ever so far, first time hearing of this issue.

**Comment by smjjames** [comment]
It used to happen a whole bunch more way back in 0.90 and back in January at least, but after a couple of dev builds, and a main build or two, it completely disappeared. I very rarely see the problem crop up.

When I did have the problem a whole lot more, adding or removing clamps sometimes resolved the problem, occasionally it took a change in design. I didn't think about that at the time I posted up the bug report, but yeah I could look into that as it could be useful information for Sarbian.

**Comment by smjjames** [comment]
Another example. Lots of mods used in this one though, and thats a tweakscaled 10m engine and tanks btw.
![screenshot41](https://cloud.githubusercontent.com/assets/11197436/8133054/9ea43ed4-10da-11e5-8203-9ecff4989f8b.png)

**Comment by chriscamacho** [comment]
Have you tested this behaviour without MJ2 I'm sure auto launch happened if the seperators were too loaded (ie the stages above were too heavy) even without MJ but its a while since I tried it to be honest

**Comment by lamont-granquist** [comment]
This was caused by physics running early, particularly on reverts where the initial jolt causes the rocket to wobble and physics to start, and i'm pretty certain autostaging was fixed to account for this so it no longer happens.
