### ISSUE TITLE
Allow auto-staging only on Ascent, while having global auto-staging be set to off

### ISSUE THREAD

**Issue by Tallinu** [MuMech/MechJeb2#61]
I find this scenario rather irritating: I get to orbit, I may or may not do some manual maneuvers to rendezvous with something, and then I decouple the final launcher stage... and suddenly I'm hearing "click-click-click-click-click-..." as MechJeb triggers a series of stages in order to get to one that has engines activated. I don't _want_ those engines active yet because I may be about to perform a docking or something else and I don't want to accidentally throttle them up by hitting the wrong key. And I certainly don't want it decoupling anything! (Fortunately the engines come before the decouplers in this rocket.) But my only option to prevent this from happening is to disable auto-staging and then re-enable it for the next launch, which I generally forget to do because I'm used to MechJeb 1.9.8 where it wasn't a problem.

In my opinion, if auto-staging is to be a global setting, it shouldn't occur unless running an autopilot function which uses the main throttle. Alternatively, if people want it to happen while flying manually, then it should not be a global setting - instead we should be able to independently toggle it for each autopilot module, with a separate setting under thrust control for auto-staging during manual flight.

**Comment by lamont-granquist** [comment]
think this got done a long, long time ago.
