### ISSUE TITLE
Feature Request: Auto-activate ASAS 'Up' after auto-landing

### ISSUE THREAD

**Issue by macdjord** [MuMech/MechJeb2#611]
When I land, I often find myself waiting anxiously for the auto-land sequence to finish, then desperately mashing the ASAS 'up' button, trying to hit it before my rocket tips too far for the reaction wheels to deal with. I'd really like an option on the Landing Guidance system that would automatically set the ASAS mode to 'Up' when it terminates.

Alternately, a more general feature: Add some function which, when ASAS is in 'Auto' mode, lets you set which mode it will switch to as soon as control is released.

**Comment by chriscamacho** [comment]
https://github.com/MuMech/MechJeb2/issues/571

I'd prefer an easy way to abort to a translatron hover so I could pick a flat landing area....

**Comment by lamont-granquist** [comment]
dup of many similar requests and one aborted attempt to implement this, closing for #1052
