### ISSUE TITLE
Stage Start Mass display is messed up when engine drains fuel from higher stage

### ISSUE THREAD

**Issue by asazernik** [MuMech/MechJeb2#615]
When an engine drains fuel from a higher stage (for example, when a decoupler is set to have crossfeed enabled), the "start mass" indicated for the stage including the engine, and all stages below it, does not include the fuel in the upper stage. (The start mass for the upper stage correctly does not include the fuel, since it's assuming that the engine will consume all the fuel before staging.)

I come across this frequently when building multi-part ships where individual components have fuel tanks and an engine to rendezvous with the assembled ship, but then I jettison all but one engines (but *not* the fuel tanks!) when I want to take the whole big contraption somewhere.

Here's a screenshot:

![screenshot from 2015-06-06 15 19 33](https://cloud.githubusercontent.com/assets/1307640/8021707/7114a640-0c5f-11e5-9005-d66a362f4f8e.png)

Note the comparison to both KER and the builtin craft info's readout of the craft's size.

Attaching .craft file as soon as I figure out how.

**Comment by asazernik** [comment]
[Have a look](https://gist.github.com/asazernik/acede1c246f4733f6a4a)

**Comment by sarbian** [comment]
Thanks. I'll see what I can do today.

**Comment by sarbian** [comment]
Working in the last dev release
