### ISSUE TITLE
Shenenighans with changing the root part confuses MJ (at least temporarily as there is a way to refresh the whole thing)

### ISSUE THREAD

**Issue by smjjames** [MuMech/MechJeb2#618]
I also posted in the forum thread.

While building this and after doing some root part swapping, I noticed that the first stage had inexplictedly changed deltaV.
![screenshot3](https://cloud.githubusercontent.com/assets/11197436/8095074/1d26529e-0f80-11e5-8810-cb816e660288.png)

To make sure that it really did change, I remade the first stage as a new craft and yes the deltaV is different. Other than the positioning of some parts, the two are constructed identically.

![screenshot2](https://cloud.githubusercontent.com/assets/11197436/8095085/2eaf4106-0f80-11e5-85d7-6fde6b7e2fd2.png)

Reproduction steps (I'm doing this on a branchoff with just MJ, Karbonite and it's dependencies, KJR, CTT, Crowd Sourced Science, and exception detector):

1. Create a simple craft with two stages, both stages having a probe core, tank and engine. The stages don't need to be identical, though I suppose you could for testing purposes.

2. Change the root part to the second probe core.

3. Remove the stage above the decoupler and replace it (if you skip this step, it doesn't reproduce, I tried to skip the step).

4. Make the origional probe core the root part again and reset staging.

5. Detach and reattach the craft below the root core part and reattach, this resets it apparently.

**Comment by n0xiety** [comment]
Well this is one of the most common bug i encountered in the latest version of mechjeb. This happens to me every time i start building a rocket from bottom up. Changing the root part to any part that is in the last stage seems to ''fix'' the problem. Atleast we have a workaround for it.

**Comment by smjjames** [comment]
I generally build top down.

Anyways, put in somewhat more simplified steps, you probably don't really need my sheneinighans while trying to fix it as steps.

**Comment by sarbian** [comment]
Yes, MJ is not as smart as you are. If the root part is not in the last stage then it think you want to drop a large part of the ship. 
This is working as intended.

**Comment by lamont-granquist** [comment]
finally got sick of this problem enough to have fixed it in #1296
