### ISSUE TITLE
Bug: Mechjeb case exploding at spawn randomly.

### ISSUE THREAD

**Issue by n0xiety** [MuMech/MechJeb2#621]
When reverting to launch after explosion, mechjeb case isn't attached to the hull anymore. Returning to VAB and then relaunching seems to fix it. Strange bug indeed.

**Comment by smjjames** [comment]
I've had the same thing happen occasionally with the MKS planetary camera. I heard somewhere that it has something to do with the fact that the part is so light.

**Comment by n0xiety** [comment]
Oh yeah might really be the reason. There are times where i saw temperature bar over mechjeb right before explosion when the ship spawned. Maybe the new heating physics are derping at spawn and that moment of heat gain is actually effecting only mechjeb since it is the only part that has no mass?

**Comment by smjjames** [comment]
It actually has mass, it's just very, very, very light.

**Comment by chriscamacho** [comment]
Would it be a bad thing if it way weighed say 2kg ?

**Comment by smjjames** [comment]
I thought it actually weighed like ounces, but if you want to experiment with the weight, I'm sure sarbian would be happy to have the data there.

**Comment by futrtrubl** [comment]
This will probably be fixed in 1.03 when they incorporate skin heating from DR. I know DR uses a minimum thermal mass just for this sort of problem so I would assume stock will too.

**Comment by Aquilux** [comment]
Increasing the part's thermal mass may help fix some of these issues. I've encountered this issue a number of times, or something similar, where the case will occasionally explodes "due to overheating." I imagine it has something to do with floating point errors on the flux value, and a tiny thermal mass not being able to absorb the spikes in heat.

**Comment by n0xiety** [comment]
Truth is i love the tiny mass which enables me to put mechjeb on the smallest of probes without a performance hit. Tho i wouldn't mind it being 0.01 mass if that is going to fix the issue.

**Comment by smjjames** [comment]
Probably worth it to wait until 1.0.3 with it's skin based heating to see how that fixes the problem.

**Comment by Frarry** [comment]
I had craft randomly blowing up, so I installed Hot Spot. The MechJeb case was cycling through random temperatures, from very hot to very cold. Increasing the mass to 0.001 fixed the issue for me. I also made it "physics-less" and everything is working great again. This is on KSP 1.0.4, btw.

**Comment by Aquilux** [comment]
The stock barometer part has the same issue, though not bad enough to explode.

**Comment by sarbian** [comment]
Fixed with b6859751d507df1a03e06df609282218429b64d0 &    75b44448c73a30fec7a280f0793a34ea3f97fc92
