### ISSUE TITLE
MechJeb RO

### ISSUE THREAD

**Issue by qbert55ca** [MuMech/MechJeb2#623]
I've been using MJ since I started playing KSP and it has become a vital part of my time using KSP. Thank you for the hard work you have put into it.

With that said, I was very disappointed with the latest version so much so that I went back to an older version. I understand the some want realism to the game but that's the problem, this is a game not a SIM.

With the new version and the forced turn speeds and altitudes you ruin the essence of the game. I for one have spent many hours getting turn speeds and altitudes precise with different rockets and none of them use the forced 100ms in the latest MJ. 

I'm all for realism if that's the way you want to go but at least give the player the chance to make the decisions, "that's part of the game"

Thank you again for a wonderful program but please give the player the control to use it to his game.

qbert55ca

**Comment by sarbian** [comment]
Those options are and always were configurable.

**Comment by futrtrubl** [comment]
Just to be clear, turn off the auto turn in the ascent profile window and you have full control like always.

**Comment by qbert55ca** [comment]
Gentlemen. I guess I did not make myself very clear in my first message. I use the Ascent profile adjustment on a regular basis. The addition of the Velocity part of the equation in it's present form throws the ascent profile out of balance. For instance, to get the rocket to turn at 8.8km you must set the velocity to a higher number than it would be at that altitude, other wise it it turns when it hits the velocity that is set. Doing this then means you also need to further adjust the ascent profile for all other
planets and moon.

You could make it so that you turn by either "Altitude" OR "Velocity" which I believe would fix the present problem but having both in play seems to cause problems if say lifting from the moon with out further adjustment of the ascent profile.

**Comment by futrtrubl** [comment]
Trying to lift off from the Mun with a Kerbin ascent profile is something that will cause problems.
