### ISSUE TITLE
Landing prediction overshoots on bodies with an atmosphere

### ISSUE THREAD

**Issue by drasive** [MuMech/MechJeb2#629]
The landing prediction seems to consistently overshoot the expected landing position when landing on bodies with an atmosphere.
If, for example, I try to land at the KSC from a 75km 0° circular orbit I end up 30-70km short (to the left), because the expected landing position shifts quite a bit while I'm being slowed down by the atmosphere. Could it be the cause, that my ship is experiencing higher drag than anticipated if it is not orientated optimally?

Does anybody else have this problem, or am I maybe doing something incorrectly?

I should note that I observed this behavior using development build [#480](http://jenkins.mumech.com/job/MechJeb2/480/), not the current release version.

**Comment by drasive** [comment]
I should

**Comment by sirmackan** [comment]
I have this problem as well.

**Comment by lamont-granquist** [comment]
dup of #1052
