### ISSUE TITLE
Enable circularization burn before leaving atmosphere

### ISSUE THREAD

**Issue by drasive** [MuMech/MechJeb2#630]
The ascend guidance should detect when the circularization burn needs to be started before reaching the edge of the atmosphere.
Launching into a very low orbit (< 75km on Kerbin) may require doing so, in order to prevent the circularization node from being executed too late (which leads to a suborbital trajectory or a massive waste of Δv) .

It looks like such a detection was implemented [here](https://github.com/MuMech/MechJeb2/blob/master/MechJeb2/MechJebModuleAscentAutopilot.cs#L357-L363) some time ago, but was removed because it caused some false positives.

**Comment by lamont-granquist** [comment]
The better solution to this is to fly a profile which lofts the rocket less (which is more efficient due to less gravity losses as well), either PVG will solve this in #1061 or else it is unlikely to get implemented.
