### ISSUE TITLE
Add project solution

### ISSUE THREAD

**Issue by drasive** [MuMech/MechJeb2#631]
Would it be possible to add a MonoDevelop / Xamarin Studio/ .. solution file to the repository (e.g. .sln for Visual Studio), so not everybody has to create one themselves following the [wiki](https://github.com/MuMech/MechJeb2/wiki/Compiling-MechJeb-2)?

**Comment by sarbian** [comment]
I code on VS 2013. I will add a zip with a VS 2013 project in the next dev push I do. Loading that in MonoDevelop / Xamarin will be left to those who need it.
