### ISSUE TITLE
Cannot resolve Vector3Pair

### ISSUE THREAD

**Issue by bruchpilotxxl** [MuMech/MechJeb2#635]
I am trying to build MechJeb in VisualStudio, but I'm getting one error, which tells me that Vector3Pair could not be resolved. Am I using the wrong UnityEngine.dll?

**Comment by bruchpilotxxl** [comment]
Same error in MonoDevelop

**Comment by sarbian** [comment]
You need to add Assembly-CSharp-firstpass.dll to the project
