### ISSUE TITLE
Feature Request: Add "Limit Dynamic Pressure" for FAR

### ISSUE THREAD

**Issue by blnk2007** [MuMech/MechJeb2#636]
"Limit Terminal Velocity" does not work with FAR. Is there a way MechJeb could detect the dynamic pressure and keep velocity at a good rate for the amount of dynamic pressure? This would help mitigate rapid disassembly of separated stages. :)

**Comment by futrtrubl** [comment]
Limit terminal velocity does work with FAR, it's that the terminal velocity is much, much higher with FAR. Also if you are basing terminal velocity on the presence of mach or heating effects; don't. They have nothing to do with terminal velocity.

Having said that, _q_ limit would be nice.

**Comment by blnk2007** [comment]
Yes, that's what I was trying to say.

**Comment by pjwerneck** [comment]
I think this can be closed now, since Limit Q has been implemented.
