### ISSUE TITLE
Landing Autopilot off by thousands of km, even on atmo-less bodies

### ISSUE THREAD

**Issue by cmheisel** [MuMech/MechJeb2#638]
I've noticed that MechJeb 2.5.1.0-484 when using the landing auto-pilot is coming in thousands of km off from the target point, even on atmosphere-less bodies.

Here's some screenshots on a stock install with only MechJeb 2.5.1.0-484 and HyperEdit installed.

![screenshot0](https://cloud.githubusercontent.com/assets/34786/8502344/b31556d4-217c-11e5-911f-0459fcbac453.png)
![screenshot2](https://cloud.githubusercontent.com/assets/34786/8502346/b5c3d22a-217c-11e5-912a-3bb2ea60823c.png)

**Comment by futrtrubl** [comment]
Give reproduction steps. What body? What starting body? Etc. Try to use well lit screenshots.

**Comment by cmheisel** [comment]
Steps I took
* Built a lander: 
* Launch from KSC
* Hyperedit to the Mun at 40km
* Enter coordinates in the screenshot shown as the landing target
* Activate autopilot

Closing this, after my initial try above I couldn't reproduce it after time warping to get the landing site in the sun :-)

I'm seeing a similar issue when trying to land at KSC on Kerbin, always ending up several km off the landing point, I'll open a seperate issue on that.
