### ISSUE TITLE
Landing Guidance is keeps screwing itself up.

### ISSUE THREAD

**Issue by PVPplayerPro** [MuMech/MechJeb2#642]
So, 1.0's new aero model now means that, unlike before, the drag of a part depends which way it is facing, this is horrbile for MJ to work with simply because mechjeb keeps giving itself the wrong info* and trying to correct what isn't wrong.

Hypothetical situation(Not really, because it actually happened)

So let's say i'm in a 200KM X 200KM orbit, i enable landing guidance to do it's thing, it burns to de-orbit and all is well, until a inclination change is done midway down. 

   When mechjeb decides to change inclination because it is one goddamn nanometer off, it re-orients the craft, which of course, tells mechjeb to calculate the decent based on how the drag is predicted to be with the now-sideways craft. 

  When it gets that the craft is sideways, it turns back to retrograde to correct for the predicted drag change, but then mechjeb now sees the craft back to normal and decides not to correct because it doesn't need to. 

  THEN, it decides that it still needs to do the inclination change because it is the aforementioned nanometer off and turns sideways to do so, which triggers a never-ending loop of back and forth between retrograde and inclination change trying to re-adjust for 2 irrelevant things at once, until it all crashes down to kerbin.

Edit: here is what keeps going on when it turns sideways, triggering the whole mess..
http://i.imgur.com/JB8C18G.png

**Comment by smjjames** [comment]
Which MJ version are (or were) you using?

I've never seen the path prediction be that screwy before though.

The description sounds a bit like the behavior I observed here, except without the inclination change halfway down and the spiralling descent prediction: http://forum.kerbalspaceprogram.com/threads/124336-PART-1-0-2-Anatid-Robotics-MuMech-MechJeb-Autopilot-v2-5-1?p=2056038&viewfull=1#post2056038

**Comment by sarbian** [comment]
It seems you are under the assumption that you can open an issue full of anger and expect it to be looked at.

You are wrong.

**Comment by PVPplayerPro** [comment]
Lol i'm not angry, i'm just dead serious that this is annoying bug that never used to happen, and is being neglected like some modules of this mod

**Comment by smjjames** [comment]
If you want sarbian to be able to help you (and maybe take you a bit more seriously), post an output log. Also, try the latest version.
