### ISSUE TITLE
Smart A.S.S. / edu version

### ISSUE THREAD

**Issue by NotHonkyTonk** [MuMech/MechJeb2#644]
After using the mod since .19 I have never had an issue. However I have begun using Kerbal space program in a classroom setting with a group of middle school students, and with how I am teaching this mod is basically essential. My issue is the Smart A.S.S function, where I personally find the name funny, is not appropriate for a classroom. Especially if I want to get the rest of the museum to buy EDU and use it as well. I wouldn't want to ask you to change the name of what is a staple of mechjeb, but instead to release an optional mod to the mod that changes it. Or an EDU version that has the function renamed.
Thanks
-NotHonkyTonk

**Comment by sarbian** [comment]
Would "Smart A.C.S"  work ? I'll add an option and a ModuleManager patch to enable it easily.

**Comment by NotHonkyTonk** [comment]
That's perfect! Thanks for the quick response! Keep up the great modding

**Comment by sarbian** [comment]
Adding "eduMode = true" to the module will rename it to SmartACS.
 You can use this Module Manager patch to do it : https://github.com/MuMech/MechJeb2/blob/master/MechJebEdu.cfg
