### ISSUE TITLE
Issues with Landing Autopilot on Gilly and Pol

### ISSUE THREAD

**Issue by doubt72** [MuMech/MechJeb2#649]
Don't know if this affects any other bodies, but the landing autopilot goes haywire on Pol and Gilly.  I haven't tried landing on Bop yet, will soon (in maybe another day or four), but given that Minmus is smaller than Bop and landing works fine, I doubt it has the same problem.

This has been around a little while at least (I think I noticed it as far back as 2.5.1), but affects the latest dev version as well (I tested it in #498 tonight before making this bug report).

Symptoms:  The problem happens during final descent; the ship will just kind of spin around aimlessly while thrusting, apparently trying to do some sort of course adjustment; see attached image for an example.

Other things I noticed: the suicide burn and time to impact countdowns zero out (and the time to land goes negative before this happens).  Possibly also related, the target (and landing prediction) markers float well above the surface of Pol and especially Gilly in the orbit map view.  True altitude seems to continue to be accurate, don't have any issues taking over and doing a manual landing.

Image attached; can happily supply any further data if necessary.

Thanks!

![screenshot42](https://cloud.githubusercontent.com/assets/801243/8740395/19474d8e-2c06-11e5-9c6d-738846eaf70c.png)

**Comment by sarbian** [comment]
It is a problem with the code used by the landing AP to get the altitude while running its simulation. On Pol and Gilly the code report the wrong altitude and the ship is far above the ground just when it thinks it should touch the ground. I need to ask other modders who know the PQS system better what they think about that...
Also if you load a landed ship on Pol you should see it above the ground for 1 frame before the terrain change and you end up on the ground. I think this is related

**Comment by doubt72** [comment]
Yeah, I noticed that.  Not just that, I noticed that if you land near something that's already landed, it "floats" high above terrain for a while until you end up landing near it (possibly at the same altitude that the autoland gets confused, but not sure).  So there is definitely some in-engine weirdness going on here as well (making it difficult to fix).

**Comment by doubt72** [comment]
Another interesting data point: I've gotten the glitch to happen on Bop...  But not consistently.  Seems to be related to altitude.  Low altitude landings seem fine?

Doubt that's particularly useful; I guess this is at best something you can mitigate, the real problem clearly seems to be with the underlying game code.

I suppose if I could figure how to set up a dev env, I might poke at the code and see what could be done (I've been wondering how Unity integrates with plugins anyway and wanted to do something similar but much less ambitious on a future game.  Hot-loaded C# objects I guess?)  This particular bug's been annoying me enough in my attempt to set up refueling infrastructure in the Jool system (to conquer all the moons) that I may do it soon and do a PR if I can figure it out.

**Comment by smjjames** [comment]
I've reported the problems with Pol before, so, yeah.

I haven't had any problems with Bop, none to the degree that I got on Pol anyway and any problems that I do have are generally blameable on the very low gravity and the engines gymbal.

**Comment by doubt72** [comment]
Having done a lot of landings on Bop now (including setting up a base to mine ore/produce fuel and landing fuel shuttles there to refuel, exploring all the biomes, etc., plus a couple landings just to confirm the issue) I can pretty much confirm that it's only super-high altitude landings on Bop that are an issue (when you get near 20km or so, maybe).  I've never had an issue with anything lower.

**Comment by lamont-granquist** [comment]
closing as a dup of all the other landing autopilot bugs compiled under #1052
