### ISSUE TITLE
CKAN Dev repo is not updated on successful builds

### ISSUE THREAD

**Issue by bstpierr** [MuMech/MechJeb2#650]
The last commit to the CKAN-meta-dev repo for MechJeb2-dev is from 28 days ago: https://github.com/KSP-CKAN/CKAN-meta-dev/tree/MechJeb2-ci/MechJeb2-dev

However, Jenkins shows multiple successful builds since then: http://jenkins.mumech.com/job/MechJeb2/

This may be an issue with a Jenkins post-build script or netkan setup.

**Comment by hakan42** [comment]
It is with the setup of the CKAN jenkins. The jobs there are triggered fom sarbian's Jenkins, but the script to process the request got lost and needs to be rebuilt. For which I will find time one of those days :smiling_imp:

**Comment by LebedevRI** [comment]
Still an issue.
If only this could be fixed, please :)

**Comment by sarbian** [comment]
the current CKAN should include the newer dev repo
