### ISSUE TITLE
MJ and KER don't recognize Karbonite as a fuel.

### ISSUE THREAD

**Issue by smjjames** [MuMech/MechJeb2#653]
It may be more of a KER issue than a MJ issue, but yeah, both of them don't recognize karbonite as a fuel. Using build 500.

![screenshot141](https://cloud.githubusercontent.com/assets/11197436/8986287/5008171a-3690-11e5-81ee-c1dfae032adb.png)

**Comment by sarbian** [comment]
Works fine now.
