### ISSUE TITLE
Mechjeb mod hid the parts in the menu to build spacecrafts!

### ISSUE THREAD

**Issue by XenXD** [MuMech/MechJeb2#656]
My mode was Sandbox. Mechjeb was the first and only mod I inserted. But then, it hid all the parts for building a Spacecraft. Fix it! I am so loving the mod but the mod started to destroy the codes. I was using the latest KSP Version (1.0.4).
![mechjeb bug](https://cloud.githubusercontent.com/assets/13748082/9197544/9928a4f6-4067-11e5-9e77-2fd634853dfd.png)

**Comment by sarbian** [comment]
I can't do anything without a log.

**Comment by XenXD** [comment]
sarbian, what do you mean?

**Comment by sarbian** [comment]
I don't have that at all. I can't fix it if I can't duplicate it or at least read a log where it happened.
So duplicate the bug and send me the KSP log so I can fix the problem.

**Comment by XenXD** [comment]
I am now closing this because I found the solution. I uninstalled and installed both KSP and the mod.
