### ISSUE TITLE
[Request] Better Max Q limiter

### ISSUE THREAD

**Issue by yaus** [MuMech/MechJeb2#660]
It is great for mechjeb have new feature for limiting throttle.
But it work not well, it always cut the engine reach MaxQ.
It is better to do this.
![image](https://cloud.githubusercontent.com/assets/7882074/9423545/aae77e38-48fa-11e5-9068-36f0b010067f.png)

**Comment by sarbian** [comment]
You may have missed the "Keep limited throttle over" / "Lower throttle limit" option I added in the same patch.
