### ISSUE TITLE
Mechjeb has no throttle control

### ISSUE THREAD

**Issue by molsen23** [MuMech/MechJeb2#673]
My apologies if this has been asked somewhere, but I couldn't find it. After upgrading to 1.0.4 on a fresh install and installing a bunch of mods I realized that MJ has no control over the throttle. It wouldn't down throttle to prevent overheats or to maintain a below terminal velocity ascent. I could alter the throttle values manually by checking "Limit Throttle To" and entering a %. It is extremely difficult to fly using that as my only source of throttle control. Once I realized there were issues, I created another fresh install and installed only mechjeb with vanilla and still the same issues. Maneuver nodes still provide throttle control, just not on ascent. 

Weirdly, It only worked one time when KSP bugged on load and turned a TWR of 1.42 to 100.42. Due to my computer being a number of years old, I only get about 5-6 frames per second- so flying with Mechjeb is the only way to make the game playable for me. I've been playing since .23, and this it the first time I've played since it went 1.0, so trying to learn the new physics system while flying manually with 5-6 fps is pissing me off. I'm hoping we can find a solution. Thanks!

I'm on a mac btw.

**Comment by sarbian** [comment]
Try with the dev version : https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/ and tell me if it is any better. 
I'll try to release a new official release soon

**Comment by sebastian-tschen** [comment]
Possibly I have the same issue, although mechjeb has no throttle control whatsoever for me. Neither ascent nor maneuver nodes. "Limit Throttle To" doesn't seem to work either.

I use KSP 1.0.4 on a Mac and the dev version you linked in this post.

**Comment by sebastian-tschen** [comment]
It now works. I guess I just didn't have the corresponding feature unlocked via tech tree.

Is there some place where I can find a description of which functions are unlocked at which tech?
