### ISSUE TITLE
Unable to use MechJeb2 (2.5.4.0-518)

### ISSUE THREAD

**Issue by omegaprime02** [MuMech/MechJeb2#681]
I've been having issues with getting MechJeb2 version 2.5.4.0-518 (The latest dev build at this time) to run, all of the parts are in place, however the actual scripts are not running, at line 1936 of the log that the game generated it states:

AssemblyLoader: Exception loading 'MechJeb2': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.

I'm not sure if that's where the issue is, but this is after a clean instal with this being the only mod running, I did try and instal a toolbar mod because I've seen it be a potential fix but I have removed it as completely as I can.  I ran the game with my antivirus disabled (and my computer in airplane mode because I'm paranoid) in both Science and Sandbox.

I've pushed the log up to my Google Drive, the link is: https://drive.google.com/file/d/0B55mvClCzUo7T2VLamo3d2NwZDg/view?usp=sharing

**Comment by sarbian** [comment]
You are running KSP inside your steam install in "C:\Program Files (x86)". On some windows anti virus and/or the integrated windows security prevents the loading of mods dll.
You have to move your install outside C:\Program Files (x86). Steam allow you to have the game in other directories ( Steam => Settings => Download => "Steam library folders" button at the top). Add a folder like C:\Games or whatever you like and re-install KSP (make sure to select the new directory in the steam install dialog). You may be able to prevent re-downloading the whole game by moving it in the new dir before re installing it.

**Comment by omegaprime02** [comment]
This has corrected my issue completely, I believe that this is due to the integrated Windows security built into Windows 10, if that's any help.
