### ISSUE TITLE
Delta V Stats are not showing up in-flight... Only in the VAB/SPH (New Update fixed this)

### ISSUE THREAD

**Issue by CookieGamers** [MuMech/MechJeb2#684]
**KSP:** 1.0.5 Windows 32BIT

**Problem:** While in flight, the delta V stats will not show up in the delta v tab. It does show the numbers in the VAB/SPH.

**Mods installed:**
MechJeb 2.5.3

**Reproduction steps:** Make any rocket with mechjeb attatched, look at the delta v stats in the VAB, launch, look at the delta v stats while flying

**Log:**
https://www.sendspace.com/file/iwc5up

**Comment by sarbian** [comment]
Sorry I missed that issue and the log that was with it. From the description you were running KSP build 1024 instead of the 1028 build that was released a few days later.
