### ISSUE TITLE
Ascent guidance unable to launch to target

### ISSUE THREAD

**Issue by tommypenner** [MuMech/MechJeb2#685]
KSP: 1.0.5, Windows 8.1 64-bit, Steam installed
MechJeb DEV Release 2.5.4.0-512 (installed via CKAN)
Problem: Ascent guidance unable to launch to target
Mods installed:
- CKAN file here: http://1drv.ms/1MOK1d2
 - Chatterer
 - Editor Extensions
 - Kerbal Alarm Clock
 - Kerbal Attachment System
 - Kerbal Engineer Redux
 - Kerbal Inventory System
 - MechJeb 2 DEV RELEASE
 - Menu Stabilizer
 - Module Manager
 - Planet Shine
 - Planet Shine - Default configuration
 - Surface Mounted Lights
 - Trajectories

Reproduction steps:
- Build a craft, send to launchpad
- Open MechJeb menu, open ascent guidance
- Open map view, select orbital target
- Return to launchpad view
- Expected: Ascent Guidance is ready to rendezvous
- Observed: Ascent Guidance does not detect orbital target, copy still reads "Select target for rendezvous"

Log:
http://1drv.ms/20Tfi93

Notes:
Maybe related to the user report here - http://forum.kerbalspaceprogram.com/threads/124336-PART-1-0-4-Anatid-Robotics-MuMech-MechJeb-Autopilot-v2-5-3-%28July-6th%29-1-0-5-in-there-too?p=2293524&viewfull=1#post2293524

Thanks!

**Comment by smjjames** [comment]
Theres a big difference between the post you linked and your report, the post you linked was using 523 (the latest dev build is now 524), you're 12 versions behind.

**Comment by tommypenner** [comment]
@smjjames Yeah, I just noticed that. Installed 524 and I'm still running into the issue, with some difference:

- Ascent Guidance *does* detect the orbital target, but it does not detect the target's inclination or altitude data. Those fields return values of 0 each.

**Comment by tommypenner** [comment]
I've been playing with 524 installed for awhile now and haven't had any issues with ascent guidance since then. Closing this out.
