### ISSUE TITLE
The ship is not steering in Ascent Guidance

### ISSUE THREAD

**Issue by howkong** [MuMech/MechJeb2#686]
When using the Ascent Guidance, the throttle control works perfectly, but the steering is completely dead.
http://i.imgur.com/OFK9wEA.png
As is can be seen above, the ship is already drifting off course, but the steering is still dead.
https://www.dropbox.com/s/czc6y6h215...t_log.zip?dl=0
This is the log file.

**Comment by Viruzzz** [comment]
I can confirm, today I had tested and no steering as well .... I use the last dev build.

**Comment by sarbian** [comment]
The first post is on 1.0.5 with a MJ version for 1.0.4. 
The second you don't provide any log.
