### ISSUE TITLE
Mechjeb doesn't work properly

### ISSUE THREAD

**Issue by allconan** [MuMech/MechJeb2#687]
Test releases for 1.0.5 Porblem
When using the Ascent Guidance, all my old rockets, which can launch in the 1.0.4, broken during the beginning of turning in the ascent. They just like falling down and point to the groung.
Also in the Ascent Guidance, it cannot launch into the same plane at specific time to docking

**Comment by pikachu01** [comment]
Can you list the mods that you are using? Probably will narrow down the cause.
