### ISSUE TITLE
Feature suggestion: On Land Surf Up

### ISSUE THREAD

**Issue by frango9000** [MuMech/MechJeb2#688]
A landing option would be useful (at least to me) ill explain.

when mechjeb landing guidance is done (on landing) it disables SmartASS controls and this leads to a delay in either manualy balancing or changing tab on SmartASS window and setting Surf UP, this is obviously more intense in light gravity lightly sloply terrain, and this delay endagers Jebediah´s safe return home. so an option on landing guidance window activating SmartASS UP on touchdown instead of totally shutting down MechJeb control would be hoighly apreciated.

**Comment by lamont-granquist** [comment]
closing in favor of #1052
