### ISSUE TITLE
Warp helper to phase angle (MJ dev 524 / KSP 1.0.5)

### ISSUE THREAD

**Issue by seyss** [MuMech/MechJeb2#692]
It won't work properly... it'll reduce the time warp way before reaching the desired value.

**Comment by seyss** [comment]
any feedback?

**Comment by robot256** [comment]
Please try to duplicate this on the latest dev version (571 right now) (https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/).  If it still occurs, please upload the log file and describe the exact steps to reproduce it.
