### ISSUE TITLE
Ascent guidance never fires jets

### ISSUE THREAD

**Issue by NanoCats** [MuMech/MechJeb2#694]
Hi! If i try to use Ascent guidance to get in orbit, It will create a burn and then never actually engage the jets when it's T-0 Secconds. Even if i wait the craft just crashes eventually

**Comment by robot256** [comment]
I have found that after the ascent burn completes, and the guidance system switches to execute the circularization maneuver, it stops auto-staging.  If your craft gets to the edge of the atmosphere with an empty tank, you will need to manually start the next stage for Mechjeb to be able to do the circularization burn.

Also, you say "jets", but do you mean rocket engines instead?  Jet engines do not work in space :D

**Comment by sarbian** [comment]
This works fine here. Make sure you are on build 1028 of KSP (look in the lower right corner of the start menu). If you still have this bug with 1028 then you will have to provide some log.
