### ISSUE TITLE
 [Feature] Mechjeb should enable RCS if no reaction wheels present

### ISSUE THREAD

**Issue by tfischer4765** [MuMech/MechJeb2#695]
I noticed this issue when I was fooling around with FASA. Some of the old capsules don't have reaction wheels. I noticed this interesting fact only when I realized that Mechjeb wouldn't point the ship towards the circularisation burn node. 

However, rare this instance may be, but hardly unheard of. I think it would be desirable if Mechjeb were prepared for this contingency. I therefore request the following feature:

When ordered to execute a maneuver node and no currently active reaction wheels exist on the vessel, Mechjeb should activate RCS.

**Comment by sarbian** [comment]
The Attitude Adjustment has a "RCS auto mode" that activate RCS when needed.
