### ISSUE TITLE
Assent Guidance

### ISSUE THREAD

**Issue by Atman6688** [MuMech/MechJeb2#696]
Hi,
I love Mechanical Jeb!  But I'm having some issues right now with assent guidence, and I think everything else.  I started using RO and RSS, and I'm not sure if the problems started with that, or upgrading to 1.0.5, both of which I did at about the same time.  Does it work with Realism Overhaul and Real Solar System?  When I try to make an assent and it starts to warp, waiting for the correct launch window to launch into the plane of the target, it will do one of two things typically.  Either it starts staging prematurely (getting rid of launch towers, and generally screwing things up, etc) which seems to ruin the launch, or it will launch on a crazy path low to the horizon (maybe 15 degrees) and the craft blows apart do to aerodynamic forces.  I will get a safe launch 1 in 15 times, so it does work occasionally.  

If I make it to orbit which is rare, and I try to use maneuver planner it will plan the node, and execute early which will plow me back into the atmosphere and to certain doom.  The craft has plenty of TWR (launches at 1.7, stages to about the same).  I'm positive it's not a lack of power that's giving me trouble.  It also doesn't deal with ullage, which is fine, but it would be nice if it handled that.  But that's just on the wishlist.  

Please let me know if you need anything else from me.  I'm anxious to provide it if it helps.  

Thanks!
Atman

**Comment by robot256** [comment]
Based on other reports like this, I believe the relevant questions are:
Does it happens when you are not "launching into plane of target"?  Does it happen when you are launching to rendezvous with a target?
Does it happen regardless of the craft design?
Are you running 64-bit KSP?
What is the complete list of mods you are using?  Are they all up to date?  
Can you replicate this behavior on a stock 32-bit installation?
You can also post the Mechjeb log file from a failed attempt, and the ship file and persistents file used to replicate it.

**Comment by robot256** [comment]
Forgot to add: What version of Mechjeb are you using?  Can you try to replicate the problem with the latest dev build from Jenkins?

**Comment by Atman6688** [comment]
Hey thanks for getting back to me!  I won’t be able to play again for a few days – after that I’ll start doing some testing, and see if I can get you better information on when exactly this is happening.  Below is a list of the mods I’m running.  I’m currently using 32 bit KSP, although I tried to switch to 64 bit last night (unsuccessfully).  I’m still interested in switching, and will pursue that as well.  I was starting to wonder if I’m maxing out my memory in 32 bit KSP, and that’s what is causing the problems with Mech Jeb.  

Anyway, thanks so much for your response.  I wasn’t sure if Mech Jeb was broken after 1.0.5, or broken in RO and RSS, or if it was just broken for me.  It sounds like it’s working for most people, is that correct?    Even in RO and RSS?

To answer your questions below:

It is happening when ‘launching into the plane of the target’ and launching to rendezvous.
I’ve only tried two different craft so far – I will continue testing as soon as I can.
All mods are installed and updated via CKAN.  
When I previously was running stock 32 bit KSP 1.0.5 I didn’t have any issues with Mech Jeb.  I installed a stock 32 bit KSP 1.0.5 last night, and I’ll give that a go as soon as I can.  
Mech Jeb version is 2.5.5.0 – why doesn’t this show up on the KSP add on version checker?  See below

KSP: 1.0.5 (Win32) - Unity: 4.6.4f1 - OS: Windows 7 Service Pack 1 (6.1.7601) 64bit
Advanced Jet Engine - 2.5.4
Community Resource Pack - 0.4.8
Ferram Aerospace Research - 0.15.5.4
Interstellar Fuel Switch - 1.18
Kerbal Joint Reinforcement - 3.1.4
KSP-AVC Plugin - 1.1.5
ModularFlightIntegrator - 1.1.2
Kerbal Planetary Base Systems - 0.2.9
Procedural Parts - 1.1.11
RealChute - 1.3.2.6
RealismOverhaul - 10.7.3
RealSolarSystem - 10.4.1
SolverEngines - 1.14
TAC Life Support - 0.11.2.1
TweakScale - 2.2.6

**Comment by Atman6688** [comment]
I'm starting to think the issue is not with Mech Jeb, and more with the rocket design I was using.  Sorry to bother you with this.  The center of lift on the rocket was a fair amount forward of the center of mass and making the rocket unstable.  For some reason it was still manually controllable, which seems odd.  I designed a new rocket, and I'm not having with Mech Jeb on this one. Thanks for your help!

**Comment by robot256** [comment]
Mechjeb will in fact malfunction if the center of thrust is above the center of mass.  That's a very different dynamic situation than a typical stacked rocket.  You can still control them with Mechjeb if you disable your engine gimbals and rely on reaction wheels or RCS thrusters.  This is what I had to do when making a skycrane, for example.

The "Launch into plane of target" feature, though, has in fact been having an overhaul.  In the latest dev version, it requires to do a test launch and revert so it can see how far the plane drifts during ascent.  I find that too annoying in most cases, so now I just eyeball the plane I want and modify the circularization burn to correct for it.
