### ISSUE TITLE
Suggestion: SmartASS option for relative wind vector

### ISSUE THREAD

**Issue by Rodg88** [MuMech/MechJeb2#699]
Basically the idea would be to have an option in SmartASS to hold retrograde to wind speed, to keep a heat shield directly in front of the ship for steep re-entry. I've just noticed sometimes holding orbital or surface retrograde will be slightly off center, and often turning off SAS will let the drag align the ship to a 0° angle of attack. But if there's an option to get SmartASS to hold a 0° AoA it would be more reliable, and good for ships which aren't as stable in re-entry.

Or is this already possible, and I just don't know how to use it? lol

**Comment by hoylemd** [comment]
I think that would just be retrograde to surface vector, given that weather isn't really a thing yet.  Sounds very possible to me.

**Comment by sarbian** [comment]
Yes, it is the "SVEL-" button in the SURF tab.
