### ISSUE TITLE
MechJeb Overcontrol Issue

### ISSUE THREAD

**Issue by xATHEISTxDEITYx** [MuMech/MechJeb2#700]
Currently been designing and experimenting with SSTO spaceplanes, but anytime I use Smart A.S.S. or any other Mechjeb Maneuvering system, I have a severe overcontrol issue to the point it will overcorrect into chaos. Stock SAS seems to behave normally and correctly, without overcontrol. Setting nodes with MechJeb, then using Stock SAS to align also has no overcontrol issues. I have made sure that Smart RCS is not in overdrive, and all other control functions are at standard values. Overcontrol issue is apparent when using RCS and using torsion attitude controllers.

Current mod list:
AB LAunchers
AIES Aerospace
B9 Aerospace
DMagic Orbital Science
Firespitter
JSI
KAS
KIS
MagicSmokeIndustries
MechJeb2
MRS
Near Future
OPM
OPT 1.7
Orbital Survey Plus
Planetary Base, Inc. 
SCANsat
SpaceY
Station Science
TAC Fuel Balancer
Tweakable Everything
TweakScale
Virgin Kalactic
ZG-27 Fuel Synthesizers

**Comment by BloodyRain2k** [comment]
You could try my PID settings if you want, I build pretty much only bigger rockets and it works good enough for me, if I give it some control surfaces as help atleast.

Tf 0.1 / 0.75
Kd 0.4
Kp 2
Ki 16
Deadband 0.0001
Ang Velocity 25

**Comment by xATHEISTxDEITYx** [comment]
Thanks, but the tweaks you suggested had no notable effect on the overcontrol issue. I have removed Tweakable Everything. I have a feeling that may be screwing with the mechjeb calculations.

**Comment by xATHEISTxDEITYx** [comment]
My feelings were validated. Tweakable Everything was causing some sort of issue with MechJeb. If anyone knows why or how, I'd love to know. Otherwise, this issue has been resolved
