### ISSUE TITLE
Allow tuning attitude PID controller per stage

### ISSUE THREAD

**Issue by chrisforbes** [MuMech/MechJeb2#713]
I often have to fiddle with the attitude controller's coefficients to get rid of unwanted shimmy. These vary by stage. It would be nice (if fairly niche) to be able to have multiple sets of coefficients, easily loaded/saved, and ideally automatically switched on staging.

**Comment by lamont-granquist** [comment]
With the HybridController there's likely a lot less need for this, and this would be a pile of complexity and UX/UI work.
