### ISSUE TITLE
Blue screen of death...ish

### ISSUE THREAD

**Issue by FlumpMC** [MuMech/MechJeb2#714]
Whenever I go into the VAB and a rocket, with Mech Jeb on it,
 is already loaded (like if I revert flight to VAB), all I can see is blue inside the building.
![20160405201212_1](https://cloud.githubusercontent.com/assets/18296928/14302035/b61be636-fb6a-11e5-8b5e-524c08afcabf.jpg)
I can still see all the buttons, so I can exit. In order to get rid of the blue, I have to quit to the main menu and go back in. If I enter the VAB and there isn't a Mech Jeb ship already loaded, I can then load one and it works just fine.
If anyone has a solution to the problem, I'd give you an internet hug or something...

**Comment by sarbian** [comment]
I missed that one but without a log there is not much I can do... If you still get it re-open and ling to a log.
