### ISSUE TITLE
Camera bug

### ISSUE THREAD

**Issue by FireFlame74** [MuMech/MechJeb2#718]
When you hover over the mechjeb gui list or any other mechjeb window the camera will follow the rotation of the current vessel if it is rotating. Moving the mouse out of the gui resets the camera to its initial position.

**Comment by mikemill** [comment]
Just wanted to confirm that I get the same issue.  Also happens if I tab away from the game regardless of where the cursor in game is.

**Comment by sarbian** [comment]
This issue was fixed in the dev builds here d785d6b4c791cd2397634c06e4e042760b55bd71.
I can't release a new official yet since the bug with the orbit calls are still there. So switch to the dev build for now
