### ISSUE TITLE
Monuver node burn starts at wrong time

### ISSUE THREAD

**Issue by Senaurus** [MuMech/MechJeb2#719]
After release of KSP 1.1.0.1228 on 04/19 the MechJeb sopped subtracting half burn time from the time to node. So, now it srats to burn exactly when ship reaches the burn node. This results in wrong final orbit.

This worked on previous version of 1.1. 

In the log file at the end

there are multiple exceptions that states:
 Method not found: 'IPartMassModifier.GetModuleMass'
 Look in the log file that I attached for more detail.
[KSPLog.txt](https://github.com/MuMech/MechJeb2/files/230121/KSPLog.txt)

**Comment by sarbian** [comment]
"MechJeb2 v2.5.1.0 / vDev #572 "

We are at build #580. The error you have in the log was fixed a week ago.

**Comment by Sinomen** [comment]
MJ Dev #882: Execution of a node starts at exactly 50% burn time instead of 0. 
In general, burn times start a bit late, old issue, but this is new.
