### ISSUE TITLE
Mechjeb Pod 2 bug

### ISSUE THREAD

**Issue by DJBen** [MuMech/MechJeb2#720]
It is immediately exerted a rediculous acceleration whenever I launch it. Or it explodes the ship it is attached to whenever I switch control to a ship that has jeb pod 2 attached.

**Comment by Rhadamanthos** [comment]
I'm having a similar issue, but I've reduced it even further - I have a rocket on the launchpad in a fairing (2.5m) with a MechJeb 2 pod on top. I deploy the fairing, and the massive acceleration DJBen is describing occurs - it seems to be at a right angle to the rocket. Here's some logs... all they show is that a "structural failure" occurs though. The subsequent explosions are after the event.
[KSP.txt](https://github.com/MuMech/MechJeb2/files/232785/KSP.txt)
[output_log.txt](https://github.com/MuMech/MechJeb2/files/232786/output_log.txt)

**Comment by sarbian** [comment]
Yes, as mentioned in the thread the pod is broken and I can,'t do anything about it since I don't have the model.
