### ISSUE TITLE
no GUI

### ISSUE THREAD

**Issue by Isenderen** [MuMech/MechJeb2#721]
In the new 1.1 update of ksp the GUI for mechjeb isn't coming up. Its really annoying since i rely on this mod to get geo stationary comssats into orbit. please fix this asap.

**Comment by sarbian** [comment]
1) You assume that I posted a version that does not work and  did not test at all.
2) You provide nothing to help me diagnose your problem

**Comment by Isenderen** [comment]
1) Well there's no gui coming up. And no, I didn't assume that.
2) I'll put a screenshot of my mods up when I get up in the morning. I just forgot to.
3) don't be so hostile. I'm just trying to let you know of a problem.

**Comment by Ruedii** [comment]
OK, here's how you need to provide enough help for this to be a valid bug report:
You need to provide the following information:
1.  Your system (OS and KSP Version first) considering it's a GUI issue, you should add Video Chip, and Video driver version.
2.  The version of Mechjeb you are using.
3.  A full list of other mods.
4.  If any errors appeared in the logs, please provide those as well.
