### ISSUE TITLE
No GUI

### ISSUE THREAD

**Issue by Isenderen** [MuMech/MechJeb2#723]
Ok, im having an issue in the dev release 2.5.7.0 where the gui is not coming up when im flying a ship with the ar202 on it. Also when im in the VAB the mechjeb icon pops up on the bottom part of the screen where it should be, but its not functional.

Currently im running windows 10 and KSP 1.1 and as said above im using Mechjeb Dev release 2.5.7.0. I'm also using a Nvidia geforce GTX 960m with the version 364.72 Geforce game ready driver.

Heres a list of my mods: (any outdated ones are because they havent come out with updated versions yet that i can find)
B9 Animation Modules - 1.0
B9 Part Switch - 1.0.1
B9 Aerospace - 6.0
Custom Asteroids - 1.2
RasterPropMonitor - 0.25
Kerbal Engineer Redux - 1.1.0.2
KineTechAnimation - 1.1
KSP-AVC Plugin - 1.1.6.1
Docking Port Alignment Indicator - 6.2
RemoteTech - 1.6.11
ResGen - 0.28.1
SpaceY Lifters - 1.12.1
Kerbal Alarm Clock - 3.5

The ship in the pic has an AR202 under the fairing but as you can see there is no button on the upper right corner to bring up the MJ GUI.
![kerbal space program 4_23_2016 1_05_32 pm](https://cloud.githubusercontent.com/assets/18625097/14763989/22e4ed3e-0954-11e6-8cb1-d229d2613812.png)

**Comment by sarbian** [comment]
I will need a log.

**Comment by Isenderen** [comment]
What do you mean by log? Sorry if it's annoying, but I'm new to the modding world so I don't know all the terms and what to do in reporting things.

**Comment by sarbian** [comment]
In KSP directory you have a file named "KSP.log". So launch the game, load your ship that should have the MJ window, then close the game and put the KSP.log file somewhere I can look at it (like dropbox)

**Comment by Isenderen** [comment]
Ok, I'll do that first thing tomorrow morning since it's about 1 my time.

**Comment by Isenderen** [comment]
heres the output log file. I dont know where to find the ksp.log file though.
[output_log.txt](https://github.com/MuMech/MechJeb2/files/233647/output_log.txt)

**Comment by rsbeaulieu** [comment]
I have a similar mix of mods:
```
...
System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.

KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null:
TextureReplacer, Version=2.4.12.37647, Culture=neutral, PublicKeyToken=null: 
SmokeScreen, Version=2.6.13.0, Culture=neutral, PublicKeyToken=null: 
RCSBuildAid, Version=0.7.7.37759, Culture=neutral, PublicKeyToken=null: 
PlanetarySurfaceStructures, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 
KSPAPIExtensions, Version=1.7.5.0, Culture=neutral, PublicKeyToken=null: 
InfernalRobotics, Version=0.21.3.0, Culture=neutral, PublicKeyToken=null: 
RasterPropMonitor, Version=0.17.0.0, Culture=neutral, PublicKeyToken=null: 
Firespitter, Version=7.1.5790.33347, Culture=neutral, PublicKeyToken=null: 
Geometry, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 
Clouds, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 
OverlayMgr, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 
CrossFeedEnabler, Version=0.3.5609.39332, Culture=neutral, PublicKeyToken=null: 
B9PartSwitch, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null: 
USITools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 
DynamicTanks, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 

...
Then we have the bit where we begin to throw the exception:
[LOG 14:16:47.206] [MechJeb2] Loading Mechjeb Dev #580 Sarbian
[LOG 14:16:47.220] ManeuverPlanner initialization: found 17 maneuvers
[ERR 14:16:47.246] MechJeb module MechJebModuleMenu threw an exception in OnLoad: System.InvalidOperationException: Operation is not valid due to the current state of the object
  at System.Linq.Enumerable.Single[Type] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback) [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.SingleOrDefault[Type] (IEnumerable`1 source, System.Func`2 predicate) [0x00000] in <filename unknown>:0 
  at MuMech.ToolbarTypes.getType (System.String name) [0x00000] in <filename unknown>:0 
  at MuMech.ToolbarManager.get_Instance () [0x00000] in <filename unknown>:0 
  at MuMech.ToolbarManager.get_ToolbarAvailable () [0x00000] in <filename unknown>:0 
  at MuMech.MechJebModuleMenu.ClearButtons () [0x00000] in <filename unknown>:0 
  at MuMech.MechJebModuleMenu.OnLoad (.ConfigNode local, .ConfigNode type, .ConfigNode global) [0x00000] in <filename unknown>:0 
  at MuMech.MechJebCore.OnLoad (.ConfigNode sfsNode) [0x00000] in <filename unknown>:0
```

Attached is the Full Log:  
[KSP_log_noSmartASSWindow.zip](https://github.com/MuMech/MechJeb2/files/233663/KSP_log_noSmartASSWindow.zip)

**Comment by rsbeaulieu** [comment]
I thought I had all latest mods @Isenderen but if you did what I did with the new v1.1 you went online to get some mods and possibly acquired an old toolbar version. In my case I had a toolbar version of 1.0.4 named aaa_Toolbar.dll in my .\GameData\000_Toolbar\ folder.  The version of this particular mod is at 1.7.11 which I am sure better matches with what MechJeb is expecting to use.

**Comment by Isenderen** [comment]
I don't have a GameData/000_Toolbar folder.

**Comment by Isenderen** [comment]
Update-
i have since updated to KSP 1.1.2 and have updated all of my mods except for firespitter which is 0.0.1 versions out of date. The problem is still there and heres an updated output log file. 
[Uploading output_log.txt…]()
