### ISSUE TITLE
MJ fails to calculate dV of vessel with external fuel tank jettisoned before engine ignition

### ISSUE THREAD

**Issue by cpcallen** [MuMech/MechJeb2#727]
This (slightly nonsensical, but perfectly valid) craft causes MechJeb's dV calculation to crash with `Exception in MechJebModuleStageStats.RunSimulation():   at MuMech.FuelFlowSimulation.SimulateStage (Single throttle, Double staticPressure, Double atmDensity, Double machNumber)` (note blank per-stage dV display):

![screenshot323](https://cloud.githubusercontent.com/assets/5603958/14793759/ad594b66-0b18-11e6-8c41-63d6e61dd400.png)

Note that removing the fuel hose will cause the error to go away - as will adding an engine to the lower tank.

Craft file / log file:
[MJ Bug 1.craft.zip](https://github.com/MuMech/MechJeb2/files/235100/MJ.Bug.1.craft.zip)
[KSP.log.txt](https://github.com/MuMech/MechJeb2/files/235103/KSP.log.txt)

**Comment by sarbian** [comment]
Thanks for the two simple test case. I will have a look this week.
