### ISSUE TITLE
Landing guidance problem after 575 build

### ISSUE THREAD

**Issue by reapergameover** [MuMech/MechJeb2#734]
Hi,

Everything started when version MechJeb2-2.5.6.0-575 came out (MechJeb2-2.5.6.0-574 was ok).

The problem is following:

**link to a movie presenting the problem:** https://www.youtube.com/watch?v=lsp9VToxIYc

When you turn on the landing autopilot and the vessel approaches the ground it starts to deccelerate. **The problem is that the braking maneouver is not SMOOTH like in the previous versions. The engine throttle starts to go up and down so in result the vessel is being stopped 3-4 meters above the ground and it stays like that with the engine turned on until it runs out of fuel.**

In the previous versions, when I was using the landing autopilot, the vessel was very gently touching the ground and the throttle was very smooth.

It happens no matter I set the touchdown speed to 0.5 m/s or  to 1 m/s or higher.

Regards,
Damian

**Comment by BIGMOS** [comment]
I seen it on mun landings. Throttles up and down have to turn landing guidance off when close  to ground. To land with out exslpodelng

**Comment by drhay53** [comment]
I can confirm that I have seen this issue multiple times with multiple different landers.

**Comment by sarbian** [comment]
I reverted some code changes and this should now work as before
