### ISSUE TITLE
Gui Issue

### ISSUE THREAD

**Issue by Mendrinos24** [MuMech/MechJeb2#736]
When launching a vessel using MechJeb for ksp v1.1.2 the gui is clearly visible and usable when on the launchpad however when the rocket reaches an altitude of about 1,500m the game freezes momentarily and when it unfreezes all of the gui for mechjeb and the staging on the left hand side disappears and control of the rocket is lost. I also cannot right click on any parts of the rocket. from what i gather from the log it is a mechJeb or modular flight integrator error because the only errors shown are as below;
`[EXC 18:49:29.222] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
	System.Collections.Generic.List1[PartThermalData].get_Item (Int32 index)
	FlightIntegrator.UpdateOcclusionSolar ()
	FlightIntegrator.UpdateOcclusion (Boolean all)
	ModularFI.ModularFlightIntegrator.UpdateOcclusion (Boolean all)
	FlightIntegrator.FixedUpdate ()
[ERR 18:49:29.226] MechJeb module MechJebModuleAscentAutopilot threw an exception in Drive: System.NullReferenceException: Object reference not set to an instance of an object
  at MuMech.DefaultAscentPath.get_autoTurnEndAltitude () [0x00000] in <filename unknown>:0 
  at MuMech.DefaultAscentPath.FlightPathAngle (Double altitude, Double velocity) [0x00000] in <filename unknown>:0 
  at MuMech.MechJebModuleAscentAutopilot.DriveGravityTurn (.FlightCtrlState s) [0x00000] in <filename unknown>:0 
  at MuMech.MechJebModuleAscentAutopilot.Drive (.FlightCtrlState s) [0x00000] in <filename unknown>:0 
  at MuMech.MechJebCore.Drive (.FlightCtrlState s) [0x00000] in <filename unknown>:0 `

images can be viewed here: http://imgur.com/a/1dSFI

How do I fix this as the game is unplayable even if the mechjeb autopilot is not enabled when launching.

**Comment by sarbian** [comment]
Those error are most likely triggered by an other mod doing something bad. You should share the whole log

**Comment by Mendrinos24** [comment]
I have put the entire log on mediafire for you to download (its too large for pastebin) however all i can see is this message showing repeatedly... Here is the log link:  [https://www.mediafire.com/?81d9w4ahos2ycae](url)

**Comment by sarbian** [comment]
You have broken cfg, outdated mods, models that don't loads. 

I am not debugging that mess. This has nothing to do with MechJeb.
