### ISSUE TITLE
SmartASS Error shown in log file when switching active vessel under some unknown circumstances...

### ISSUE THREAD

**Issue by Galenmacil** [MuMech/MechJeb2#741]
This something pops up in the log when switching vessel:

_[LOG 00:56:05.932] ------------------- initializing flight mode... ------------------
[LOG 00:56:06.086] Target vessel index: 7  vessel count: 11
[LOG 00:56:06.088] [FLIGHT GLOBALS]: Switching To Vessel COMM-SAT K3 ---------------------- 
[LOG 00:56:06.088] setting new dominant body: Kerbin
FlightGlobals.mainBody: Kerbin
[WRN 00:56:06.110] HighlightingSystem : Multiple Highlighter components on a single GameObject is not allowed! Highlighter has been disabled on a GameObject with name 'model'.
[LOG 00:56:06.128] [MechJeb2] Loading Mechjeb Dev #586 Sarbian
[ERR 00:56:06.159] MechJeb module MechJebModuleSmartASS threw an exception in OnLoad: System.NullReferenceException: Object reference not set to an instance of an object
  at MuMech.MechJebModuleSmartASS.Engage (Boolean resetPID) [0x00000] in <filename unknown>:0 
  at MuMech.MechJebModuleSmartASS.OnLoad (.ConfigNode local, .ConfigNode type, .ConfigNode global) [0x00000] in <filename unknown>:0 
  at MuMech.MechJebCore.OnLoad (.ConfigNode sfsNode) [0x00000] in <filename unknown>:0_

**Comment by sarbian** [comment]
Do you know the mode that Smart ASS was set on ?

**Comment by Galenmacil** [comment]
It most probably set to "ADV", "Sun" and "Forward" because this is one of my communication satellite for RemoteTech...
