### ISSUE TITLE
FR: Stop storing vessel settings in .cfg files

### ISSUE THREAD

**Issue by ihsoft** [MuMech/MechJeb2#742]
I noticed that `MechJeb` stores some vessel specific data in folder `MechJeb2\Plugins\PluginData\MechJeb2\`. Files have names like `mechjeb_settings_type_<craft name>.cfg`.

I'd like to propose to change the extension of these files from `.cfg` to any other value. Why? Because of all `.cfg` files are scanned and stored by KSP in the game database. If there is a `ModuleManager` installed (does anybody *not* install it?) then it will re-compile the whole database on any change in any config file. Depending on the number of the installed mods it may make a big difference.

Are these vessel setting files really need to be accessible via game database? Can they be a target for MM patch? If answer to the both questions is "no" then these files can safely be renamed to whatever extension that isn't recognized by KSP as database.

**Comment by sarbian** [comment]
Files in "Plugins\PluginData" subfolders are not loaded in the GameData base by KSP. They don't impact ModuleManager cache.

**Comment by ihsoft** [comment]
Interesting. I didn't know KSP ignores configs in particular folders. Thanks for the info.

Btw, I did some more tests and it looks that having only `PluginData` subfolder is enough to make configs not loaded in the database.
