### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by Isenderen** [MuMech/MechJeb2#743]
The GUI is not showing up on ships i have a Mech jeb control unit on.
Mods and game version:
KSP: 1.1.2 (Win64) - Unity: 5.2.4f1 - OS: Windows 10  (10.0.0) 64bit
Toolbar - 1.7.12
B9 Animation Modules - 1.0.2
B9 Part Switch - 1.2
B9 Aerospace - 6.1.1
B9 Aerospace Procedural Parts - 0.40.2
Custom Asteroids - 1.3.1
Firespitter - 7.2.3
RasterPropMonitor - 0.26
KSP-AVC Plugin - 1.1.6.1
Docking Port Alignment Indicator - 6.2
RemoteTech - 1.7
Kerbal Alarm Clock - 3.6.2.1

Screenshot:
![kerbal space program 4_23_2016 12_58_40 pm](https://cloud.githubusercontent.com/assets/18625097/15560279/88fc8856-2296-11e6-9885-68ad42fb1e02.png)

**Comment by Isenderen** [comment]
It wont let me upload the KSP.log file though. How should i get that to you?

**Comment by fr33kvanderwand** [comment]
Same Problem here...
KSP: 1.1.2 (Win64) - OS: Windows 10 (10.0.0) 64bit

**Comment by BloodyRain2k** [comment]
@Isenderen Pastebin or the like for example.
I personally prefer http://hastebin.com/ because it has not an ad and bloat crapped layout.

@fr33kvanderwand and without logs is it impossible to even guess what's the issue so just saying "same" isn't helping anyone.

**Comment by Isenderen** [comment]
[KSP.txt](https://github.com/MuMech/MechJeb2/files/305818/KSP.txt)
Heres the log. i just had to change the extention to .txt, just change it back to .log when you download it to look at it.

**Comment by Isenderen** [comment]
btw in the VAB using the toolbar mod it will show the icons to access the mechjeb functions like rcs assist and stuff like that but they dont do anything and dissapear as soon as i try to launch the ship.

**Comment by sarbian** [comment]
You have outdated version of BDAnimationModules, BahaTurret, ModuleAnimateEmissive & DockingPortAlignment that prevents MJ from initializing properly. 
If you use the last dev version of MJ it should initialize even with those outdated dll around : https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/

**Comment by Isenderen** [comment]
Ok, I'll update and get the latest version tomorrow. Then get back to you if it doesn't work.
