### ISSUE TITLE
Build #585 introduced error for Hohmann transfer to target

### ISSUE THREAD

**Issue by danielguo** [MuMech/MechJeb2#745]
Steps to repeat:
1. Ship in 267km circular orbit.
2. Station in 421km circular orbit.
3. From ship click Maneuver Planner -> Hohmann transfer to target -> Create note
4. In build 584 (https://github.com/MuMech/MechJeb2/commit/146e6479389ddebdebb3db2a2e1434d1789d267c), the ship is planned to intercept the target perfectly.
5. In build 585 (https://github.com/MuMech/MechJeb2/commit/cd90df0dffdcb47c8604132fc17082dabbfc6920), the ship misses the target by a wide margin. 
Separation at 461km with 525m/s relative speed.

[KSP.log.zip](https://github.com/MuMech/MechJeb2/files/287976/KSP.log.zip)
[output_log.zip](https://github.com/MuMech/MechJeb2/files/287979/output_log.zip)

Note: I'm using RSS+RO.

Thanks.

**Comment by sarbian** [comment]
The fix will have to wait for KSP 1.1.3
