### ISSUE TITLE
A Death Loop In “CoastToDeceleration”

### ISSUE THREAD

**Issue by ceabie** [MuMech/MechJeb2#746]
OnFixedUpdate in [CoastToDeceleration](https://github.com/MuMech/MechJeb2/blob/dev/MechJeb2/LandingAutopilot/CoastToDeceleration.cs#L67):
if  currentError > 1000 && (!vesselState.parachuteDeployed || vesselState.drag <= 0.1) then switch to CourseCorrection.
In [CourseCorrection](https://github.com/MuMech/MechJeb2/blob/master/MechJeb2/LandingAutopilot/CourseCorrection.cs#L57):
if (vesselState.drag > 0.1) then switch to CoastToDeceleration.

Suppose now that currentError > **1000**, parachuteDeployed = **false** and vesselState.drag > **0.21**, it will be:
CoastToDeceleration(drag > 0.1) ->
    CourseCorrection(currentError > 1000 && !parachuteDeployed is true) ->
 CoastToDeceleration(drag > 0.1)  -> 
    CourseCorrection(currentError > 1000 && !parachuteDeployed is true) -> 
CoastToDeceleration(drag > 0.1) -> .....

Going to death loop until the currentError < 150 or is already too low.

**Comment by ceabie** [comment]
Thanks, it is working better!

**Comment by sarbian** [comment]
Thanks for finding it. That s the kind of bug that can be hard to trace.
