### ISSUE TITLE
Delta V for core+boosters varies between VAB and flight

### ISSUE THREAD

**Issue by NathanKell** [MuMech/MechJeb2#748]
An R-7 config (decoupleable boosters that do not crossfeed, core that lights at the same time but burns longer than the boosters) is calculated correctly in the VAB, but in flight everything combines into a single stage for display and delta V is wrong.

**Comment by sarbian** [comment]
I can't seems to dup it in stock and the test in RSS takes way to long to launch to debug the dv thread :(

**Comment by lamont-granquist** [comment]
all fixed afaik.
