### ISSUE TITLE
Ascent target is 180 degrees off in azimuth

### ISSUE THREAD

**Issue by NathanKell** [MuMech/MechJeb2#751]
@sarbian with the modset I linked you before, the shown ascent indicator is 180d off and in addition it looks like launch-to-inclination is also troubled.
(We spoke about this but I never made a ticket)

**Comment by drhay53** [comment]
https://github.com/MuMech/MechJeb2/issues/739

**Comment by NathanKell** [comment]
I have been able to repro it by setting orbit altitude "too high" and fix by lowering orbit altitude. I believe I can therefore close this issue.
