### ISSUE TITLE
FAR control surfaces not picked up for torque

### ISSUE THREAD

**Issue by NathanKell** [MuMech/MechJeb2#752]
Despite https://github.com/MuMech/MechJeb2/blob/dev/MechJeb2/VesselState.cs#L817 it looks like FARControllableSurface modules aren't being picked up. In FAR they do implement ITorqueProvider so I don't know what could be wrong here.

**Comment by sarbian** [comment]
Fixed in 2e0ef29c366c4102e1a67efd6a98905feffdd649 
So stupid :(
