### ISSUE TITLE
"DecelerationBurn": Sometimes attitude of the vessel has not yet reached the proper angle to burn.

### ISSUE THREAD

**Issue by ceabie** [MuMech/MechJeb2#755]
Branch: dev (the latest) 

[DecelerationBurn](https://github.com/MuMech/MechJeb2/blob/dev/MechJeb2/LandingAutopilot/DecelerationBurn.cs#L57):
**Vector3d.Dot(vesselState.forward, desiredThrustVector) < 0.75**
Means that when the angle of vessel's attitude and desiredThrustVector is < 90, it can start to burn.Sometimes if the angle is 88 then it will lead off course.

Or it's maybe (< 0.75 \* desiredThrustVector.magnitude) ?

I try to use Vector3d.Angle(vesselState.forward, desiredThrustVector) > 1, will burn when angle <= 1. It looks like working well.Or you have a better way.
 Thanks.

**Comment by sarbian** [comment]
desiredThrustVector is normalized so the dot is < 0.75 if the angle is < 41.4 degree

**Comment by ceabie** [comment]
Oh! it's my mistake. 
but it's burning when the angle between the desired attitude(desiredThrustVector) and the current attitude is 40 degree can cause off course. Especially in Kerbin there is a large gravity's body.

**Comment by lamont-granquist** [comment]
closing as another dup of all the landing autopilot issues in #1052
