### ISSUE TITLE
May change gmcs to mcs?

### ISSUE THREAD

**Issue by MikeCoder** [MuMech/MechJeb2#756]
According to the doc of mono: [C# Compiler](http://www.mono-project.com/docs/about-mono/languages/csharp/)

> ![snip20160614_50](https://cloud.githubusercontent.com/assets/3142935/16038501/c03b3526-3257-11e6-83ab-35b0bc13a17f.png)

Shall we change the `gmcs` compiler in Makefile to `mcs` ?

> ![snip20160614_51](https://cloud.githubusercontent.com/assets/3142935/16038530/ef34c1bc-3257-11e6-9aa9-4e54bb9bba22.png)

**Comment by sarbian** [comment]
If you want. I use roslyn to build it, so it does no change anything for me.

**Comment by MikeCoder** [comment]
ok. thanks.
