### ISSUE TITLE
[Suggestion]can split the ComputerMoulde and stuff like this to another Dll to improve hot-reloader?

### ISSUE THREAD

**Issue by ceabie** [MuMech/MechJeb2#757]
Hi, recently I'm doing some experimental tests in MechJeb2, but must restart the game after rebuild this project everytime.You know the game start time always very long.

I find a way to hot-reloader a dll in KSP: [KSPPluginReload](https://github.com/m1ndst0rm/KSPPluginReload).
It can reloader a alone dll when KSP is running.But MechJeb2 is all in one, and I'm not familiar with the mechanism of KSP and MechJebCore to refactor it.

can you give some suggestion to do this or in next version?

thanks.

**Comment by BloodyRain2k** [comment]
If the game starts up too slow you can try running it from a RamDisk, 
assuming you have 2 or 3gb spare memory before starting it. 
https://www.softperfect.com/products/ramdisk/
And alternative would be a SSD, though I'd rather suggest more memory 
and a RamDisk.
Also don't enforce VSync via driver or anything as Unity is not capable 
of loading more than 1 asset per frame during startup so with VSync 
you're in for a looong loading time by default. And not having 20 part 
packs installed helps too.

I hope this helps until Sarb can comment on the hot-reload thing and 
should it be doable get around to it, or who ever else might tackle that 
in the end.

**Comment by sarbian** [comment]
I saw that code when it was first posted 2 years ago. 

1. From the reloader readme : "Parts & partmodules will not be reloaded."

2. that code was made for unity 4 and I sure won't adapt it for 5.

3. Using that in MJ require too much change for a limited use case. With the ability to break and inspect the game in dev mode it does not help all that much.
