### ISSUE TITLE
Mass of disabled fuel tanks not being used in DeltaV calculations leading to values much higher then reality

### ISSUE THREAD

**Issue by Dark-Matter-001** [MuMech/MechJeb2#760]
Title sums it up pretty much. If you have a disabled fuel tank on your vessel, (perhaps mono prop on a later stage you don't want used at launch?), its mass will be completely ignored by the DeltaV calculations resulting in a number much higher then reality and failed missions due to the surprise shortfall.

Found this out when a vessel that said it had 2700m/s dV fell 200m/s short of a 1600m/s insertion burn into Duna. Had monoprop powered satellites with disabled tanks.

Simple Test Setup: http://imgur.com/a/xL99Z

**Comment by sarbian** [comment]
hum, the code seems to handle this case properly. I ll test it tonight to see if anything changed.

**Comment by sarbian** [comment]
It works as intended. The simulation see a part with no usable ressource so the first thing it does is stage it. If you display the full staging stats you will see that.
As a reminder your root part should be the last thing you want remaining on your vessel. In that case with the root part as the probe then the top fuel tank is considered expendable.
