### ISSUE TITLE
Maneuver Node Editor - Conics Mode Switch doesn't seem to work

### ISSUE THREAD

**Issue by Theysen** [MuMech/MechJeb2#761]
Newest MJ version in 1.1.3 - tested in full stock -

the Conics Buttons in Maneuver Node Editor have no influence on the actual visual representation in the Map View while planning and don't seem to switch the mode. If already reported or updated please ignore.

**Comment by Theysen** [comment]
Newest MJ version in 1.1.3 - tested in full stock - 

the Conics Buttons in Maneuver Node Editor have no influence on the actual visual representation in the Map View while planning and don't seem to switch the mode. If already reported or updated please ignore.

**Comment by sarbian** [comment]
I just tested with an node giving a trajectory that intercepts the mun and and the conics mode change the projected trajectory. How did you test ?

**Comment by Theysen** [comment]
I realised I was in 'Focus View on Mun' selection and then tried to change it. My bad, they work when normally plotting in Kerbin View / Ship View where it's supposed to.
