### ISSUE TITLE
Launch to Interplanetary Window is broken

### ISSUE THREAD

**Issue by absincog** [MuMech/MechJeb2#763]
This is effectively a reopen of issue 738, which was closed as fixed after the release of KSP 1.1.3 / MJ 1.5.8, but appears to remain an issue.

Tried a launch at the interplanetary window to Eve after performing clean installs of KSP 1.1.3 / MJ 1.5.8 (no other mods installed).  MJ Ascent Guidance set the launch at 176 days out.  Launched and achieved orbit using Ascent Guidance.  Set an interplanetary transfer to Eve using the maneuver planner and MJ set the node ~155 days out.  In the past (i.e., prior to KSP 1.1.2), when I have launched at the interplanetary window, the interplanetary transfer node would be set ~1 hour after achieving Kerbin orbit.

KSP log attached
[KSP.log.zip](https://github.com/MuMech/MechJeb2/files/337007/KSP.log.zip)

**Comment by sarbian** [comment]
How long you have to wait for the transfer windows depends on the date so I don't see what it wrong here. If the date was the same then what was the node dV for 1.1.2 and 1.1.3 ?

**Comment by absincog** [comment]
Ok, thanks.

**Comment by absincog** [comment]
Hello - is there any update on this?  Thanks.

**Comment by AnghusMcleod** [comment]
I can confirm that this is happening in the latest version of MJ available from CKAN with RSS/RO/RP-0.
Launch to interplanetary window gets you into position for strange radial burns with high speed intercepts as opposed to Hohmann transfers for rendezvous. Choosing lowest deltaV at the same position give you a clean transfer approximately 150-200 days out when going from Earth to Venus.

**Comment by absincog** [comment]
This continues to occur in build #643, with KSP version 1.2.  It seems as though this is one of the key features of mechjeb - are there plans to fix this?

**Comment by justhearit** [comment]
Just happened to me. Used ascent guidance to launch at interplanetary window to Duna. I am still 1 year away from the transfer burn after circularization. This happens with the latest beta build as of right now.  2.7.3.0 - 802

**Comment by lamont-granquist** [comment]
I never use launch to interplanetary window myself, I always plan the windows using the transfer window planner mod, use KAC to warp to the alarm, launch, and then use the advanced transfer planner to setup the ejection burn.

**Comment by felixscheffer** [comment]
@lamont-granquist As far as I understand, you removed this feature in https://github.com/MuMech/MechJeb2/commit/022b4ec37a658f75d4896a0711da1d56f244a876 , so I guess this issue should be closed as wont-fix?

**Comment by lamont-granquist** [comment]
yep

**Comment by lamont-granquist** [comment]
and yeah, i don't realistically think that bit of #1061 is going to happen.
