### ISSUE TITLE
Warp Helper shutoff at altitude-forced warp changes

### ISSUE THREAD

**Issue by Gwtheyrn** [MuMech/MechJeb2#765]
It looks like the Warp Helper shutoff engages when altitude forces the warp speed to drop. This probably explains why people are having issues with the landing module cratering their ships. When the Warp Helper shuts off, it doesn't disengage the warp, so MJ never starts the braking maneuver until something (such as altitude) forces warp back to 1x.

To recreate:
1. Launch to 100km orbit
2. Change apoapsis to 650km at periapsis.
3. Warp to apoapsis.
4. Create new maneuver node to change apoapsis to new desired altitude at periapsis and execute.
5. Watch as altitude change forces warp down to 50x when it dips below 120km. Warp helper shuts off. Ship continues at 50x warp right past the maneuver node.

**Comment by sarbian** [comment]
This (and other warp problems) should be fixed in the new dev with d8beaeef6aa09840215dc2226aa2723019ac97a7
Thanks for the report
