### ISSUE TITLE
Maneuver Planner Lead Time Reset Affecting Tolerance

### ISSUE THREAD

**Issue by 130erickson** [MuMech/MechJeb2#766]
When you reset the lead time in the maneuver planner, it brings both the lead time and the tolerance to 3 even though the default Delta V tolerance is 0.1.
![screenshot4](https://cloud.githubusercontent.com/assets/20257966/16541334/79f7df50-4045-11e6-9131-b25128b70b44.png)
![screenshot5](https://cloud.githubusercontent.com/assets/20257966/16541333/79f449e4-4045-11e6-9545-9c0febf991d3.png)

**Comment by sarbian** [comment]
This was fixed in the dev build with the commit ed0fd13c34d56777a7d0947261e6f7279d931728
You can get the last dev build here : https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/
