### ISSUE TITLE
Time Warp Not Operational

### ISSUE THREAD

**Issue by 130erickson** [MuMech/MechJeb2#767]
Time Warp is not working for any MechJeb2 Module. Note that Auto-warp is turned on in the screenshot and that the warp factor is unchanged.
[[save file]](https://drive.google.com/open?id=0B9QzNt8nAXkkc3NTY3g4a1doQnc)
![screenshot8](https://cloud.githubusercontent.com/assets/20257966/16541377/865d29de-4046-11e6-904d-02502d435a93.png)

**Comment by sarbian** [comment]
Could you share a log ?

**Comment by 130erickson** [comment]
[ksp.txt](https://github.com/MuMech/MechJeb2/files/344993/ksp.txt)

**Comment by sarbian** [comment]
You are playing KSP 1.1.2. The current version of Mechjeb is for KSP 1.1.3
