### ISSUE TITLE
request: combining multiple maneuver nodes at the same spot

### ISSUE THREAD

**Issue by assassinacc** [MuMech/MechJeb2#776]
just a reminder... ;)

**Comment by jwvanderbeck** [comment]
I'd allow for a tolerance.. IMHO ideally a dialog that says something like "Merge all nodes within ___ seconds"

With options for the final node's UT to be that of the first node, last node, or the average

**Comment by assassinacc** [comment]
probably useful source: https://github.com/radistmorse/KSPPreciseManeuver/blob/master/src/NodeManager.cs

**Comment by lamont-granquist** [comment]
this was completed.
