### ISSUE TITLE
Feature Request: Allow Maneuver Node Planner to accept Percentage Values

### ISSUE THREAD

**Issue by Xyphos** [MuMech/MechJeb2#780]
Often I will launch an interplanetary satellite into LKO via Spaceplane, but due to the low thrust of the ion engines, I'm forced to manually create a spiral trajectory over the course of several nodes, before ejecting it out of Kerbin's SOL. this is done by `<Change Apoapsis> <At Apoapsis>` and doubling the AP for each node.

what I wish it could do, is accept **125%** as the value, instead of having to manually calculate and type it in.

**Comment by henrybauer** [comment]
[Manuever Node Splitter](http://forum.kerbalspaceprogram.com/index.php?/topic/132209-11-maneuver-node-splitter-v150/) or [KSPTOT](http://forum.kerbalspaceprogram.com/index.php?/topic/33568-winmac-ksp-trajectory-optimization-tool-v154-ksp-v11x-compatibility/) will split one big node into several smaller ones for you, which works great for turning a 2000 m/s burn into 5 x 400 m/s burns.

**Comment by lamont-granquist** [comment]
seems like #737 covers the more actionable part of this request.  closing as dup.
