### ISSUE TITLE
Launch into Target Plane in RSS broken

### ISSUE THREAD

**Issue by Theysen** [MuMech/MechJeb2#786]
- latest Dev version installed
- Launch into target plane as timed launch wants to launch during completely off plane times, e.g. Cape Canaveral into lunar plane wants to start at 44° relative inclination, timed launches from Korou to lunar results in instant "Launching into target plane" although it is way off, same thing for most custom objects in the game too (space stations on 50° inclined orbits and MJ instantly jumps to "launching into target plane, not waiting for appropriate launch windows) 
  (- also when launching into a set inclination without target sometimes it's off by +/- 3  degress where as it used to work properly)
- Logs (barebone RSS and MJ dev install - this is a log which had the instant switch to Launch to target orbit without timer despite being completely off, and there's nothing really in the logs about it):

https://www.dropbox.com/s/qqkfq2mj8jy46iw/output_log.txt?dl=1
https://www.dropbox.com/s/v5sa7c8hoc7ol25/KSP.log?dl=1

**Comment by Theysen** [comment]
- ON HOLD - need more investigation

**Comment by lamont-granquist** [comment]
@sarbian pretty sure this was an old bug as well
