### ISSUE TITLE
semi-automatic node execution

### ISSUE THREAD

**Issue by Schnobs** [MuMech/MechJeb2#789]
Is there a way to have MJ cut the throttle at the end of a burn without using the fully-automatic "Execute Node" feature?

In Realism Overhaul, starting an engine can be quite involved and MJ is not aware of the necessary steps. Sometimes this can easily be worked around, but on other occasions I really need to control the throttle myself in order to start the burn at (about) the right time.

However, I really want machine support when ending the burn. Especially in RO, where dry masses are miniscule and you can have insane accelerations once most of the fuel is gone. This really demands split-second accuracy.

In principle I could pass over control to the autopilot when all engines are running. However, that routine apparently starts by locking the throttle to zero before doing anything else, thus eating a precious ignition.

**Comment by MrGeekArt** [comment]
Schnobs, do you think that the suggestion made in [#795](https://github.com/MuMech/MechJeb2/issues/795) would satisfy you ?
This wouldn't be as flexible as your proposal but would in most case work i.m.o.

**Comment by Schnobs** [comment]
Well, I guess that this is a more of a philosophical question. Basically, I'm asking for more modularity in order to better cope with special cases (or so that i don't always have to design my vessel in such a way that MJ can handle it). Improving MJ so it can deal with more cases is certainly worthwhile, but goes in a wholly different direction.
