### ISSUE TITLE
Errors unsolved

### ISSUE THREAD

**Issue by oldtex59** [MuMech/MechJeb2#791]
Hi,

OK, using Kerbal 1.1.0.1230, I have been scratching my head over the issue of the MechJeb interface just not showing up when launching or flying.  It's in the tree, it's attached, says it's working, just no interface. 

Only thing I see in the debug log is this:  [Exception]: FieldAccessException: Field `ModuleGimbal:engineMultsList' is inaccessible from method `MuMech.VesselState:AnalyzeParts (Vessel,MuMech.VesselState/EngineInfo,MuMech.VesselState/IntakeInfo)'

Here's the full log:  [https://www.dropbox.com/s/o840fcr2gne5uh1/KSP_Log_09-06-16-Mechjeb.log?dl=0](url)

I asked this same question over on the KSP forums, so I"ll monitor both spots for an answer.

**Comment by sarbian** [comment]
MJ is built for the last version of KSP: 1.1.3.1289
