### ISSUE TITLE
MechJeb2 not working with KSP 1.2 Beta

### ISSUE THREAD

**Issue by solarisfire** [MuMech/MechJeb2#792]
MechJeb2 UI elements aren't showing in KSP 1.2 Beta making the mod unusable.

Parts are available, and can be put onto a ship. But the MJ tab doesn't show so the MJ panels cannot be accessed.

**Comment by Olympic1** [comment]
That's because MJ isn't updated for 1.2 yet. Sarbian is busy with helping with KSP 1.2, so have patience for an update.

**Comment by solarisfire** [comment]
Just making sure people were aware. Couldn't find any reports anywhere saying other people were experiencing the same problem.

**Comment by sarbian** [comment]
Don't worry, the dev IS aware.
