### ISSUE TITLE
when will wechjeb for V1.2 be comming out

### ISSUE THREAD

**Issue by Chllgy** [MuMech/MechJeb2#793]
when will Add to dictionary for V.1.2 be coming out i need it its literally one of the most important components of the game for me I tried installing it and it seemed to load fine but never appeared on the screen. is there anyway to make it work in the meantime?!?!?!?!?!?!

**Comment by Olympic1** [comment]
This is why the thread was closed. To prevent these questions being asked.

But to awnser your question: Sarbian will make a release when 1.2 is fulle released. Untill then have patience.

**Comment by sarbian** [comment]
As soon as my clone is ready
