### ISSUE TITLE
MechJeb menu does not appear

### ISSUE THREAD

**Issue by Rolycade** [MuMech/MechJeb2#794]
KSP 1.2.0.1548 (OSXPlayer)-pre
MechJeb2-2.5.8.0-635
[KSP.log.txt](https://github.com/MuMech/MechJeb2/files/502679/KSP.log.txt)

Start sandbox mode, create (any) ship with a MJ-202 attached, go to launch and the MJ menu does not appear.

Awesome job on MJ btw. I love making spaceships!

**Comment by JessShadowheart** [comment]
I am pretty sure that mechjeb Version was not intended for the prerelease Version.

**Comment by sarbian** [comment]
Right now you need to use the dev version
https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/
https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/lastSuccessfulBuild/artifact/MechJeb2-2.5.9.0-638.zip
