### ISSUE TITLE
RCS ullage on maneuver node execution

### ISSUE THREAD

**Issue by borogove** [MuMech/MechJeb2#795]
Realism Overhaul requires for many engines that propellant is stabilized before engine ignition. Typically for upper stages this is done by firing RCS prograde for a few seconds before ignition. It would be very nice to have an option for this on "execute next maneuver" in MJ. Checkbox labeled "RCS ullage", edit field to set the time, e.g. 3 seconds; after reaching the correct attitude, at the start of a maneuver burn, MJ would hold throttle at zero but fire RCS prograde for the specified time, then turn the throttle up.

**Comment by lamont-granquist** [comment]
you might want to checkout https://github.com/MuMech/MechJeb2/pull/775 if you have "prevent unstable ignitions" checked and RCS selected it should fire RCS until the engines are stable and then fire the engines and execute the burn.

**Comment by borogove** [comment]
I don't seem to have that option in my utilities in MJ 2.5.8.

**Comment by lamont-granquist** [comment]
no, its not in 2.5.8 its only in dev builds for 1.1.x, it looks like it'll be in 2.5.9 for 1.2

**Comment by lamont-granquist** [comment]
@sarbian the "Use RCS to ullage" option in dev should close this
