### ISSUE TITLE
[DEV Question] - Popup appears below the mechjeb UI

### ISSUE THREAD

**Issue by SPD13** [MuMech/MechJeb2#797]
Hi,
I am working on the script module and i am facing a dev problem.
When a script is saved, i would like to show a confirmation Popup. I am using this function:
`PopupDialog.SpawnPopupDialog(new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f), "Save", "Script saved in slot "+(slot+1)+" on current vessel", "OK", true, HighLogic.UISkin, true);`
but the popup appears behind all the MechJeb windows.
Is there a GUI modifier i can use on the popup to bring it above any window?
Thank you for your help

**Comment by sarbian** [comment]
Unfortunately no. Not until I rewrite the UI to use the new unity UI

**Comment by SPD13** [comment]
OK no problem. I'll find a way to notify the user without a popup.
Thank you for your feedback.
