### ISSUE TITLE
#637 Landing Issues

### ISSUE THREAD

**Issue by ArgyleMHK** [MuMech/MechJeb2#798]
Landing Target: Mun
KSP build 1576

Issue: 
Craft 02 refused to plane change when "Land at target" selected. it just warped around Mun endlessly. Changed to "Land anywhere" and craft deorbited, then behaved erratically firing RCS and engines first prograde/retrograde, then normal/antinormal until craft decelerated to 76m/s, then warped down to 2000m, started  erratic engine firing again and crashed into surface. Lander can survived.

Logs: KSP.log, output_log.txt, save file & craft file.

[MechJec errors.zip](https://github.com/MuMech/MechJeb2/files/518456/MechJec.errors.zip)

**Comment by sarbian** [comment]
Too bad the log contains 467417 lines of "MissingMethodException: Method not found: 'ResourceRatio..ctor'."
I won't look at report with broken mods.

**Comment by ArgyleMHK** [comment]
Part Overhauls by Porkjet?

Now that's funny.

**Comment by sarbian** [comment]
Nope. USITools.dll by RoverDude. That s funny as well.
