### ISSUE TITLE
Dev Branch | Ascent Guidance Doesnt Do Maneuvers...

### ISSUE THREAD

**Issue by DrPiggy** [MuMech/MechJeb2#800]
Title.. it just says circularize and doesn't do anything...

**Comment by MrGeekArt** [comment]
Hi DrPiggy,
Please specify the Dev version you're using and provide the required log files.
On a side note, Sarbian already of acknowledged about this on the [MechJeb forum thread](http://forum.kerbalspaceprogram.com/index.php?/topic/111978-113-anatid-robotics-mumech-mechjeb-autopilot-258-22-jun-2016/&page=121) 4 hours ago.

**Comment by DrPiggy** [comment]
@MrGeekArt firstly, i dont have a clue how that thread is connected xD, secondly:
version(im using ckan): 2.5.9.0-641
log file: [https://drive.google.com/file/d/0B8NkRAMTZtmbSjFVYWpNcUJLcmM/view?usp=sharing](https://drive.google.com/file/d/0B8NkRAMTZtmbSjFVYWpNcUJLcmM/view?usp=sharing)

while uploading i noticed that there are 2 errors from MechJeb ALL THE TIME:
1.MissingMethodException: Method not found: 'MapView.get_MapIsEnabled'.
	MuMech.MechJebCore.OnGUI ()
2.MissingMethodException: Method not found: 'MapView.get_MapIsEnabled'.
	MuMech.MechJebAR202.FixedUpdate ()

**Comment by sarbian** [comment]
"1.2.0.1500 (WindowsPlayer)-pre"
You are not on the KSP release build. And build 1500 is from Sept 18th !

**Comment by DrPiggy** [comment]
@sarbian i updated my game and it fixed it, sorry for all the hassle.
