### ISSUE TITLE
Manuver node changing when selecting target

### ISSUE THREAD

**Issue by Agnemon** [MuMech/MechJeb2#801]
Dev -638 on 1.2 (issue was there on 1.2 pre)
If you select a target while a manuver node is current it alters the existing node

EG: circularising an orbit (no target selected) node is executing. Select a target (Mun) active node changes from 100 km to a much larger random? one.

Does not appear to be ship dependant.

Easy work around is to just not select a target until the current node is finished

Sry, no logs atm (I don't think this would be hard to replicate)

1.2 pre, only MJ2 installed

1.2 full
KAS 0.60
Kerbalstats 2.1
KIS 1.3
MJ2 (638)
Planetary Base Inc 1.1.5
RCS Build Aid 0.9
AMP Year (Reposoft Tech) 1.4
Module Manager 2.7.1

**Comment by SciMan314** [comment]
I can confirm that this bug still exists in Dev -648 on KSP 1.2.1
The issue can be reliably reproduced during execution of any maneuver node by right clicking any target in the map and selecting "set as target".
I have not tested if this issue arises with changing the surface coordinate target used by the Landing Autopilot.

**Comment by lamont-granquist** [comment]
I can confirm that on 1.3.x that selecting different targets while burning a node down causes the dV display to bounce around.  That is a core KSP feature, though, and a core KSP bug, MechJeb does not draw any of the ManeuverNode data.
