### ISSUE TITLE
MechJeb fails to load

### ISSUE THREAD

**Issue by ervildave42** [MuMech/MechJeb2#803]
I have MJ 2.5.8.0 and KSP 1.2.0.1586
MechJeb does not work, the control module is in the inventory and can be placed on rockets with no problem but appears not to do anything, no tabs or windows ever show up for it.  I have already gone sofar as to uninstall KSP, delete all files, and start with a clean install of nothing but the latest KSP and MJ with no results.

**Comment by nmaarse** [comment]
I have exactely the same problem. I reinstalled KSP but end up with the same result as desecribed above. De mechjeb control module is in the inventory and can be placed. But nothing appears. not tabs or windows. als during launch there is nothing appearing from the mechjeb so cannot use anything from mechjeb.

**Comment by Olympic1** [comment]
@ervildave42 and @nmaarse. v2.5.8.0 is **NOT** build for 1.2. If you want to use MJ use the dev build.

**Comment by ervildave42** [comment]
Thank you Nmaarse!  Works like a champ!
