### ISSUE TITLE
Ascent Guidance - Launch into Plane of Target busted in dev build 644?

### ISSUE THREAD

**Issue by lamont-granquist** [MuMech/MechJeb2#807]
MechJeb2-dev 2.5.9.0-644

I set a target to Minmus, click "launch into plane of target" then hit "engage autopilot" and there's no warping to the target plane, it just launches immediately, even when KSC is very obviously about 90 degrees off from being aligned with the AN/DN of Minmus' orbit and nowhere close to being the plane of the target...

Honestly not entirely certain I'm not just being a bit thick in the head tonight though and I'm missing something stupid...

**Comment by absincog** [comment]
This may be related to issue 763 which I originally opened as issue 738 in May (it was erroneously closed so I reopened as 763 in June). Bottom line is that the launch at interplanetary window functionality has been broken for months now. It does not accurately choose the window, leaving a huge dV to complete and/or fine tune the transfer.  I wonder whether this is also impacting the 'launch into plane of target' function.

**Comment by Bill0151** [comment]
Just put it on orbit, circularize, change plane to target, hohmann transfer, fine tune target, warp, circularize, done.

**Comment by lamont-granquist** [comment]
That works up until you're trying to do something like intercept a class E asteroid on an orbit nowhere near Kerbin's equator, or trying to launch to the actual Moon in RSS, where you're trying to avoid the cost of the plane change maneuver in your delta-V budget.

**Comment by absincog** [comment]
Yes - this can be done manually as described, except that if your target is another planet such as EVE and you don't launch close to an interplanetary transfer window, it can take hours of time warp once in orbit to get to the transfer window.

**Comment by Bill0151** [comment]
This may be true, but I believe the issue was going to minmus only.

**Comment by lamont-granquist** [comment]
no, the issue is that timed ascent guidance appears to not be working at all
