### ISSUE TITLE
Partless free MechJeb cfg file doesn't work

### ISSUE THREAD

**Issue by fr33soul** [MuMech/MechJeb2#830]
I used the old version of the free partless cfg [file](https://kerbal.curseforge.com/projects/mechjeb-embedded-universal?gameCategorySlug=ksp-mods&projectID=221109) that allow us to use mechjeb without the maneuver and translator part, but it doesn't work..

there's any update on this?

**Comment by lamont-granquist** [comment]
http://forum.kerbalspaceprogram.com/index.php?/topic/75295-0235-mechjeb-and-engineer-for-all/
