### ISSUE TITLE
Advanced Transfert to Another Planet Issue

### ISSUE THREAD

**Issue by Corgumolax** [MuMech/MechJeb2#843]
Hi, 
first I wish to thx for this great mod. Now the problem:
I try to achieve a Kerbin-Duna Transfert...
 - First I put the vessel in a CIRCULAR orbit around kerbin at 640km (for warping). 
 - Now, I use MechJeb to plan an Advanced Transfert to another planet:
    * Select Duna as a target
    * Open MechJeb and choose "advanced transfert...."
    * First the node planner issue a Warning "Initial Orbit can't be hyperbolic"......but initial orbit is not hyperbolic, it's circular.
    * Anyway, I ignore this warning, I click on a blue area of the porkchop windows. and create a node, then execute it.
    * Wait...for the transfert window....wait....wait....wait.....
    * When it reach the transfert window, at start the maneuver is executed as intended but when the planned orbit reach the point where it escape from Kerbin SOI, Duna is automatically deselected, and next calculation and execution of the transfert node are wrong and the vessel miss Duna. Even if I try to reselect Duna as fast as I can, it doesn't work.

KSP Version:  1.2.2.1622
Mods: 
- [x]Science! 5.4
- BetterBurn Time 1.5.3
- Gravity Turn Continued 1:1.7.6
- Kerbal Engineer Redux 1.1.2.8
- MechJeb (of course)  2.6.0.0
- Module Manager 2.7.5
- AutoAsparagus 2.2.5
- Smart Stage 2.9.5
(All by CKAN)

ps: hope it's clear, sorry for the poor quality of my english.

**Comment by lamont-granquist** [comment]
@sarbian i can't quite tell but i suspect this is due to my patches to the transfer planner (not the lambert solver but the cad7c7d82afbc6702c6ad189005b431797dee346 stuff).  i was working on this and was deep down a levenberg-marquardt rathole that i didn't manage to extricate myself from before i had to start planning for vacation.  now that i've got some time again i want to take another run at it

**Comment by sarbian** [comment]
Knock yourself out. I am down with the flu myself...

**Comment by Greg4040** [comment]
Same problem here. 
So, figure that I can't play without Mechjeb anymore ;)

**Comment by dacj501** [comment]
This same exact thing is happening to me as well - is there any word on fix?

**Comment by mpredosin** [comment]
Same problem.  I'm getting "initial orbit must not be hyperbolic" when trying to set a transfer node.

**Comment by sarbian** [comment]
@lamont-granquist is the one who has the info with this bug. I could have a look but it would take me a lot more time.

**Comment by sworisbreathing** [comment]
I have the issue as well. Tried on minimus-to-mun transfer as well as kerbin to duna. In both cases the porkchop transfer doesn't take me into the other body's SOI.

**Comment by Greg4040** [comment]
Ho come on please resolve this bug :)

**Comment by dacj501** [comment]
Workaround for this is to clear any target (so that you have no active target shown) before the burn - then it wont go crazy on you.

**Comment by lamont-granquist** [comment]
closing this one as i think the specific bugs that caused this issue were fixed.  #1086 addresses an issue with the current code.
