### ISSUE TITLE
Issue with MechJeb-created maneuver nodes and Precise Node mod

### ISSUE THREAD

**Issue by joshpainter** [MuMech/MechJeb2#845]
I'm not sure if this is a MechJeb bug or a Precise Node bug, but I saw mention of it on the Precise Node thread so I thought I'd post it here.

With MechJeb and Precise Node both installed, create a maneuver node using MechJeb's maneuver node planner, such as a Hohmann transfer to Mun. Now manually create a second maneuver node after the first. In Precise Node's window, notice that you can change from Node 1 to Node 2 using the > button.

Now, edit the first MechJeb-created node with PreciseNode's window. Add a few dV prograde for example. Notice that you now cannot change from Node 1 to Node 2 using the > button. This is the bug.

Now, manually adjust the first maneuver node (created by MechJeb) by a tiny amount in any direction using the stock dragger in the Map view. Observe now that Precise Node's window > buttons again work correctly to navigate through both nodes.

Theory: Precise Node doesn't like something about how MechJeb creates maneuver nodes and errors when trying to edit them. I am assuming this is something specific to how MechJeb is creating the node vs. how the game Map view is creating the node because of the workaround I found: by simply manually editing a MechJeb-created node by a tiny amount, Precise Node will again recognize it as a valid node.

Here is the thread on PreciseNode that might apply:
http://forum.kerbalspaceprogram.com/index.php?/topic/44129-120-precise-node-124-precisely-edit-your-maneuver-nodes/&page=31

Quote from thread:

> "Did you generate the initial maneuver node with MechJeb? I noticed that maneuver node created by MJ "Maneuver Planner" generate exception when edited with Precise Node. Manually created ones are okay. Since MJ is not officially out yet for KSP 1.2.0, maybe this well get fixed by Sarbian." - Galenmacil

**Comment by lamont-granquist** [comment]
possibly fixed here:  831fc7623dd67ca881e44641de5272302cca3898

**Comment by sarbian** [comment]
Yes, this should partially fix it. The bug is actually in the stock code AFAIK. I need to submit a bug to Squad.
