### ISSUE TITLE
MechJeb fails to operate (Cannot find a PartModule of typename 'MechJebAR202')

### ISSUE THREAD

**Issue by Flatfoot** [MuMech/MechJeb2#846]
Tested all the way to a restarted computer, clean install of KSP via Steam (tested 32 and 64 bit), with only the Dev .zip of MechJeb2 installed via KSP Mod Admin.

New Sandbox, easy.

Stock Craft loaded

MechJeb AR202 case shows up in the part list.. MechJeb Pod does not.

Attaching the AR202 case to the vehicle does not enable the MechJeb window(s) to display.

OS: Win 8 64

Other Mods work when installed.. this is the only one I'm having issues with.
[Uploading output_log.txt…]()

**Comment by Flatfoot** [comment]
[output_log.txt](https://github.com/MuMech/MechJeb2/files/673165/output_log.txt)

**Comment by sarbian** [comment]
From the look of it the dll is not present. I don't know what KSP Mod Admin installed but it did not properly did it.

**Comment by Flatfoot** [comment]
I'm not finding any dll files in the dev package.  What's it called and where is it supposed to be located?  Is it possible to download it specifically?

**Comment by Flatfoot** [comment]
Looks like it's trying to create the .dll file.  When is this code executed?  Also, what happens if KSP is not in a "normal" location?
Could it be it doesn't have read/write permissions?

Spitballing here... one of them might stick..

**Comment by Flatfoot** [comment]
Ok, I think KSPModAdmin interaction with Github is the reason.  Your Makefile is looking for a hardcoded filepath.  When I URL install MechJeb from Curseforge.. KSPModAdmin properly sets the project folder name in GameData to "MechJeb2".  When URL installing from github, KSPModAdmin sets the foldername to MechJeb2-2.6.0 (which is the current version).  It also asks you to choose which file to install (if there are multiple versions).  I checked two other mods that I am AVC'ing with github, and they have the version in the mod folder name as well.

  I suspect that when KSPModAdmin does this, it auto-adds the version onto the folder name.  Which makes this not an issue with your code nor with KSPModAdmin itself... just how KSPModAdmin handles things when Github is set as it's AVC URL.

Suggestion, have a note for KSPModAdmin users that they will have to use curseforge for AVC and downloading.

I'll drop a note with KSPModAdmin asking if they can change how it interacts with github.  Meanwhile, is it feasible to make the script auto-detect the folder name, instead of it being hard-coded?   I imagine that it would already know, since it's being called from a file inside that folder.  Just need code to do that.  I will try to cobble something together; but I'm weaksauce when it comes to programming language.

**Comment by sarbian** [comment]
i dont store any working version on github. the build are here https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/
