### ISSUE TITLE
Menu Location

### ISSUE THREAD

**Issue by OfficiallyBrown** [MuMech/MechJeb2#858]
Would it be possible to have more precise control over the menu button location instead of just Top/Bottom/Left/Right? With the mods I have pretty much all those options it ends up overlapping over something, and when I do find a good place for it and go from the VAB to In-game or vice versa, some UI elements move while MechJeb stays the same so it will be clear of icons on one screen but not the other

**Comment by sarbian** [comment]
You can drag the menu button with the right mouse button.
