### ISSUE TITLE
Performance Problems

### ISSUE THREAD

**Issue by Superrick652github** [MuMech/MechJeb2#860]
i have some microbugs everytime in the game. I had install KSP 1.2.2.1622 Mechjeb 2.6.0 on:
"Windows 7 Home" and i try the same at Ubuntu "16.04.1"
System:
CPU
________________________________________________________________________________
Model                : Intel(R) Core(TM) i7 CPU 930 @ 2.80GHz
Logical cores        : 8
CPUID                : GenuineIntel family 6, model 1A, stepping 5

GPU1
________________________________________________________________________________
Display device       : GeForce GTX 760 on GK104 GPU
Display driver       : 376.09

The problem:
- every 4-5 sec the GPU and CPU usage goes down to 0% (tested with "MSI Afterburn") for a very short moment.
- At this moment the game stops.
- Its no matter how much parts i used.
- i have try out play the game without Mechjeb, but there are NO stops.
- yes, graphic settings ultra low, and ultra high tested. -> same problem.

**Comment by sarbian** [comment]
The current dev builds ( https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/ ) should already fix that problem
