### ISSUE TITLE
MechJeb misses the planetary intercept

### ISSUE THREAD

**Issue by mpredosin** [MuMech/MechJeb2#866]
I created a maneuver node using the advanced planetary transfer tool and have it execute the burn.

MechJeb executes the maneuver node....
![20170308111139_1](https://cloud.githubusercontent.com/assets/253549/23719591/e07072a0-03f0-11e7-8140-d03041cca5da.jpg)

It's almost finished...
![20170308111251_1](https://cloud.githubusercontent.com/assets/253549/23719594/e379dc52-03f0-11e7-919b-deb4ea5c9f12.jpg)

but then, the maneuver node moves to a different location with a new delta V just when it gets to the intercept.
![20170308111251_2](https://cloud.githubusercontent.com/assets/253549/23719603/e654e8d6-03f0-11e7-88bb-7d98fc95b303.jpg)

**Comment by sarbian** [comment]
The node moving is actually a stock bug and I can't do much about it.

**Comment by mpredosin** [comment]
Ok thanks.  I'll report the bug to the KSP developers.  Do you happen to know of any way around it?

**Comment by sarbian** [comment]
No, I sent a report a while ago but I did not heard about it since then. It may have been fixed in the next patch, we will see in a couple of weeks.

**Comment by mpredosin** [comment]
I filed a new issue on the KSP bug tracker.  Hopefully, the issue gets more attention now.
http://bugs.kerbalspaceprogram.com/issues/14076

**Comment by lamont-granquist** [comment]
dup of #1002
