### ISSUE TITLE
Fine-Tuning Apoapsis and flameouts (0 ignitions left)

### ISSUE THREAD

**Issue by AscottW** [MuMech/MechJeb2#868]
[Here](https://github.com/MuMech/MechJeb2/files/836254/Installed.KSP.mods.txt) is a list of all of my Mods in case it's needed.

Issue:

- ~100km, MechJeb 2 auto-pilot status changes from "Gravity Turn" to "Fine-Tuning Apoapsis".
- MechJeb 2 throttles down to 0.
- Liquid Engine thruster flames out.
- Remaining ignitions are 0.
- Lost Δv due to early engine flameout.
- Disabling autopilot leads to engine cut-off instead of just leaving throttle where it currently is.

I know I should design my rocket such that, by MECO, I no longer need the first stage. However, I'm not there yet. I still have more to learn about orbital mechanics.

Any ideas on what to do other than forgo autopilot or find another engine configuration?

**Comment by sarbian** [comment]
The MJ settings panel should have a RSS option. When it is activated it should prevent engine shutdown when using the ascent AP. 
It is not perfect but I did not have the time to work on a better solution so far.
