### ISSUE TITLE
Advanced Hohmann transfer planning:  Integrate with Rendezvous pilot and better window control

### ISSUE THREAD

**Issue by Cwhizard** [MuMech/MechJeb2#870]
When setting rendezvous autopilot, it puked because the next window was ;192 orbits away, but literally a 30 second radial out burn with a single 'dawn'  gave it a new window at 1.27 orbits.  Some amount of brute force searching would be nice to identify sub-optimal transfers.  Not everything is  hohmann or bilateral transfers.  Single tangent transfers can often make the transfer happen in real time with close enough to optimal results.

**Comment by lamont-granquist** [comment]
Probably duplicates issues in #1058

**Comment by lamont-granquist** [comment]
Yeah hohmann rendezvous from essentially identical orbits where there is an enormous synodic period is going to fail with the existing two-impulse burn solver.  It needs to be three impulses to change to a phasing orbit and then do a transfer.  After more than 5 years I think this is never getting fixed, so its up to the user to identify and fix the problem.
