### ISSUE TITLE
install on Mac ksp V 1.2.2

### ISSUE THREAD

**Issue by juak123456789** [MuMech/MechJeb2#872]
Hi I cant install it on KSP v1.2.2 on my MAC.
I Copied the Stable Version of Mechjeb2 to the GameData directory. 
But if i start a rocket there is no additional Gui from Mechjeb. 
What i did wrong?

Edit: I write something from add AR202 to a ship. But how can i do this?

Thanks for help.

**Comment by sarbian** [comment]
In the editor part list you should find the AR202 part and add it to your ship.

If you do not want to add part for Mechjeb to work then you have to also install this mod
http://forum.kerbalspaceprogram.com/index.php?/topic/88726-mechjeb-embedded-universal/&page=1

**Comment by juak123456789** [comment]
Thanks this Works.
