### ISSUE TITLE
Mouse cursor flickers in IVA

### ISSUE THREAD

**Issue by MarkGS76** [MuMech/MechJeb2#878]
Hello,
I have an issue with mechjeb 2.6.0 in KSP v1.2.2 x64 (Win7). With mechjeb attached to my vessel, the mouse cursor does not go entirely away in IVA when right-clicking or pessing mouse-look toggle key. Instead, it centers itself in middle of the screen and flickers. Happens only with mechjeb attached (or embedded) in IVA. Is this a known issue?

**Comment by sarbian** [comment]
It is know and fixed in the dev version ( https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/ )
It will be included in the next release when KSP 1.3 is out.
