### ISSUE TITLE
KSP 1.2.9 won't open becuase of MechJeb 2.6.0.0 on Win10

### ISSUE THREAD

**Issue by Zeus1080** [MuMech/MechJeb2#879]
I've read many threads, but none seems to solve my issue.
My KSP keeps crashing on startup only when MechJeb is one of the mods (or even the only mod)
I'm running Windows 10 x64 with GTX 970M and 16GB RAM, so hardware is not the issue (I hope)

[error_log.txt](https://github.com/MuMech/MechJeb2/files/922845/error_log.txt)
[output_log.txt](https://github.com/MuMech/MechJeb2/files/922849/output_log.txt)

There are the error)log and output_log.
Please help

**Comment by sarbian** [comment]
There is no MJ version compatible with 1.2.9

**Comment by Zeus1080** [comment]
When will MJ be compatible with 1.2.9 ?

**Comment by Olympic1** [comment]
Days/weeks after the 1.3 release. KS 1.2.9 are just re-releases for 1.3
