### ISSUE TITLE
Auto-warp broken on KSP 1.3.0

### ISSUE THREAD

**Issue by sworisbreathing** [MuMech/MechJeb2#890]
After updating KSP to version 1.3.0 and updating MechJeb to version 2.6.1.0, I'm hitting a rather annoying bug with auto-warp. I've seen this happen when using ascent guidance,  rendezvous autopilot, and maneuver planner.

Basically what happens is, when auto-warp starts, the camera jumps to way out in space, and then when it tries to fire the engines, the speed displayed on the navball jumps to an insanely high value (like in the tens or hundreds of thousands of meters per second) and the altimeter jumps to several thousand Mm as well. I haven't been able to reproduce it with using keybindings to warp, or the "Warp to next Maneuver" option in map view.

Log is attached. 

[Player.log.txt](https://github.com/MuMech/MechJeb2/files/1040926/Player.log.txt)

**Comment by sarbian** [comment]
I am afraid I have no idea about what is going on there. I did my test with the zip from my thread to be sure and I don't get the problem you describe or the errors I see in your log.
Could you do a test with only MJ installed to make sure it is not an other mod interfering ?

**Comment by sworisbreathing** [comment]
@sarbian I'll try to get a reproducible test case with only MechJeb installed. It'll be a bit tricky to set up, since the ship in question has a PPD-10 attached via an AGU on the bottom of it, and you can't attach parts to the clamp in the VAB.

**Comment by sworisbreathing** [comment]
Okay... this appears to be a bug in KSP itself, triggered by warping while a part attached to an AGU is moving.

With the [attached save](https://github.com/MuMech/MechJeb2/files/1050060/MJTest.zip), the steps to reproduce are:

1. Load quicksave
1. Right-click AGU and click "Free Pivot"
1. Turn SAS on and set orientation to Normal. Note your orbit speed on the navball.
1. While the PPD-10 is still moving, hit the warp key. Notice the ship disappears
1. Drop out of warp. Note your orbit speed on the navball now.

I'll file a bug against KSP and link to here.
