### ISSUE TITLE
Landing Autopilot doesn't account for staged landings

### ISSUE THREAD

**Issue by Xyphos** [MuMech/MechJeb2#895]
if your lander isn't an SSTO and requires staging to land, the staging event never occurs unless you enable the autostage in the utilities menu, and even if enabled, the lander will crash after staging unless you're using a more powerful engine than before because the landing calculations doesn't account for the staged mass change.

I discovered this, while attempting to land on Tylo with a 2-stage descent, 2-stage ascent lander.

**Comment by uxlapogi** [comment]
Can confirm, staging to another less powerful stage with landing autopilot results in rapid unplanned pancaking.

I'd like to add, that it probably isn't only the mass change but also the available thrust changing the required burn time that results in the violent horizontal inflation.

**Comment by lamont-granquist** [comment]
This will not be fixed short of the complete rewrite to use PVG guidance for landing in #1052.
