### ISSUE TITLE
Issue with Asparagus-ized (Asparagized?) fuel flow through decouplers messing up Delta-V stats after launch

### ISSUE THREAD

**Issue by lamont-granquist** [MuMech/MechJeb2#907]
Seem to happen post KSP 1.2 where the decouplers now act like fuel lines, with the fuel flow priority settings controlling which direction the fuel flows.

In the VAB or prelaunch on the pad MJ will get the right dV values.

Then on launch the stages merge like its just one big tank and a bunch of engines.

Example launch is 54 mins into this video:  https://www.twitch.tv/videos/155703821

**Comment by lamont-granquist** [comment]
The plot thickens...   NK says that his decouplers there don't cross-feed.  That more matches what I was thinking which was that RO/RP0 didn't let you cross feed through decouplers because that would be highly ahistorical.  That makes it smell a lot more buggy.  Its possible that whatever RO/RP0 is using to disable crossfeed on decouplers is not playing nice with MechJeb and it might be a bug on either side...

**Comment by sarbian** [comment]
I can't duplicate it in stock 1.3 or 1.2.2. The same vessel loaded in a RO install shows the problem. 
I could not find why so far...
