### ISSUE TITLE
Ascent Guidance: Launching with -90 inclination, circularization burn attempts +90 degrees

### ISSUE THREAD

**Issue by tivec** [MuMech/MechJeb2#908]
I am currently on version 2.6.1.0. I had a contract for a polar orbit and decided to launch southward to meet the orbit. I set up an orbit inclination of -90 degrees and let MJ do its magic. However, the circularization burn was completely opposite direction, as if I had done a 90 degree orbit, and the vessel tried a 180 degree plane change by burning retrograde... 

While I can wait half a rotation to go 90, shouldn't it try to circularize in the prograde direction?

**Comment by sdfg2** [comment]
I just discovered this as well.  My current workround is to use ascent guidance to get me the AP, and then a maneuver node to circularize.  Of course, the problem with that is it doesn't set the orientation for the burn without an 'adjust orbit' mode. :-(

**Comment by lamont-granquist** [comment]
@sarbian this is a dup of the issue fixed by 14b8a17c5ef3c376fa2cc031eced3b384a705b2d

**Comment by sarbian** [comment]
Fixed then
