### ISSUE TITLE
Sr Docking Module and Port do not work correctly

### ISSUE THREAD

**Issue by joannplano2005** [MuMech/MechJeb2#912]
Witness many problems.
1. Rendezvous Autopilot does not work if your in same orbit as target. If you start out with target higher than yourself, then rendezvous autopilot will work.
2. Docking using Sr docking ports do not work correct. You have to target the opposite side of the module that you want to dock to. 
3. Sr. Docking Port and Module will not mate together.

**Comment by Starwaster** [comment]
2 and 3: MJ2 can't stop two compatible ports from docking if they are in range. You have your Sr ports on backwards. The side that actually does the connecting has a little window and a handle, just like the medium sized port.

**Comment by joannplano2005** [comment]
With the normal port, I just grab and stick it on top or sides of and a object. If I want it to be on bottom, then I have to reverse it 180 degrees.So with a Sr port I have to first stick it onto the top or sides an object then reverse it 180 degrees before it will work correctly? I will check and see where the window and handle is located.

JoAnn Donaldson



On Tuesday, August 1, 2017, 1:50:54 PM CDT, Starwaster <notifications@github.com> wrote:


2 and 3: MJ2 can't stop two compatible ports from docking if they are in range. You have your Sr ports on backwards. The side that actually does the connecting has a little window and a handle, just like the medium sized port.

**Comment by Commissar0617** [comment]
mechjeb does not handle parts at all. user error on #2 and #3
