### ISSUE TITLE
Attitude Adjustment problems

### ISSUE THREAD

**Issue by Atario** [MuMech/MechJeb2#919]
* When "Low Pass Filter" is turned off, Tf fields are hidden
* When "Tf auto-tuning" is turned off, changes to PID factor fields are ignored
* "Reset" does not reset "Deadband" nor "Maximum Relative Angular Velocity"
* The three MOI values (visible in "Show Numbers") can become swapped around when vessel is split from a larger one, i.e.:
  * Design a vessel that has very different pitch/roll/yaw MOI values (e.g., long and skinny, or book-shaped), with docking ports
  * Attach copies of the vessel to itself by the ports
  * Launch or Hyperedit to orbit
  * Decouple subvessels
  * Result:  some will have the three MOI value shuffled, resulting in crazy attitude handling

**Comment by sarbian** [comment]
* Normal since Tf is related to the low pass filter. I added some space to the left to show it s a subsection. And I just changed Tf to be (1,1,1) when the filter is deactivated.
* Fixed
* Fixed
* I don't see how the value could be actually messed up. Are you sure it s not that the "control from here" part moved to a side facing docking port ?

**Comment by Atario** [comment]
Picking a different "control from here" part doesn't reshuffle the MOI value placements (though it does slightly alter the exact values, oddly enough).  At any rate, the other values like torque and so on don't get seem to shuffled, so mismatches happen, whatever the case.

When the subvessel doesn't get shuffled, controlling from a differently-oriented part doesn't screw up control, either.  But when they do get shuffled, every control part gives the same dysfunction.

Some further experimentation reveals that whether this happens does seem depend on whether the root part of the subvessel faces the "right way" on separation (meaning, along the same axis as the overall vessel… or something.  It's hard to tell exactly what's going on).

Go ahead and try it.  If you need me to, I can record a video of it or whatever is required.

Oh, also I forgot to mention originally:

* With "Tf auto-tuning" off, the three "Tf (s)" fields seem to be mislabeled P/Y/R instead of P/R/Y

**Comment by Atario** [comment]
Another thing I forgot to write:  if the Tf values are no longer relevant when low pass filtering is turned off, why do the K*x* numbers not change?  (Although they don't respond to the PID factors changing either in this state… possibly just a numbers-display bug?)

**Comment by lamont-granquist** [comment]
MOI issues with different "control from here" is due to KSP game bugs.  I thought that was fixed in sufficiently late KSP versions, but have entirely forgotten how late it needs to be.

**Comment by Atario** [comment]
I'm on 1.2.2 for what it's worth

**Comment by Atario** [comment]
Also, I should add that the MOI values being swapped does not seem to affect the regular stock SAS's behavior.

**Comment by lamont-granquist** [comment]
Still an open issue on the squad bugtracker:  http://bugs.kerbalspaceprogram.com/issues/13282
