### ISSUE TITLE
Docking autopilot override the 'Speed Limit' at final docking sequence.

### ISSUE THREAD

**Issue by hraban35** [MuMech/MechJeb2#927]
In the final approach to docking the 'Docking autopilot does not limit the speed by 'Speed limit'. So heavyer Parts overshhot the position and wiggle away.

**Comment by hraban35** [comment]
KSP 1.3. Stock System. RCS with 'old' RCS-Module.

**Comment by Commissar0617** [comment]
+1 on dev 747
have massive issues with overshoot, and exceeding speed limit. was not problematic prior to 1.3. same craft as prior to 1.3.

**Comment by doc4kidz** [comment]
Goes much faster than set speed limit, uses WAAAY too much mono propellant and overshoots the target
