### ISSUE TITLE
No MechJeb Tab or Parts Showing Up

### ISSUE THREAD

**Issue by konigsberg7** [MuMech/MechJeb2#933]
As the title says, I've been unable to get the tab or any of the parts to show up.

I've tried the following:

-Fresh install on my G Drive
-Moving the install to my H Drive
-Installing it manually (while deleting all other mods i.e mechjeb being the only mod installed)
-Installing it using CKAN while it also being the only mod
-Trying the dev version via CKAN while it also being the only mod
-I tested each iteration/attempt in sandbox mode
-Deleting the game completely and installing it via CKAN as the only mod (This will be the install of the output log I postt).

[output_log.txt](https://github.com/MuMech/MechJeb2/files/1272587/output_log.txt)

Edit: Also tried the dev version on my fresh install. Still a no go.

**Comment by sarbian** [comment]
The log looks fine. you added the AR202 part to your ship, right ?

**Comment by konigsberg7** [comment]
It doesn't even show up in my parts list.

**Comment by sarbian** [comment]
The name of the part is "MechJeb 2 (AR202 case)". As there is no errors in your log and MJ seems to be installed fine this is the only things I see that could be wrong.

**Comment by AfterQuarter** [comment]
sarbian I have a problem.
I do have the MechJeb 2 (AR202 case)
but it wont work.
I also downloaded it from the ksp curse website 4 times.
