### ISSUE TITLE
Feature request: flag check for ModuleCommand's requiresPilot 

### ISSUE THREAD

**Issue by seanth** [MuMech/MechJeb2#934]
It would be nice to show/hide mechjeb functions based on whether a pilot is present in a pod.

Something like:

```
        MechJebLocalSettings {
            MechJebModuleSpaceplaneGuidance { unlockFlag = requiresPilotTrue }
        }
```

Then parts of mechjebcore could be added to command pods using module manager, but would only be available if a pilot was present. Could enhance roleplaying so players could "have the pilot" do things.

**Comment by lamont-granquist** [comment]
PR for this would be acceptable, but without someone volunteering to do the coding I doubt it'll happen.
