### ISSUE TITLE
final descent fails to slow craft

### ISSUE THREAD

**Issue by Commissar0617** [MuMech/MechJeb2#945]
okayu,  i got it to work at least one, partially, but it touched down at 50  m/s... the final descent mode is trash. it uses maybe 15% throttle, and  actually INCREASES velocity.
on the latest dev
craft has a duna twr of ~4.5, and is ~200t in mass. 

https://youtu.be/Aj8QJ9JMK44

video of the entire landing sequence (cut short a the end, but it's like that all the way down)

**Comment by Commissar0617** [comment]
okayu, i got it to work at least one, partially, but it touched down at 50 m/s... the final descent mode is trash. it uses maybe 15% throttle, and actually INCREASES velocity.

**Comment by lamont-granquist** [comment]
landing issues have been rolled up under the #1052 EPIC
