### ISSUE TITLE
Mechjeb Dev749 - Not Landing At Selected Coordinates

### ISSUE THREAD

**Issue by Messernacht** [MuMech/MechJeb2#948]
**KSP**
- 1.3.1 Windows 64bit

**Problem**
- Ships under MechJeb Landing Guidance landing well off-course

**Mods Installed**
B9 Aerospace
BoulderCo
Chatterer
Deployable Engines
Community Category Kit
Community Resource Kit
DmagicOrbitalScience
EvironmentalVisualEffects
Firesplitter
JSI
JX2Antenna
KAS
KIS
Kopernicus
KW Rocketry
MarkIVSystem
MechJeb2 (Dev 749)
ModularFlightIntegrator
NearFutureConstruction
NearFutureElectrical
NearFutureLaunchVehicles
NearFutureProps
NearFutureSolar
NearFutureSpacecraft
New_Horizons
OPT
PlanetaryBaseTech
REPOSoftTech
Smokescreen
Squad (of course)
StationPartsExpansion
ThunderAerospace
TriggerTech
WildBlueIndustries
ModuleManager 2.8.1

**Reproduction Steps**
Achieve stable orbit around body
- Select target on moon
- Activate Landing Guidance
- Landing Guidance will complete burns, placing landing point at best 40km behind selected target, or on opposite side of body

**Log**
[output_log.txt](https://github.com/MuMech/MechJeb2/files/1451356/output_log.txt)

**Comment by Messernacht** [comment]
Have further tested, and issue appears to mostly happen on bodies added for New Horizons.

**Comment by aaamoeder** [comment]
Same for me, entire landing part seems messed up.
If I pick land at target it seems as if it tries to land as far off of that point as possible, and when i do all the burns except the landing burn itself and ask it to land "somewhere" it messes up the landing.

KSP

1.3.1 Windows 64bit

Mods Installed

MechJeb2
xScience
ForScience
AutomatedScreenshots
CommunityCategoryKit
ModuleManager
MechJebForAll
KerbalEngineerRedux
BetterBurnTime
BetterTimeWarpCont
B9PartSwitch
VaporVent
InterstellarFuelSwitch-Core
IndicatorLights
KerbalJointReinforcement
KIS
CapCom
ColorCodedCans
KAS
EasyVesselSwitch
DMagicScienceAnimate
ContractParser
ProgressParser
ContractsWindowPlus
EnvironmentalVisualEnhancements
