### ISSUE TITLE
Rover Autopilot: heading control seems broken, build 751

### ISSUE THREAD

**Issue by Azimech** [MuMech/MechJeb2#953]
Temporarily changed from the last official release to see the new features. Driving on Duna and loading the last saved game, it won't steer towards the set heading. It does use stability control with the gyroscopes to return to prograde while drifting.

**Comment by TheKurgan** [comment]
Tested build #760 on a fresh install (stock plus MechJeb) Rover still seems to be 180° off from its proper heading when travelling to a waypoint.

**Comment by sarbian** [comment]
I'll need a demo rover then because it was doing that without the patch with the one I used to test...

**Comment by TheKurgan** [comment]
You're saying it's working fine now? If that's the case I have something messed up.... I'll retest at lunch time.

**Comment by TheKurgan** [comment]
Ok here we go, very fresh install of KSP, part database and all logs and such cleared before test. 

https://youtu.be/uDXNtGIl0P8

![mjdownload](https://user-images.githubusercontent.com/19254618/33279947-6a5f0470-d36e-11e7-809d-0f6be25d4526.jpg)

![gamedatass](https://user-images.githubusercontent.com/19254618/33279949-6ad03ac8-d36e-11e7-89b1-6a5a4355e5cc.jpg)
![mjtestrover](https://user-images.githubusercontent.com/19254618/33279950-6adbb16e-d36e-11e7-959f-73fde5ab763b.jpg)

**Comment by TheKurgan** [comment]
[MJ Test Rover.zip](https://github.com/MuMech/MechJeb2/files/1506896/MJ.Test.Rover.zip)

**Comment by TheKurgan** [comment]
Maybe I have done something dumb... but I don't think so ;)

**Comment by sarbian** [comment]
No, I was the one doing dumb things. I tested with the only stock rover that has inverted controls...

So now I don't understand what this issues is about...

**Comment by TheKurgan** [comment]
Oh... lol, sorry, the inverted controls... that sounds like something I would do. Well, I hope it's something simple, good luck, and thanks for your work. There is nothing else like it.

**Comment by TheKurgan** [comment]
Closed, but it's still an issue. The Rover will not follow a waypoint. I just did the same testing using the same craft as above... same esult.
