### ISSUE TITLE
Can I participate in language localization?

### ISSUE THREAD

**Issue by RonnyWu** [MuMech/MechJeb2#968]
I want to participate in localization,
support more languages, can you give me an example or specification?

Please leave localization guidelines for more languages.

I am a Chinese player, I think I should be involved, at least I can translate Simplified Chinese
and Traditional Chinese.

Looking forward to your reply. Though I do not know game development, but I am an Android developer, to give an example, I think i can be competent to localization modify.

**Comment by sarbian** [comment]
Hi. I will have a look at starting MJ localization in early 2018. Feel free to remind me about it late January.

**Comment by RonnyWu** [comment]
Oh,Great.
I'll remind you.

**Comment by CrazyTommyK** [comment]
I want to translate MJ2 on russian.
Work is in progress. Names and descriptions are finished. But i must make a huge part of work. If you can and want to help me send e-mail to timagejmer@gmail.com 
Sory, bad english😥

**Comment by Xteuk** [comment]
I was just thinking the same : I'll be happy participating in french MJ translation !
( now that we have the game translated in french, not officially yet, though )

**Comment by sarbian** [comment]
Bonne idée, ça me fera des vacances.

**Comment by RonnyWu** [comment]
@sarbian Hey, brother, maybe I should remind you to prepare to support localization?

**Comment by RealKolago** [comment]
If you need a german translation, i can help.

**Comment by RonnyWu** [comment]
@sarbian About to enter in February.Maybe it should be localized?

**Comment by sarbian** [comment]
Sorry for the lack of updates. I did some test and it showed that I need to rewrite the UI before doing any localization work. With the old UI it makes the performance really worse.
I started doing some work on that but currently I do not have the time. Hopefully I will have some more time later but you will have to wait for now...

**Comment by lamont-granquist** [comment]
There's now a localization framework:  https://github.com/MuMech/MechJeb2/pull/1190
