### ISSUE TITLE
Rover Autopilot does not follow waypoints because it cannot set heading

### ISSUE THREAD

**Issue by drhay53** [MuMech/MechJeb2#980]
There have been some posts in the KSP forum thread about this issue, but I don't see an issue here on github (except this one, https://github.com/MuMech/MechJeb2/issues/953, which was closed but the problem still exists), so I'm officially opening one.

I am using the Dev releases through CKAN, and this has been an issue since ~September 2017. 

If you use the rover autopilot to set a waypoint, and then tell MJ to 'drive', it does not change the heading, and therefore cannot follow any waypoints. 

I believe this bug was introduced in this PR: https://github.com/MuMech/MechJeb2/commit/65eafbe720bfa20150ebb71594ac18fbd7d73fde

Specifically, my guess is that it has something to do with the changes in line 110 in MechJeb2/MechJebModuleRoverWindow.cs, and/or line 576 in MechJeb2/MechJebModuleWaypointWindow.cs

**Comment by merket** [comment]
I see a fix above, but could this still be an issue? I'm having problems with rover autopilot, no matter which controller I run from.

**Comment by drhay53** [comment]
My understanding was that holding 'alt' while clicking drive was the way to get it to work, but that sarbian was going to get rid of the 'alt' requirement. It was working with 'alt' for me last I checked. 
Not every fix on github makes it into the release version quickly, so try pressing 'alt' while clicking drive.

**Comment by sarbian** [comment]
It was fixed but I can comment on your problem since you did not give the KSP and Mechjeb version you use
