### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by EoD** [MuMech/MechJeb2#984]
Would it be possible to open up the (official?) wiki for people to register and contribute? 
http://wiki.mechjeb.com/

If not, could the github wiki be used instead and added with some documentation?
https://github.com/MuMech/MechJeb2/wiki

**Comment by sarbian** [comment]
I do not control the old wiki. Github Ziki is open so you can add new pages.

**Comment by EoD** [comment]
@r4m0n As you seem to be the owner, would you open the wiki to the public?

**Comment by sarbian** [comment]
FFS

**Comment by EoD** [comment]
@sarbian FFS?

**Comment by EoD** [comment]
As you closed this bug report without any explanation, I will assume that it was an accident and I will continue here until it is reopened.

The wiki I posted above, does not seem to be opened (r4m0n has not been active for a couple of weeks on github), so I started copying pages from the old wiki to the github wiki.
Starting with the version history: https://github.com/MuMech/MechJeb2/wiki/Version-history

@sarbian Is this the way you prefer it? Don't you want to prefer a markdown changelog inside the repo?

**Comment by sarbian** [comment]
Yes, moving the docs over github seems like the best idea. Thanks for working on it.

**Comment by EoD** [comment]
https://github.com/MuMech/MechJeb2/wiki/Ascent-Guidance

I added some more information about Ascent Guidance, combining information from the old wiki, the forums and from the top of my head. I decided to use Markdown instead of wiki syntax, so it should be easier for others to edit.

Can you have a look at the "TODO" parts and see if you can easily replace some of them?

**Comment by lamont-granquist** [comment]
Closing this as its sort of an endlessly open-ended issue.  The GH Wiki is the place though, the old wiki is now a malware site out of anyone control and URLs to it really need to get scrubbed from the universe.
