### ISSUE TITLE
Ascent Guidance miscalculates rendezvous time

### ISSUE THREAD

**Issue by EoD** [MuMech/MechJeb2#985]
When I press "Launch to Rendezvous", the launch is too late and the orbiting partner is long gone when I reach it. It does improve, when I increase "Orbit altitude" to a higher value.
![image](https://user-images.githubusercontent.com/293499/35943203-9570fdc6-0c58-11e8-8912-6c7143dc4953.png)
![image](https://user-images.githubusercontent.com/293499/35943346-f852ee90-0c58-11e8-862c-a40ecea59004.png)

I am using Mechjeb 2.7.0.

As there seem to be a (missing?) correlation between the orbit altitude and the rendezvous timer, would it be possible to auto-set the orbit altitude to something similar to the "target altitude/apoapsis"? This would avoid unnecessary fuel consumption.

**Comment by sarbian** [comment]
This function needs the vessel to be launched once untill circularisation for MJ to know the time to reach orbit . Then you do do a revert to launchpad and use the launch to rdv.

**Comment by EoD** [comment]
@sarbian I am a bit confused. I did launch the vessel and quickloaded (as Minmus has no spaceports), but it didn't work. What exactly do you mean?

**Comment by sarbian** [comment]
Hum, I am not sure it would work when launching from anywhere. The recoreder may not start... 
I'll have to check

**Comment by EoD** [comment]
Can you explain to me (I have no clue), why it is not possible to calculate an estimated rendezvous by using the targets orbit (median of periapsis/apoapsis), the current position (or just the angle?) and the available thrust?
Of course assuming that there is no atmosphere.

**Comment by sarbian** [comment]
Where did I say it is not possible ? The code is not there. If someone want to write it they are welcome to do it. 
Currently we have a solution that work well for most needs (launch from a space center) and the rendez-vous autopilot for other cases.

**Comment by dlrk2** [comment]
Does the launch and revert have to be done every launch, or can an old/original number be reused for a similar launch vehicle?

**Comment by sarbian** [comment]
It saves the value for a vessel name.

**Comment by lamont-granquist** [comment]
It is entirely possible but the problem of doing it without a prior rocket launch is pretty much a post-grad level trajectory optimization problem -- particularly the "without overshooting" bit.  I've spent the past 6-8 months off and on trying to teach myself how to do it, and I took graduate level quantum mechanics in college...

**Comment by lamont-granquist** [comment]
#1061 is the rewrite that will eventually be able to solve this right, closing as a dup of that.
