### ISSUE TITLE
Unable to use ascent guidance to get to specific orbit plane in RSS.

### ISSUE THREAD

**Issue by lzylzylzy130** [MuMech/MechJeb2#989]
Using KSP1.2.2 with RSS and RO.
Tried to launch a rocket into the target’s orbit plane but never success. There is always a terrible relative inclination.
I’m just wondering if there is any way to get the ascent guidance work properly? Or if it’s just because I  have made some mistakes in the operation?
It’s really a good mod and thanks for developers’ work.

**Comment by sarbian** [comment]
First which version of MJ are you using ? v2.6.0 or the custom dev builds for OR ( https://ksp.sarbian.com/jenkins/job/MechJeb2-RO/ )
The later has a lot of fixes that could help and some new ascent guidance config just for RO/RSS ( doc : https://github.com/lamont-granquist/MechJeb2/wiki )

**Comment by lzylzylzy130** [comment]
Wow!
Thanks for your early reply! The information really helps. Many of my friends get the same problem since we are using the 2.6.0. And now we got the solution!
Thanks! It’s quite amazing!
