### ISSUE TITLE
[UI Issue] Move MJ access button to avoid overlapping new stock UI

### ISSUE THREAD

**Issue by asmi84** [MuMech/MechJeb2#99]
I've just installed MJ 2.0.8 and noticed that bu menu button moved up so no it's precisely on top of new "info" buttons in map view. Can you please move it down? OR - better yet - enable user to move it whereever it wants (personally I'd put it somewhere along bottom corner as position to the right interferes with VAB staging).

**Comment by plaguewolf** [comment]
fourth. please, for the love of god, my OCD. dat overlap.

**Comment by sarbian** [comment]
You can move the button with a left mouse drag and the settings menu as options to move it on other side of the screen.
