### ISSUE TITLE
pod doesn't load

### ISSUE THREAD

**Issue by a101010** [MuMech/MechJeb2#995]
Mechjeb 2_2.7.0, ksp 1.3.1.1899 x64

The AR202 loads, but the pod doesn't. Log has the following repeated 8 times
[output_log.txt](https://github.com/MuMech/MechJeb2/files/1752125/output_log.txt)

WheelCollider requires an attached Rigidbody to function.
 
(Filename:  Line: 239)

**Comment by sarbian** [comment]
The pod was removed since its legs were breaking a lot of things and I do not have the models file to fix it.
