### ISSUE TITLE
[KSP 1.3.1] OPM_Galileo Disables ability to pick landing target/coordinates on minmus while in orbit.

### ISSUE THREAD

**Issue by GhastlyKerbal** [MuMech/MechJeb2#996]
While in orbit around minmus picking a landing target does not display coordinates and only focuses on minmus. As far as I can tell, minmus is the only planet/moon affected. Disabling OPM fixes this but its one of my favorite mods and I'd rather not play without it if possible. Below are two screenshots, one showing the mod working without OPM, the other showing that you cant see or select coordinates with OPM installed. https://nofile.io/f/MZAWEOxsSM1/output_log.txt
Without OPM
![without opm](https://user-images.githubusercontent.com/36802807/36635807-8bb04fa6-1989-11e8-9239-d6160ff3366e.jpg)
With OPM
![withopm](https://user-images.githubusercontent.com/36802807/36635852-3ceca49a-198a-11e8-82ab-afa90e3cc96d.jpg)

**Comment by sarbian** [comment]
As explained in Galileo thread this is a bug in the current version of Kopernicus that deletes the biomes maps of bodies.
I added some code in the dev version so that MJ handles it better but the true fix is in Kopernicus.
