### ISSUE TITLE
Mechjeb can fully control unmanned probe even if out of signal

### ISSUE THREAD

**Issue by MaximeBrean** [MuMech/MechJeb2#997]
I don't know if this behavior is intended or not, but MechJeb can still operate an unmanned probe even if the vessel is out of signal range.
By operate, I mean change orientation and thrust which is something currently impossible with manual controls.

I noticed this in career mode and I only have unlocked the "Maneuver and Translatron" upgrade.

**Comment by lamont-granquist** [comment]
gonna consider this a dup of #382
